### ISSUE TITLE
Precompile JuMP

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#1181]
When the API settles down, we should add `Base.precompile` statements to improve loading time.

**Comment by blegat** [comment]
Isn't it already done ?

https://github.com/JuliaOpt/JuMP.jl/blob/0b849149bbc1866c652051311da8990969813efb/src/JuMP.jl#L11

**Comment by mlubin** [comment]
I'm referring to https://github.com/JuliaOpt/JuMP.jl/blob/release-0.18/src/precompile.jl.

**Comment by odow** [comment]
Started by #2484. We should continue to investigate this and track down causes of compilation latency, particularly after the next MOI release.

**Comment by odow** [comment]
Closing in favor of #2735
