### ISSUE TITLE
@test_macro_throws and coverage

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#1331]
It seems that the lines covered by tests using `@test_macro_throws` are not detected as covered.
It has been several PR that I have noticed this and when I debug it locally by adding a `println` just before the error, the printing message is shown when I call the macro outside `@test_macro_throws` but it is not shown when it is called inside `@test_macro_throws`.

**Comment by odow** [comment]
This seems to work now. For example, the errors thrown by indicator constraints 
https://github.com/jump-dev/JuMP.jl/blob/52b1b385b6a02bb08964b35403b6d7aee4252281/src/indicator.jl#L22
and tested with `@test_macro_throws`
https://github.com/jump-dev/JuMP.jl/blob/52b1b385b6a02bb08964b35403b6d7aee4252281/test/constraint.jl#L302-L304
are covered: https://codecov.io/gh/jump-dev/JuMP.jl/src/master/src/indicator.jl
