### ISSUE TITLE
[release-0.18] Callback test failure on Julia 1.0

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#1539]
https://github.com/JuliaOpt/CPLEX.jl/pull/184#issuecomment-428737947

**Comment by IssamT** [comment]
I think, you meant this comment https://github.com/JuliaOpt/CPLEX.jl/pull/184#issuecomment-428736054

**Comment by odow** [comment]
Closing as won't-fix. This relates to JuMP 0.18.
