### ISSUE TITLE
Make JuMP tests callable from an external package

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#1711]
The tests that are run for `JuMP.Model` and `JuMPExtension.MyModel` should also work for `StructJuMP.StructuredModel`. Currently, if StructJuMP wanted to run these tests, it would have to include, e.g. `constraint.jl` and then call `constraints_tests(StructuredModel, ...)` but including `constraint.jl` also run the tests for `JuMP.Model` and `JuMPExtension.MyModel`. It would be nice to define the tests and run the tests in separate files so that StructJuMP can define them without running them on `JuMP.Model` and `JuMPExtension.MyModel`.

**Comment by odow** [comment]
I'm actually going to re-open this until we have something documented. Were essentially there, though.

```julia
import JuMP
include(joinpath(dirname(dirname(pathof(JuMP))), "test", "Kokako.jl"))
const MODULES_TO_TEST = Kokako.include_modules_to_test(JuMP)
Kokako.run_tests(
    MODULES_TO_TEST,
    JuMPExtension.MyModel,
    JuMPExtension.MyVariableRef;
    test_prefix = "test_extension_",
)
```
