### ISSUE TITLE
Decide whether to export MOI.

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#1789]
I'm conflicted on whether its appropriate to export an alias for an imported module. Should `MOI` be named `_MOI`? Should we reexport all of MOI anyway? 

Ref #1779

**Comment by blegat** [comment]
Currently we have
```julia
julia> using JuMP

julia> MOI
MathOptInterface
```
I would vote for keeping this behavior.

**Comment by mlubin** [comment]
The underlying design issue is that users are forced to interact with two APIs at once in order to accomplish basic tasks like checking statuses. I'll mark this for 1.0. For 0.19 we can get by as is.

**Comment by odow** [comment]
This issue potentially resolved by embedding the MOI docs into JuMP: https://github.com/jump-dev/JuMP.jl/pull/2522.

I haven't seen many users confused with the `MOI.` I think MOI functions should stay unexpected to avoid clashes with things like `get, so this is really a matter of the enums. If these are better documented/accessible from the JuMP documentation then I think we're okay.

**Comment by blegat** [comment]
I'm also in favor of 2.
