### ISSUE TITLE
inequality syntax for set constraints

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/JuMP.jl#1798]
As discussed on Gitter, for the sake of a minimal and consistent interface for generic set constraint modeling, let's remove the special case `@SDconstraint` and generalize it for other sets.

The current syntax `@constraint(model, X in SomeSet())` is great as a foundation, but some users will prefer to write some constraints with inequalities, like `@constraint(model, X >= Y, SomeSet())` (which specifies that the inequality is with respect to `SomeSet()` instead of the equivalent `@constraint(model, X - Y in SomeSet())`.

There are many directions we could go from there for further improving convenience and usability, and @blegat made some good suggestions - those are more complicated and require more discussion re: DCP modeling in JuMP so let's have a separate longer term issue for that. I'm certainly eager to help on the DCP modeling aspect down the track so I'm keen to discuss at JuMP-Dev.

**Comment by odow** [comment]
Now we have constraint tags (#2574), we can implement this trivially. 

While doing so, we should consider removing `@SDconstraint`

Instead of 
```Julia
@SDconstraint(model, X >= Y)
```

```Julia
@constraint(model, X - Y >= 0, PSD)
```
