### ISSUE TITLE
Exported functions with no doc

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#1825]
Edit(odow): updated 31-03-2021
 - [ ] `MOI`
 - [ ] `MOIB`
 - [ ] `MOIU`
 - [ ] `VariableNotOwnedError`
 - [ ] `moi_add_constraint`
 - [ ] `moi_add_to_function_constant`
 - [ ] `parse_SD_constraint`
 - [ ] `parse_SD_constraint_expr`
 - [ ] `parse_constraint`
 - [ ] `parse_constraint_expr`
 - [ ] `parse_constraint_head`
 - [ ] `parse_one_operator_constraint`
 - [ ] `parse_ternary_constraint`
 - [ ] `parse_ternary_variable`
 - [ ] `parse_variable`
 - [ ] `variable_type`
 - [ ] `vectorize`
  
Script
```julia
deprecated = [
    :getdual,
    :getobjectivebound,
    :getobjectivevalue,
    :getvalue,
    :linearterms,
    :numnlconstr,
    :numvar,
    :set_coefficient,
    :set_parameter,
    :set_parameters,
    :setlowerbound,
    :setupperbound,
    :setvalue,
    :solve,
    :with_optimizer,
    :writeLP,
    :writeMPS,
]
for name in filter(n -> !(n in deprecated), names(JuMP))
    f = getfield(JuMP, name)
    s = Base.Docs.doc(f)
    if s.content[1].content[1] == "No documentation found."
        println(" - [ ] `", name, "`")
    end
end
```

**Comment by blegat** [comment]
Isn't the 1.0 milestone more appropriate ? This is not a regression from v0.18

**Comment by mlubin** [comment]
Of these, I'd say that only `index` and `optimizer_index` need to be documented for 0.19. The rest are not that essential for typical usage.

**Comment by odow** [comment]
Here's an updated list:

 -[ ] `@NLconstraints`
 -[ ] `@NLexpressions`
 -[ ] `@SDconstraints`
 -[ ] `@expressions`
 -[ ] `AUTOMATIC`
 -[ ] `AbstractJuMPScalar`
 -[ ] `AbstractModel`
 -[ ] `AbstractVectorSet`
 -[ ] `AffExpr`
 -[ ] `DIRECT`
 -[ ] `GenericAffExpr`
 -[ ] `GenericQuadExpr`
 -[ ] `IJuliaMode`
 -[ ] `JuMP`
 -[ ] `LinearTermIterator`
 -[ ] `MANUAL`
 -[ ] `MOI`
 -[ ] `MOIB`
 -[ ] `MOIU`
 -[ ] `ModelMode`
 -[ ] `NLPEvaluator`
 -[ ] `NonlinearConstraintIndex`
 -[ ] `NonlinearExpression`
 -[ ] `NonlinearParameter`
 -[ ] `PrintMode`
 -[ ] `QuadExpr`
 -[ ] `QuadTermIterator`
 -[ ] `REPLMode`
 -[ ] `ScalarVariable`
 -[ ] `SymMatrixSpace`
 -[ ] `UnorderedPair`
 -[ ] `VariableInfo`
 -[ ] `VariableNotOwnedError`
 -[ ] `add_NL_constraint`
 -[ ] `constraint_ref_with_index`
 -[ ] `constraint_string`
 -[ ] `constraint_type`
 -[ ] `error_if_direct_mode`
 -[ ] `getdual`
 -[ ] `getobjectivebound`
 -[ ] `getobjectivevalue`
 -[ ] `getvalue`
 -[ ] `isequal_canonical`
 -[ ] `jump_function_type`
 -[ ] `linearterms`
 -[ ] `map_coefficients`
 -[ ] `map_coefficients_inplace!`
 -[ ] `model_string`
 -[ ] `moi_add_constraint`
 -[ ] `moi_add_to_function_constant`
 -[ ] `moi_bridge_constraints`
 -[ ] `moi_function_type`
 -[ ] `moi_mode`
 -[ ] `nl_constraint_string`
 -[ ] `nl_expr_string`
 -[ ] `numnlconstr`
 -[ ] `numvar`
 -[ ] `object_dictionary`
 -[ ] `parse_SD_constraint`
 -[ ] `parse_SD_constraint_expr`
 -[ ] `parse_constraint`
 -[ ] `parse_constraint_expr`
 -[ ] `parse_constraint_head`
 -[ ] `parse_one_operator_constraint`
 -[ ] `parse_ternary_constraint`
 -[ ] `parse_ternary_variable`
 -[ ] `parse_variable`
 -[ ] `register`
 -[ ] `reverse_sense`
 -[ ] `set_NL_objective`
 -[ ] `set_coefficient`
 -[ ] `set_objective`
 -[ ] `set_optimize_hook`
 -[ ] `set_parameter`
 -[ ] `set_parameters`
 -[ ] `setlowerbound`
 -[ ] `setupperbound`
 -[ ] `setvalue`
 -[ ] `show_backend_summary`
 -[ ] `solve`
 -[ ] `variable_ref_type`
 -[ ] `variable_type`
 -[ ] `vectorize`
 -[ ] `with_optimizer`
 -[ ] `writeLP`
 -[ ] `writeMPS`

Obtained with the following code:
```Julia>
for name in names(JuMP)
    f = getfield(JuMP, name)
    s = Base.Docs.doc(f)
    if s.content[1].content[1] == "No documentation found."
        println(" -[ ] `", name, "`")
    end
end
```

**Comment by odow** [comment]
With #2731 the list is now
 - [ ] `MOI`
 - [ ] `MOIB`
 - [ ] `MOIU`
 - [ ] `parse_SD_constraint`
 - [ ] `parse_SD_constraint_expr`
 - [ ] `parse_constraint`
 - [ ] `parse_constraint_expr`
 - [ ] `parse_constraint_head`
 - [ ] `parse_one_operator_constraint`
 - [ ] `parse_ternary_constraint`
 - [ ] `parse_ternary_variable`
 - [ ] `parse_variable`
 - [ ] `vectorize`

The `parse_` methods can be covered by https://github.com/jump-dev/JuMP.jl/issues/2236
The `MOI` structs can be covered by #1789 

Therefore, I'm going to close this issue.
