### ISSUE TITLE
dual & shadow_price do not work on sparse arrays

### ISSUE THREAD

**Issue by ndinsmore** [jump-dev/JuMP.jl#1876]
While ```value``` works on variables stored in a sparse array.  ```dual``` and ```shadow_price``` do not work on constraints stored in a sparse array.  This behavior seems inconsistent.

**Comment by blegat** [comment]
You mean sparse array or Containers.SparseAxisArray ? Have you tried broadcasting ? Could you give a code sample ?

**Comment by ndinsmore** [comment]
The scope I meant was both broadcasting SparseVector & SparseMatrixCSC.  Below is an example.

```julia
using JuMP
using Clp

m = Model(with_optimizer(Clp.Optimizer))

@variable(m, 0 <= x <= 1)
@variable(m, 0 <= y <= 1)
@variable(m, 0 <= z <= 1,)
c=@constraint(m, x + y + z >= 1)
@objective(m, Min, 2x + y + z)

spv_var=sparsevec([1,3,5],[x,y,z],5)
sp_var=sparse([1,3,5],[1,3,5],[x,y,z],5,5)

spv_con=sparsevec([3],[c],5)
sp_con=sparse([3],[3],[c],5,5)

JuMP.optimize!(m)

#Value  Work
value.(spv_var)
value.(sp_var)

#Dual  does Not Work
dual.(spv_con)
dual.(sp_con)

#shadow_price  does Not Work
shadow_price.(spv_con)
shadow_price.(sp_con)
```

**Comment by mlubin** [comment]
The error message, for completeness:
```julia
julia> dual.(spv_con)
ERROR: MethodError: no method matching zero(::Type{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},ScalarShape}})
Closest candidates are:
  zero(::Type{LibGit2.GitHash}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LibGit2/src/oid.jl:220
  zero(::Type{Pkg.Resolve.VersionWeights.VersionWeight}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/resolve/VersionWeights.jl:19
  zero(::Type{Pkg.Resolve.MaxSum.FieldValues.FieldValue}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/resolve/FieldValues.jl:44
  ...
Stacktrace:
 [1] _zeros_eltypes at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:199 [inlined]
 [2] _noshapecheck_map(::typeof(dual), ::SparseVector{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},ScalarShape},Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:155
 [3] copy(::Base.Broadcast.Broadcasted{SparseArrays.HigherOrderFns.SparseVecStyle,Tuple{Base.OneTo{Int64}},typeof(dual),Tuple{SparseVector{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},ScalarShape},Int64}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:165
 [4] materialize(::Base.Broadcast.Broadcasted{SparseArrays.HigherOrderFns.SparseVecStyle,Nothing,typeof(dual),Tuple{SparseVector{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},ScalarShape},Int64}}}) at ./broadcast.jl:756
 [5] top-level scope at none:0
```

**Comment by odow** [comment]
Previous discussions: https://github.com/JuliaOpt/JuMP.jl/issues/1448, https://github.com/JuliaOpt/JuMP.jl/pull/1702, https://github.com/JuliaOpt/JuMP.jl/issues/1151

Problem is that we don't define `zero` for most JuMP types, so that when you broadcast over a sparse matrix, it attempts to call `f(zero(T))` and crashes.

The best thing is to probably define `zero` and throw a more helpful error.

**Comment by mlubin** [comment]
We explicitly implemented SparseAxisArray to address this: https://github.com/JuliaOpt/JuMP.jl/blob/f526373863cebe89a5a9f95a496ea8192378c9ae/src/Containers/SparseAxisArray.jl#L6-L17

> The best thing is to probably define `zero` and throw a more helpful error.

Not knowing where the function is called from, what better error can we provide than the method isn't implemented? Isn't that what `MethodError` means? It's base Julia that's violating the [MethodError principle](http://www.juliaopt.org/JuMP.jl/v0.19.0/style/#User-facing-MethodError-1) in this case. Not sure what we can do about it.

**Comment by mlubin** [comment]
More explicitly, `SparseVector` and `SparseMatrixCSC` should politely inform the user that it's wrong to construct a sparse matrix if the element type does not define `zero()`. This is a Julia usability bug.

**Comment by ndinsmore** [comment]
I think that there are plenty of valid use cases that would call for defining ```zero``` for constraints at least.  

For example, the use case that I ran into this on was in very large network flow problems, I was storing the edge capacity constraints in the sparse matrix.  Which is a great extension because so many other aspects of graphs can be sparse matrices.  

In another use case that includes column generation for thousands of variables, a sparse vector is perfect for containing constraints on those.   

So long as it is considered valid to store Variables in a sparse array, so should it be to store a constraint that may be put on that variable.

**Comment by odow** [comment]
> I think that there are plenty of valid use cases that would call for defining `zero` for constraints at least.

What should the return value be?

> So long as it is considered valid to store Variables in a sparse array, so should it be to store a constraint that may be put on that variable.

It isn't. Your `value.(spv_var)` example only works because JuMP defines  `zero(VariableRef) = AffExpr(0.0)`. However, `start_value.(spv_var)` doesn't work.

**Comment by ndinsmore** [comment]
> However, `start_value.(spv_var)` doesn't work.

That is appears to be because:
```no method matching start_value(::GenericAffExpr{Float64,VariableRef})```
But couldn't you argue that it is a property that is clearly defined as the value of the expression based on the starting values of the variables.  Thus ```start_value(AffExpr(0.0)) == 0```.

That brings up another interesting question.  Should ```start_value``` return ```Nothing``` of ```Missing``` for variables without that property?   It seems that ```Missing``` is a more correct definition, in that the first thing that nearly every solver will do is go at try "find" that missing value.  Not act like there is no value that could represent the start_value.
That would also make the ```start_value(::GenericAffExpr{Float64,VariableRef})``` have a much more correct definition.

> > I think that there are plenty of valid use cases that would call for defining `zero` for constraints at least.
>
>What should the return value be?

For a constraint ```zero(T)``` should either be```0 >=0``` or maybe ``` 0 == 0```  with the choice depending on the primary way that a given solver represents constraints.
With that definition, it becomes clear ```dual(zero(Constraint)) = 0``` .

**Comment by blegat** [comment]
We could make sense of `start_value` for an affine expression but that's not the case for all functions defined on variables. What about `LowerBoundRef` for instance ? Or `index` ?

**Comment by mlubin** [comment]
> For a constraint `zero(T)` should either be`0 >=0` or maybe ` 0 == 0` with the choice depending on the primary way that a given solver represents constraints.
With that definition, it becomes clear `dual(zero(Constraint)) = 0` .

`ConstraintRef` is not a constraint, it's a reference to a constraint that exists in the model. Are you saying that we should create a new `0 = 0` constraint and add it to the model to implement `zero(ConstraintRef)`?

> That brings up another interesting question. Should `start_value` return `Nothing` of `Missing` for variables without that property? It seems that `Missing` is a more correct definition, in that the first thing that nearly every solver will do is go at try "find" that missing value. Not act like there is no value that could represent the start_value, which is more in line with what I would think of as the definition of `Nothing`.

The decision to use `Nothing` instead of `Missing` wasn't made because of what they conjure up when one things of the words "nothing" and "missing" but by their behavior. `Missing` propagates silently, while `Nothing` does not:
```julia
julia> 1 * missing
missing

julia> 1 * nothing
ERROR: MethodError: no method matching *(::Int64, ::Nothing)
```
We chose the safer route so that users are notified immediately if they mistakenly assume that a value is present. The alternative is extra debugging to find out where the `missing` was introduced.

**Comment by mlubin** [comment]
It seems like there's nothing actionable for JuMP in this issue. Closing. Feel free to revive the discussion in the future if there are new ideas on how to address this issue.
