### ISSUE TITLE
Does JuMP support max and min operator in the constraint

### ISSUE THREAD

**Issue by zhangxz1123** [jump-dev/JuMP.jl#1889]
Say I have a problem like this:
`min f(x,y,z)
s.t. c = max(x,y,z)
`
In general, f is nonlinear, so I can't reduce the max function to a equivalent set of linear constraints. How can I solve it using JuMP?

**Comment by odow** [comment]
This sort of modelling questions is more appropriate for our [Discourse forum](https://discourse.julialang.org/c/domain/opt). We try to reserve the Github issues for bugs and feature requests.

Note that you can use `min` and `max` via JuMP's [nonlinear interface](http://www.juliaopt.org/JuMP.jl/v0.19/nlp/).

```julia
using JuMP, Ipopt
model = Model(with_optimizer(Ipopt.Optimizer))
@variable(model, x >= 0)
@variable(model, y >= 1)
@NLobjective(model, Min, max(x, y))
optimize!(model)
```

**Comment by zhangxz1123** [comment]
When I run
```model = Model(solver=IpoptSolver(print_level=0))
@variable(model, x >= 0)
@variable(model, y >= 1)
@NLobjective(model, Min, max(x, y))
solve(model)```
I get the error message `Unsupported operation max`. It doesn't seem to work? My Julia version is 1.0.3.

**Comment by odow** [comment]
Hmm, I retract my statement about it working (I didn't actually test). The problem is that the gradient of `max` isn't supported by JuMP's differentiation library. This is a usability bug: the error message should be more helpful.

In the mean-time, you have two options: use [AmplNLWriter.jl](https://github.com/JuliaOpt/AmplNLWriter.jl), or use automatic differentiation to evaluate the gradient.
```julia
model = Model(with_optimizer(Ipopt.Optimizer))
@variable(model, x >= 0)
@variable(model, y>=1)
f(x, y) = max(x, y)
JuMP.register(model, :f, 2, f, autodiff=true)
@NLobjective(model, Min, f(x, y))
optimize!(model)
```

**Comment by zhangxz1123** [comment]
I see. Thanks

**Comment by guillermoCabrera** [comment]
Hi guys,

Just to make this question a bit more general, does the max function works for arrays? In particular, can I pass on an Array of NLExpressions to the max operator?

Thanks!

**Comment by odow** [comment]
@guillermoCabrera you can use the splatting operator (see http://www.juliaopt.org/JuMP.jl/v0.19.1/nlp/#Syntax-notes-1), but you have to tell JuMP the number of arguments that you are expecting in `JuMP.register`.

```Julia
N = 2
model = Model(with_optimizer(Ipopt.Optimizer))
@variable(model, x >= 0)
@NLexpression(model, y[i=1:N], sin(x)^i)
f(args...) = max(args...)
JuMP.register(model, :f, N, f, autodiff=true)
@NLobjective(model, Min, f(y...))
optimize!(model)
```

**Comment by guillermoCabrera** [comment]
Thanks Oscar! @odow

**Comment by odow** [comment]
No worries Guillermo, feel free to ask any other questions on https://discourse.julialang.org/c/domain/opt.
