### ISSUE TITLE
Cannot retrieve vector created with string name

### ISSUE THREAD

**Issue by tomerarnon** [jump-dev/JuMP.jl#1895]
Retrieving vectors with symbolic names has the expected behavior:
```julia
julia> @variable(m, z[1:3]);
```
```julia
julia> m[:z]
3-element Array{VariableRef,1}:
 z[1]
 z[2]
 z[3]
```

On the other hand, using strings for the name yields a different, and less practical behavior:
```julia
julia> @variable(m, [1:3], base_name = "z");

julia> variable_by_name(m, "z")

julia> variable_by_name(m, "z[1]")
z[1]
```

As far as I can tell, there is no way to retrieve the entire vector all at once in the second case, which is an extremely useful behavior. I am not sure what is happening behind the scenes to make all of this happen, but I am interested in programmatically creating names in such a way that makes the first method impossible, and the second method impractical.

E.g., something I would like to be able to do is:
```julia
for (i, n) in enumerate(N)
    @variable(model, [1:n], base_name = "z$i")
end
```
And then retrieve the `z1, z2, ...` vectors elsewhere

I have looked at triangular dispatch to try and deal with this, and on the surface it almost works, e.g.:
```julia
julia> @variable(model, z[i = 1:n, j = N[i]])
  [1, 2]  =  z[1,2]
  [3, 1]  =  z[3,1]
  [2, 2]  =  z[2,2]
  [1, 1]  =  z[1,1]
  [2, 1]  =  z[2,1]
```
But without the proper retrieval syntax, this can't be put back in the form that I need it:
```julia
julia> m[:z][1, :]
ERROR: ArgumentError: Indexing with `:` is not supported by Containers.SparseAxisArray
```

**Comment by odow** [comment]
You are free to go
```julia
m = Model()
m[:z] = @variable(m, [1:3])
m[:z]
```

You should look at the functionality JuMP gives you as helpers; you can store variables in your own datastructures if the in-build functionality doesn't meet your needs.

**Comment by tomerarnon** [comment]
Thanks very much for the reply @odow! You're absolutely right, and I totally missed that (and I thought I was thorough in reading the docs...)

```julia
julia> m[:vars] = [@variable(m, [1:i]) for i in rand(1:5, 3)];

julia> m[:vars]
3-element Array{Array{VariableRef,1},1}:
 [noname, noname]                        
 [noname, noname, noname]                
 [noname, noname, noname, noname, noname]

```

**Comment by odow** [comment]
A note should be added to the docs clarifying this: http://www.juliaopt.org/JuMP.jl/latest/variables/#Variable-names-1
