### ISSUE TITLE
provide function which composes names

### ISSUE THREAD

**Issue by ndinsmore** [jump-dev/JuMP.jl#1936]
There should be a user facing function which can be used to compose names which match those created by JuMP in a consistent manner.   Then the best practice should likely be that JuMP then uses the same function to generate names.

Ideally, this would also allow the composition of nested indices, ie. "var[1][4], even though JuMP won't generate these on it's own.

A hacked together version I use today looks like:
```julia
_name_f_tuple_string(t::Tuple{T}) where T<:Integer =  string('[',t[1],']')
_name_f_tuple_string(t::Tuple{T,T}) where T<:Integer  = string('[',t[1],',',t[2],']')

_name_f(s,t::Tuple)=string(s,_name_f_tuple_string(t))
_name_f(s,t::Tuple,r::Tuple)=_name_f(_name_f(s,t),r)
```
That works for my simple use case but I proper solution should likely be more flexable.

**Comment by odow** [comment]
Hi @ndinsmore, it's taken a while to get to this issue! 

Do you have an example of a use-case for this?

The code is here: 
https://github.com/jump-dev/JuMP.jl/blob/f4af44deef5b73788dfbe66de7c280fa8fe55a02/src/macros.jl#L1577-L1593

But you could probably just write your function as:
```julia
julia> name(t::Tuple) = string('[', join(t, ','), ']')
name (generic function with 1 method)

julia> name((1, :a, "c"))
"[1,a,c]"
```
Given the simplicity, I don't see the need to expose this from JuMP. It's also not obvious when or why this would be used outside of JuMP.

**Comment by odow** [comment]
Given the age of this issue and the lack of supporting comments, I'm going to close it. 

@ndinsmore, if you (or anyone else reading this) still wants this and the work-around above isn't sufficient, please leave a comment and we will re-open for further discussion.
