### ISSUE TITLE
Make ReferenceMap support indexing with containers? 

### ISSUE THREAD

**Issue by dourouc05** [jump-dev/JuMP.jl#2019]
I am toying with models and their copies: more precisely, I have a model with a series of variables (say, `a[i]` and `b[i, j]`), which I copy; then, I add constraints to this copy (but not variables), and reoptimise. (Actually, I do so for several constraint sets.) I am using the function `copy_model` to make the copy (and to retrieve a map of indices between the old and the new models). 

This brings me to my use case: I have a function that generates the constraint set (in order to avoid code duplication), to which I pass containers of variables (i.e. `a` and `b`). However, the old references no more work in the copied model. It would be very helpful to have an easy way of converting a bunch of references, not just one by one: I wish I could write something like `ref_map[a]`, but `getindex` does not have the right overload. 

(For the record, I also tried `ref_map.[a]`, and expectedly it did not work: `invalid syntax "ref_map.[a]"`.)

I am unsure about the syntax `ref_map[a]`, because it would not really be about indexing, so it does not feel right -- it's just very convenient. Nevertheless, an implementation could be quite easy: 

```julia
function Base.getindex(reference_map::ReferenceMap, container::Union{DenseAxisArray, SparseAxisArray})
    return getindex.(reference_map, container)
end
```

**Comment by blegat** [comment]
Does `getindex.(ref_map, a)` work ?

**Comment by dourouc05** [comment]
Indeed, it does the work (albeit not really pretty or intuitive). I updated my code in the first message to rather use this syntax (much better than using the containers' internals).
