### ISSUE TITLE
Export of Private Macros

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/JuMP.jl#2023]
Should [this line](https://github.com/JuliaOpt/JuMP.jl/blob/de34e8ac73a76012c28e2714a65a01986d59aad0/src/JuMP.jl#L767),
```
    if sym in _EXCLUDE_SYMBOLS || startswith(sym_string, "_") ...
```
include ` || startswith(sym_string, "@_")` so that a package can have internal non-exported macros?

**Comment by mlubin** [comment]
Yes, looks like an oversight. We've already been naming internal macros with underscores:
https://github.com/JuliaOpt/JuMP.jl/blob/79a4fe4d4fc11bc96b62a88b085734429a833dd2/src/macros.jl#L987-L994

**Comment by odow** [comment]
I guess this is a breaking change, but it shouldn't hit anyone because they shouldn't be using the macros beginning with an underscore.

Task:
- [ ] Add what `@ccoffrin` says
