### ISSUE TITLE
Old error message on ambiguous variable name. Keyword "category" no longer exists

### ISSUE THREAD

**Issue by bhalonen** [jump-dev/JuMP.jl#2035]
This little bit of code 
```
using JuMP
model = Model()
indicator = @variable(model, Bin)
```
throws the error:
```
ERROR: LoadError: In `@variable(model, Bin)`: Ambiguous variable name Bin detected. Use the "category" keyword argument to specify a category for an anonymous variable.
```
Searching the word 'category' on the documentation yields no useful hits. Something should probably be added to the anonymous variable section.

**Comment by mlubin** [comment]
Thanks for reporting. The `category` keyword no longer exists, so this error message needs to be updated. I believe the new recommendation for an anonymous binary variable would be:
```julia
using JuMP
model = Model()
indicator = @variable(model)
set_binary(indicator)
```

**Comment by bhalonen** [comment]
ah. I actually gave up trying to track it down.
```
indicator = @variable(model, binary=true)
```
works as well.
