### ISSUE TITLE
"reregister" a function?

### ISSUE THREAD

**Issue by tamasgal** [jump-dev/JuMP.jl#2058]
Consider the following situation (with a non-sense MWE):

```julia
function optimisation_procedure(reoptimize::Bool)
    f = FMinimiser(2)
    
    model = Model(with_optimizer(Ipopt.Optimizer, print_level=0))
    register(model, :f, 1, f, autodiff=true)
    @variable(model, x)
    @NLobjective(model, Min, f(x))
    optimize!(model)
    
    if reoptimize
        # this could also be a while block
        f = FMinimiser(10)
        register(model, :f_new, 1, f2, autodiff=true)
        @NLobjective(model, Min, f(x))
        optimize!(model)
    end
    
    value(x)
end
```
I need to change the function to be optimised on the fly sometimes to reoptimise again. In these cases, the `register()` and the `@NLobjective` need to be reset, former with a new symbol identifier (`:f_new`). This works, but I'd like to have possibly multiple iterations and generating a new symbol every time seems awkward.

I assume there is a better way of changing the function on the fly?

**Comment by odow** [comment]
x-ref: https://discourse.julialang.org/t/weird-scoping-issue-misunderstanding-in-jump-jl/28604
x-ref: https://github.com/JuliaLang/julia/issues/15602

Here's a better MWE:
```Julia
using JuMP, Ipopt

begin
    model = Model(with_optimizer(Ipopt.Optimizer, print_level = 0))
    @variable(model, x >= 0)
    f(x) = (x - 2)^2
    JuMP.register(model, :foo, 1, f, autodiff=true)
    @NLobjective(model, Min, foo(x))
    optimize!(model)
    # This one works
    @show value(x), isapprox(value(x), 2, atol=1e-5)

    f(x) = (x + 10)^2
    optimize!(model)
    @show value(x), isapprox(value(x), 0, atol=1e-5)
end

function doesnt_work_because_julia_15602()
    model = Model(with_optimizer(Ipopt.Optimizer, print_level = 0))
    @variable(model, x >= 0)
    f(x) = (x - 2)^2
    JuMP.register(model, :foo, 1, f, autodiff=true)
    @NLobjective(model, Min, foo(x))
    optimize!(model)
    # This one fails!?!
    @show value(x), isapprox(value(x), 2, atol=1e-5)

    f(x) = (x + 10)^2
    optimize!(model)
    @show value(x), isapprox(value(x), 0, atol=1e-5)
    return
end
doesnt_work_because_julia_15602()
```
Yields
```Julia
Non-function scope
(value(x), isapprox(value(x), 2, atol=1.0e-5)) = (2.00000000062657, true)
(value(x), isapprox(value(x), 0, atol=1.0e-5)) = (0.0, true)

Function scope
(value(x), isapprox(value(x), 2, atol=1.0e-5)) = (0.0, false)
(value(x), isapprox(value(x), 0, atol=1.0e-5)) = (0.0, true)
```

This is fundamentally a Julia bug.

**Comment by tamasgal** [comment]
Thanks for wrapping and and xlinking.

Any ideas how to do such things inside a function then? Should I try to implement a `reregister` function or maybe a keyword to `register` to allow overwriting a function with the same symbol name?

The only workaround I found was to execute both `@NLobjective` and `register` but I need a new symbol every time... also not sure about the actual performance overhead, since my optimisations are usually very quick.

**Comment by odow** [comment]
You could use `gensym()` to get a new symbol. 

A better solution would be to rebuild the model every time unless you have benchmarks showing that this is prohibitively expensive.

```Julia
function rebuilder(f)
    model = Model(with_optimizer(Ipopt.Optimizer, print_level = 0))
    @variable(model, x >= 0)
    JuMP.register(model, :foo, 1, f, autodiff=true)
    @NLobjective(model, Min, foo(x))
    optimize!(model)
    return value(x)
end
rebuilder(x -> (x - 2)^2)
rebuilder(x -> (x + 10)^2)
```

**Comment by tamasgal** [comment]
Thanks, `gensym()` is perfect! Rebuilding is unfortunately too much overhead...

**Comment by tamasgal** [comment]
Ahm, wait. How do I use the symbol in `NLobjective` then? I just tried my MWE using functors, which is quite close to my code structure:

```julia
using JuMP
using Ipopt


struct FMinimiser <: Function
    a
end


function(f::FMinimiser)(x)
    (x + f.a)^2
end


function optimisation_procedure(reoptimize::Bool)
    f = FMinimiser(2)
    
    model = Model(with_optimizer(Ipopt.Optimizer, print_level=0))
    register(model, :f, 1, f, autodiff=true)
    @variable(model, x)
    @NLobjective(model, Min, f(x))
    optimize!(model)
    
    if reoptimize
        f = FMinimiser(10)
        s = gensym()
        register(model, s, 1, f, autodiff=true)
        @NLobjective(model, Min, f(x))  # <----- here I should use the symbol s
        optimize!(model)
    end
    
    value(x)
end
```

This of course gives the same result for both of these calls:

```
> optimisation_procedure(false)
-2.0
> optimisation_procedure(true)
-2.0
```

**Comment by odow** [comment]
You will need to use the raw expression input: https://www.juliaopt.org/JuMP.jl/v0.20.0/nlp/#Raw-expression-input-1

**Comment by tamasgal** [comment]
Sorry, I am trying all kinds of combinations but this expression thing is killing my nerve. I am sitting on this issue for almost 6 hours now 🙈 

```julia
set_NL_objective(model, :Min, :(s($(x))))
```

I thought it should work like this but I get

```
MethodError: no method matching set_NL_objective(::Model, ::Symbol, ::Expr)
```

I thought this would work since it's quite similar to this (https://discourse.julialang.org/t/how-to-add-user-defined-nonlinear-functions-as-constraints-with-jump/11436/3?u=tamasgal) but I am sure the symbol `s` needs to be "unwrapped".

**Comment by odow** [comment]
Looks like the docs need updating. You need to use `MOI.MIN_SENSE` instead of `:Min`. Here's the function:
https://github.com/JuliaOpt/JuMP.jl/blob/3caea82df6d73744f9b060c04a81c77058f8011c/src/nlp.jl#L1190-L1194

**Comment by tamasgal** [comment]
Oh ok nice catch. Thanks again ;)

For the sake of completeness, this is the right syntax for a function call:

```julia
set_NL_objective(model, MOI.MIN_SENSE, :($s($(x))))
```

which is equivalent to 

```julia
@NLobjective(model, Min, s(x))
```

**Comment by odow** [comment]
Since this is really just a Julia thing:
```julia
julia> function foo()
           bar(x) = 2x
           @show bar(2)
           bar(x) = 4x
           @show bar(2)
       end
foo (generic function with 1 method)

julia> foo()
bar(2) = 8
bar(2) = 8
```
I think the only actionable item is to add a warning to the documentation that functions cannot be re-registered.
