### ISSUE TITLE
Ease addition of matrix cones

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#2093]
The `PSDCone` allows to easily add `MOI.PositiveSemidefiniteConeTriangle` and `MOI.PositiveSemidefiniteConeSquare`.
There are several other matrix cones, that should work exactly like `PSDCone` for consistency:
* `SemidefiniteInterval`, `SemidefiniteGreaterThan` and `SemidefiniteLessThan` that create `MOI....Triangle` and `MOI....Square`, see https://github.com/JuliaOpt/MathOptInterface.jl/issues/942
* `EigenvalueInterval`, `EigenvalueGreaterThan` and `EigenvalueLessThan` that create `MOI....Triangle` and `MOI....Square`, see https://github.com/JuliaOpt/MathOptInterface.jl/issues/942
* `SumOfSquares.DDCone` that create `SumOfSquares.DiagonalyDominantConeTriangle` and `SumOfSquares.DiagonalyDominantConeSquare`
* `SumOfSquares.SDDCone` that create `SumOfSquares.ScaledDiagonalyDominantConeTriangle` and `SumOfSquares.ScaledDiagonalyDominantConeSquare`

To allow reusing the code for `PSDCone` between these different sets we can create a `AbstractSymmetricMatrixCone` set and the function `triangle_vectorized_cone` and `square_vectorized_cone` and then all the code should work for any `AbstractSymmetricMatrixCone`.

Requires https://github.com/JuliaOpt/MathOptInterface.jl/issues/942

**Comment by odow** [comment]
@blegat: We haven't made any progress on this. I see what we closed #942, so I'm not sure what `Requires #942` is for. Can this be closed? We seem to be getting on okay without it.

**Comment by blegat** [comment]
I'll take a look whilr adding affine hermitian constraints. It would still be helpful

**Comment by odow** [comment]
Bump. Is there anything to do here?

**Comment by blegat** [comment]
Yes, I still need to get at it

**Comment by odow** [comment]
Can you point me in the right direction? I still don't really understand what you're after.

**Comment by blegat** [comment]
I'm going to take a look

**Comment by odow** [comment]
Can you be a little more explicit in what you want here? For example, links to the bits in other packages that would be de-duplicated?

**Comment by blegat** [comment]
These are the cones: https://github.com/jump-dev/SumOfSquares.jl/blob/8476c96d0fc182377a3a585222714061925092ab/src/diagonally_dominant.jl
I haved made it possible to use them from JuMP as it would be duplicating the code

**Comment by odow** [comment]
So you want a fallback for any `MOI.AbstractSymmetricMatrixSetTriangle`?

**Comment by blegat** [comment]
Yes
