### ISSUE TITLE
Print constraints/variables in set form instead of scalarized

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2171]
Currently, we get
```Julia
model = Model()
@variable(model, x[1:2] >= 0)
@constraint(model, c[i = 1:2], x[i] + i >= 0)
print(model)
# gives
Feasibility
Subject to
 c[1] : x[1] ≥ -1.0
 c[2] : x[2] ≥ -2.0
 x[1] ≥ 0.0
 x[2] ≥ 0.0
```
@claytonpbarrows suggests that we simplify this printing to
```
Feasibility
Subject to
 c[i=1:2] : x[i] + i ≥ 0
 x[i=1:2] ≥ 0.0
```
where the expressions are taken directly from the macro form.

This is particularly useful in large models, where the number of unique (parameterized) constraints is small, but each constraint is indexed over a large set.

**Comment by mlubin** [comment]
This requires a ton of finicky infrastructure that we previously removed (see, e.g., https://github.com/JuliaOpt/JuMP.jl/issues/795) and I think it's useful only for a narrow range of models where the code should be reasonably simple to read, so the printing doesn't add much information.

As soon as you have programmatic generation of the model and/or anonymous variables, it becomes a lot more complex to decide how to compress and print the index sets. Should we be remembering and presenting `sum`s as the user entered them? What if the constraints had sub-expressions, should we print the names of the expressions or their contents? Do any other modeling interfaces as flexible as JuMP have similar fancy printing like this?

I'd prefer to not print the model or come up with more concise summaries when the full print-out is too large to be readable: https://github.com/JuliaOpt/JuMP.jl/issues/957.

**Comment by odow** [comment]
I guess the "concise summary" is what we're after. I'm aware of the code complexity issue. 

The motivation is, given a [PowerSimulations.jl](https://github.com/NREL/PowerSimulations.jl) model, print a summary for the user showing what algebraic model they are solving.

**Comment by odow** [comment]
Closing because explicit printing now only happens with `print(model)`. To print a concise summary, use `show(model)`.
```Julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x[1:2] >= 0)
2-element Vector{VariableRef}:
 x[1]
 x[2]

julia> @constraint(model, c[i = 1:2], x[i] + i >= 0)
2-element Vector{ConstraintRef{Model, MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}, ScalarShape}}:
 c[1] : x[1] ≥ -1.0
 c[2] : x[2] ≥ -2.0

julia> print(model)
Feasibility
Subject to
 c[1] : x[1] ≥ -1.0
 c[2] : x[2] ≥ -2.0
 x[1] ≥ 0.0
 x[2] ≥ 0.0

julia> show(model)
A JuMP Model
Feasibility problem with:
Variables: 2
`AffExpr`-in-`MathOptInterface.GreaterThan{Float64}`: 2 constraints
`VariableRef`-in-`MathOptInterface.GreaterThan{Float64}`: 2 constraints
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.
Names registered in the model: c, x
```
