### ISSUE TITLE
Feature Request: Report table for query solutions

### ISSUE THREAD

**Issue by yordiak** [jump-dev/JuMP.jl#2191]
The last few weeks I have to switched to JuMP in order to perform my (optimization) analysis. Having a look at the documentation related to "Query Solutions" I found that you can extract very useful information regarding the optimizations results.

Thus, I was thinking that it would be a nice all of this information to be presented in a table. I understand that not everything is useful for everyone, and querying solutions might be context-specific. However, I believe that there are parts of a solution that are important to (almost) every one. These parts should be included in the report table.

I believe that a `report!()` command can generate such table. Here, arguments will denote the information someone wants to include in the table. For instance,

`report!()` = universal results, like `objective_value` and `value.(x)`
`report!(primal, dual)` = `objective_value` and `value.(x)` and also, `primal_status` and `dual_status'

**Comment by odow** [comment]
This issue is still up for grabs. I think we want a function
```Julia
function solution_summary(model::Model; verbose::Bool = false)
    # ...
end
```
that produces a report like the following:
```
solution_summary(model)

--------------------------------------------------------------------------------
* Solver : MOI.get(model, MOI.Name())

* Status

  termination_status : MOI.OPTIMAL
  primal_status      : MOI.FEASIBLE_POINT
  dual_status        : MOI.NO_SOLUTION
  Message from the solver:
    "... the output of MOI.get(model, MOI.RawTerminationStatus()) ..."

* Candidate solution

  Objective value : xxx
  Objective bound : xxx

* Work counters

  Solve time (sec)   : xxx
  Simplex iterations : xxx
  Barrier iterations : xxx
  Node count         : xxx
--------------------------------------------------------------------------------

solution_summary(model; verbose = true)

--------------------------------------------------------------------------------
* Solver : MOI.get(model, MOI.Name())

* Status

  termination_status : MOI.OPTIMAL
  primal_status      : MOI.FEASIBLE_POINT
  dual_status        : MOI.NO_SOLUTION
  Message from the solver:
    "... the output of MOI.get(model, MOI.RawTerminationStatus()) ..."

* Candidate solution

  Objective value : xxx
  Objective bound : xxx
  Primal solution : 
     x[1] : xxx
     x[2] : xxx
     ...
  Dual solution : 
     c[1] : xxx
     c[2] : xxx
     ...

* Work counters

  Solve time (sec)   : xxx
  Simplex iterations : xxx
  Barrier iterations : xxx
  Node count         : xxx
--------------------------------------------------------------------------------
```
