### ISSUE TITLE
Generalize modification functions

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2256]
The majority of functions in https://github.com/jump-dev/JuMP.jl/blob/master/src/constraints.jl are specialized to `Model`s.

It would be very helpful for extensions (e.g., https://github.com/pulsipher/InfiniteOpt.jl/issues/55) if these were generalized to `AbstractModel`.

Examples:
https://github.com/jump-dev/JuMP.jl/blob/ecf12ab5868ba5af45e38ee721f1f5ea0c43a1b7/src/constraints.jl#L436-L437
https://github.com/jump-dev/JuMP.jl/blob/ecf12ab5868ba5af45e38ee721f1f5ea0c43a1b7/src/constraints.jl#L452-L453
https://github.com/jump-dev/JuMP.jl/blob/ecf12ab5868ba5af45e38ee721f1f5ea0c43a1b7/src/constraints.jl#L479-L480
https://github.com/jump-dev/JuMP.jl/blob/ecf12ab5868ba5af45e38ee721f1f5ea0c43a1b7/src/constraints.jl#L495
https://github.com/jump-dev/JuMP.jl/blob/ecf12ab5868ba5af45e38ee721f1f5ea0c43a1b7/src/constraints.jl#L557

cc @pulsipher

**Comment by joaquimg** [comment]
So this is simply adding a bunch of `where`'s ?

**Comment by blegat** [comment]
Yes, or even just `ConstraintRef{<:AbstractModel}`

**Comment by odow** [comment]
Tasks for the sprint:
- [ ] Relax strict typing of `Model` in the `src/constraints.jl` file and check tests still pass.
