### ISSUE TITLE
Documentation inconsistency: MOI or MathOptInterface? 

### ISSUE THREAD

**Issue by dourouc05** [jump-dev/JuMP.jl#2263]
In https://jump.dev/JuMP.jl/dev/constraints/, sets in MOI are referred to as either `MathOptInterface.*` or as `MOI.*` (in the text, not in the results from Julia REPL): 

* `MathOptInterface.AbstractSet` for `@constraint`
* `MathOptInterface.SecondOrderCone` for SOC
* `MathOptInterface.RotatedSecondOrderCone`
* `MOI.PositiveSemidefiniteConeTriangle` and `MOI.PositiveSemidefiniteConeSquare` for PSD

I guess it would be best to uniformise this (as MathOptInterface, it looks like the most common one?).

**Comment by odow** [comment]
Probably actually `MOI`, since that is the constant exported from JuMP.
