### ISSUE TITLE
Powers print incorrectly in IJulia mode

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#2293]
![image](https://user-images.githubusercontent.com/1733683/88467225-bda5b980-cea2-11ea-9c24-eb97337f5496.png)

The decimal point is getting mangled.

**Comment by odow** [comment]
The issue is here: https://github.com/jump-dev/JuMP.jl/blob/f47b18ce6c8ef10301d31c98559e55c562390815/src/print.jl#L621-L623
Instead of 
```Julia
julia> string(:(x ^ 4.0))
"x ^ 4.0"
```
we need `x ^ {4.0}`.
