### ISSUE TITLE
Docs: explain package incompatibility

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/JuMP.jl#2296]
- [x] teach users to check for the latest version
- [x] talk about the order of adding packages
- [x] explain why some packages are not compatible
- [x] talk about envs

ref: https://github.com/JuliaLang/Pkg.jl/issues/1655 and https://discourse.julialang.org/t/package-versions-how-to-make-it-less-confusing/43714

**Comment by odow** [comment]
Closing as largely resolved by https://github.com/jump-dev/JuMP.jl/pull/2392.

This is really an upstream issue, and there are other issues to track that.
