### ISSUE TITLE
Constraints' start values by using variables' start values

### ISSUE THREAD

**Issue by davide-f** [jump-dev/JuMP.jl#2299]
Function start_value returns the current start value for a variable; however, when a good set of variables is provided, the above can have implications in the values of the constraints and for some applications it would be interesting to evaluate what is the starting value of a constraint and the interval.
For example, in bilevel optimzation, being able to automatically initialize the binary variables in Fortuny-Amat reformulations or SOS constraints simply by passing the primal variables would be very helpful.
To do so, a function equivalent to start_value(::ConstraintRef) returning the slack value would be very helpful.
It is worth noticing that when only a partial solution is provided, a specific numeric value may not be achievable for every constraint, rather an interval.

For example, a constraint like the following (slack variable z), being x, y >= 0
x + y <= 1 -> x + y + z = 1
when both x and y are initialized, i.e. x=y=0
z = 1 - x - y = 1 -> The proposed start_value may return z_low = z_high = 1
When for  only x is initialized
z = 1 - x - y = 1 - x -> The proposed start_value may return z_high = 1, z_low = 0/-Inf (Theoretically, when the constraint is achieved the slack cannot be negative, so 0 could be specified as a return variable, or -Inf)

**Comment by odow** [comment]
There is already an open issue and PR for implementing `ConstraintDualStart`: https://github.com/jump-dev/JuMP.jl/issues/2094

Is this a request for `slack_value(con)`?

You can achieve it with something like the following. Although a proper implementation would account for the correct signs, etc.
```Julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x, start = 1)
x

julia> @variable(model, y)
y

julia> @constraint(model, c, 2.5 * x + y <= 3)
c : 2.5 x + y ≤ 3.0

julia> o = constraint_object(c)
ScalarConstraint{GenericAffExpr{Float64,VariableRef},MathOptInterface.LessThan{Float64}}(2.5 x + y, MathOptInterface.LessThan{Float64}(3.0))

julia> function slack_value(c, f = start_value)
           o = constraint_object(c)
           lhs = value(o.func, x -> f(x) === nothing ? 0.0 : f(x))
           rhs = MOI.constant(o.set)
           return rhs - lhs
       end
            
slack_value (generic function with 2 methods)

julia> slack_value(c)
0.5
```

**Comment by davide-f** [comment]
Thank you for your comment, which partially answer my question.
#2094 seems related to being able to set the initial dual start explicitly, if I understood properly. Here I am suggesting to being able to evaluate the extreme values of the slack value of each constraint.
 The code should work in the case all primal variables are implemented; however when the above does not occur when a variable is not set.
However, the proposed function does not take into account the non-initialized variables, such as the "y" of your example. I think it could be useful a function able to return the minimum and maximum values of the slack variable.

I believe this could be helpful for many packages including BilevelJuMP, which I am using for a problem and I need to be able to evaluate the slack values for the initialization of the binary/SOS constraints.
I cite @joaquimg who might be interested and give his opinion on this point.

**Comment by mlubin** [comment]
@davide-f Is it clear how to extend @odow's example to include extra logic when some variables are not initialized?
The interval logic you're proposing is application specific and not a general or standard feature supported by solvers. I'm not seeing why this particular function needs to be built into JuMP when JuMP already provides the APIs that let you access the constraints and perform transformations on them as you like.

**Comment by davide-f** [comment]
To be honest, I only see the complex way in which given a GenericAffExpr I may iteratively check every terms to check whether they have a start value, if not I should check the bounds.
Isn't there an easier way to proceed?

**Comment by mlubin** [comment]
> I only see the complex way in which given a GenericAffExpr I may iteratively check every terms to check whether they have a start value, if not I should check the bounds.

I'm not sure I understand why this is perceived to be complex compared with any other transformations one might do to implement bilevel optimization. Any implementation of the interval computation you proposed has to check every term in a GenericAffExpr and perform some logic on each term depending on whether there's a start value set. This is a `for` loop with an `if` condition inside the loop.

**Comment by davide-f** [comment]
Thank you for your help, I thought there were an easier way, but I have developed the function to estimate the bounds of a constraint.
If someone is interested, please text me.
I think we can close this comment.
