### ISSUE TITLE
Support for restoring constraints after unfix rather than deleting them

### ISSUE THREAD

**Issue by davide-f** [jump-dev/JuMP.jl#2304]
What is the easiest way to restore the bounds on variables after an unfix?
Having an option to delete or restore them after the unfix could be interesting and may save some coding

**Comment by odow** [comment]
If it only has a fixed value, you could do something like:
```Julia
function my_unfix(x)
    v = fixed_value(x)
    unfix(x)
    return () -> fix(x, v)
end

model = Model()
@variable(model, x == 1)
refix = my_unfix(x)
refix()
```
It shouldn't be too hard to modify this for lower and/or upper bounds.

**Comment by davide-f** [comment]
Thank you very much for your help, I definitely understand how to generalize it.
I have already developed the function.
