### ISSUE TITLE
Default variable name by the symbol

### ISSUE THREAD

**Issue by davide-f** [jump-dev/JuMP.jl#2305]
In my application I am experiencing problems in having the solver finding a feasible starting point.
When I pass the feasible partial starting point with set_start_value, the solver cannot find a feasible solution.
However, when I fix the variables is able to find the solution.
Therefore, my goal was to:
1) develop my model including bounds
2) initialize and fix the partial feasibile starting point
3) optimize the fixed model
4) retrive the complete solution
5) unfix the original model and pass the full starting values of the model
6) optimize the model again

However, when fix/unfix are used, the numbering of the equations may change due to the packages I am using, therefore it is very difficult to link the variables between points 4 and 5. It would be very helpful to be able to retrive the variables by name, but that is not easy to handle.
All the above might be easier to do if:
1) unfix could have an option to restore the bounds before the fix operation (#2304)
2) the default name of variables is the symbol used for them

Could you provide me some hint to advance?
Thank you very much

**Comment by odow** [comment]
>  It would be very helpful to be able to retrive the variables by name, but that is not easy to handle.

https://jump.dev/JuMP.jl/v0.21.1/variables/#JuMP.variable_by_name

These types of usage questions should be first asked on Discourse: https://discourse.julialang.org/c/domain/opt/13. We try to keep the Github issues for bug reports and features requests (e.g., #2304). Asking on Discourse has a few benefits: more people read it so others might have some suggestions, people can search for old questions which helps people in the future, and we can workshop the question first before opening a Github issue.

In particular, it's hard to offer more advice for this issue without seeing what code you have written. So I suggest you create a minimal working example of what you are trying to do, post on Discourse, and we can go from there.

**Comment by mlubin** [comment]
> All the above might be easier to do if:
> the default name of variables is the symbol used for them

I don't understand the request. This is already the case.

```julia
julia> m = Model();

julia> @variable(m, x >= 0)
x

julia> name(x)
"x"

julia> variable_by_name(m, "x")
x
```

**Comment by davide-f** [comment]
Sorry, I got confused by the option name="" in the functions, I'll use the forum first next times.
Thank you.
