### ISSUE TITLE
nonlinear complementary constraints

### ISSUE THREAD

**Issue by Jovansam** [jump-dev/JuMP.jl#2308]
Thanks for great work. JuMP is a great and I love it. Support for complementary constraints is limited only linear constraints, however. While I can "manually" introduce nonlinear complementary constraints, it would be nice to have this feature added to the package ecosystem. [See this discussion](https://discourse.julialang.org/t/julia-jump-optimization-help/43259/2).

**Comment by odow** [comment]
Unfortunately there are fundamental reasons why this can't happen anytime in the near- to medium-term. It requires a complete re-write of JuMP's NLP support.

**Comment by odow** [comment]
I'm going to close this as out-of-scope. Users should use https://github.com/chkwon/Complementarity.jl until the nonlinear API is rewritten.
