### ISSUE TITLE
Sparse array addition with diagonal is dense

### ISSUE THREAD

**Issue by angeris** [jump-dev/JuMP.jl#2309]
Heya JuMP team!

Here's a (hopefully simple) one—I think I could even try and PR it, but I haven't looked at the JuMP codebase in quite a while, so it might take me longer than it probably will for almost anyone :) .

Anyways, it seems that currently adding a sparse matrix with a `Diagonal` `VariableRef` defaults, for some reason, to elementwise addition over all entries. More specifically, here's a basic example:
```julia
m = Model()
@variable(m, a[1:10])

sparse(I(10)) + Diagonal(a)
```
gives a matrix with 100 nonzero entries, where all off-diagonal elements are simply 0.0 (even though, as one would expect, it should only give 10 nonzero entries along the diagonal). Additionally, trying the next obvious thing (we'll call this the "main" example)
```julia
sparse(I(10)) + sparse(Diagonal(a))
```
still suffers from the same problem. On the other hand,
```julia
I(10) + Diagonal(a)
```
does correctly keep the `Diagonal` structure (as one would expect, since `@which` shows that we are calling `+(Da::Diagonal, Db::Diagonal)`).

Anyways, the next thought was that `sparse(Diagonal(a))` was simply filling in a bunch of nonzero entries, but it seems that this is incorrect! In fact, `sparse(Diagonal(a))` returns exactly a `SparseMatrixCSC` with only nonzero diagonals. So, my guess is that, because of the abstract sparse fallback in the "main" example, adding a `VariableRef` to a zero-entry in `Float64` is not returning a `zero` of the `VariableRef` element or it is being treated as a concrete `zero` in the abstract fallback. This may be wrong, though, as I have not yet dug deeper into this!

Thank you so much! :)

**Comment by angeris** [comment]
I *think* I found out why this is the case. The abstract fallback for the sparse matrix calls `map(+, A, B)` where `A` and `B` are `AbstractSparseMatrixCSC` types. This call, in turn, calls some other methods, which, at the end call `SparseArrays.HigherOrderFns._iszero` to determine whether the return of summing `zero(eltype(A)) + zero(eltype(A))` is zero.

The problem is that `SparseArrays.HigherOrderFns._iszero(x) = x == 0` whenever `x` is a `GenericAffExpr`, and, for example `0.0*a[1] == 0` (where `a` is as defined above) is not true. One possible fix is to define the `==` operation for `GenericAffExpr` to check if both all coefficients (and the intercept) are zero (or if there are no coefficients in the `Dict`) and return `true` if so.

**Comment by odow** [comment]
There are quite a few bugs like this in the sparse linear algebra package because `typeof(VariableRef) != typeof(zero(VariableRef))`.

> The problem is that `SparseArrays.HigherOrderFns._iszero(x) = x == 0`

That's really annoying.

This seems to do the trick
```julia
Base.:(==)(x::AffExpr, y::Number) = isempty(x.terms) && x.constant == y
```

**Comment by angeris** [comment]
Yup, this is pretty much the solution I have written in my current program, but I'm wondering if it's worth actively including in the JuMP repo? (Or if there is another, more "Julia" way to do it.)

**Comment by odow** [comment]
This should probably be added to the JuMP repo.

We need
```Julia
Base.:(==)(x::GenericAffExpr, y::Number) = isempty(x.terms) && x.constant == y
Base.:(==)(x::GenericQuadExpr, y::Number) = isempty(x.terms) && x.aff == y
```
plus tests and a comment linking to the `_iszero` explaining why it's needed.

**Comment by blegat** [comment]
Could we also do a long term fix similar to https://github.com/JuliaLang/julia/pull/36194?

**Comment by angeris** [comment]
I was wondering the same thing. My only issue is that it might be a breaking change for some packages (with weird behavior) where `iszero(x)` need not imply `x == 0`? Or there is no such `iszero` method?

**Comment by blegat** [comment]
`iszero` falls back to `x == zero(x)` so it should work. What they meant by `_iszero` is in fact `iszero`, it was probably written before `Base.iszero` existed.

**Comment by angeris** [comment]
>  it was probably written before Base.iszero existed.

Yeah, this was what I imagined. I guess I'll just do a PR there, which would save all of us a lot of headaches :)

**Comment by blegat** [comment]
Yes, it would also be helpful for MathOptInterface where we don't want to implement `==` between a `ScalarAffineFunction{Float64}` and an `Int`.

**Comment by odow** [comment]
I think we're going to mark this as won't-fix for JuMP. It should be fixed upstream, but things are a little complicated: https://github.com/JuliaLang/julia/pull/38789
