### ISSUE TITLE
Missing website

### ISSUE THREAD

**Issue by zdroid** [jump-dev/JuMP.jl#2310]
This repository is missing a website link in its description. Reasons to do this are listed in [this Discourse thread](https://discourse.julialang.org/t/a-suggestion-for-package-maintainers/44111).

https://jump.dev/JuMP.jl/stable/, https://jump.dev/JuMP.jl/dev/ or https://jump.dev/ all are suited for this task.

**Comment by blegat** [comment]
I just put https://jump.dev/, not sure which one of the three it should be however

**Comment by zdroid** [comment]
I think that one is the best, and it has a link to documentation anyway.
