### ISSUE TITLE
Docs: Add info on `start` for multiple variables

### ISSUE THREAD

**Issue by dpsanders** [jump-dev/JuMP.jl#2312]
The docstring for `@variables` does not say how to give `start`ing values for multiple variables.
It should either be added to the docstring or a link given to https://jump.dev/JuMP.jl/v0.21.3/variables/#variables-1, where that info is given.

**Comment by odow** [comment]
Do you mean something like:
```Julia
@variables(model, begin
    x, (start = 1)
    y, (start = 2)
end)
```

There is more information on starting values here:
https://jump.dev/JuMP.jl/v0.21.3/variables/#Start-values-1

**Comment by dpsanders** [comment]
Actually I meant the part on `y[i=1:2]` here:
```
@variables(model, begin
           x
           y[i=1:2] >= i, (start = i, base_name = "Y_$i")
           z, Bin
       end)
```

**Comment by odow** [comment]
Can you refine the question? The docstring does show how to set `start` for multiple variables.

Do you want the same value for each variable?
```Julia
@variables(model, begin
    x[i = 1:2], (start = 2 * i)
    y[i = 1:2], (start = 1)
end)

**Comment by dpsanders** [comment]
`?@variables` on JuMP 0.21.3 has no information on using `start` like that with multiple variables.

**Comment by dpsanders** [comment]
If that info is already in the docstring master then this issue can be closed!

**Comment by odow** [comment]
I was incorrect. The docstring didn't have the information. I opened a PR.

**Comment by dpsanders** [comment]
Thanks!

**Comment by alanedelman** [comment]
any reason we can't have vector syntax? e.g. (start = 1:2)

**Comment by mlubin** [comment]
Vector syntax doesn't generalize to all the settings where you can use `@variable`, e.g.,
```julia
source = ["LAX", "JFK", ...]
dest = [...]
@variable(model, flow[i = source, j = dest], start = some_formula(i,j)) # This is fine.
@variable(model, flow[i = source, j = dest], start = 1:2) # What does a vector mean here?
```

If you have a plain vector of variables, you're free to use `JuMP.set_start_value.(var, 1:n)`, which seems fine to me. The fewer special cases in the macros, the better.

**Comment by alanedelman** [comment]
perhaps that could go in the doc
