### ISSUE TITLE
Bug in SDP parsing?

### ISSUE THREAD

**Issue by migarstka** [jump-dev/JuMP.jl#2320]
I might be overlooking something, but shouldn't these two SDP models be feasible and return the same optimal X (objective is slightly differently scaled)? 

**Problem**:
Given a graph G(V,E) with adjacency matrix E and matrix J = ones(n,n)

max tr(J, X)
s.t.  tr(X) == 1
X_ij = 0, if (i, j) in E
X is PSD

**Model 1**:
```julia
using LinearAlgebra, SCS, COSMO, JuMP

# let's define our graph
n = 3
E = zeros(n, n)
E[1, 2] = 1.
E[2, 3] = 1.
E = Symmetric(E)

model = JuMP.Model(with_optimizer(SCS.Optimizer))
@variable(model, X[1:n, 1:n], Symmetric)
@objective(model, Max, sum(X))
@constraint(model, tr(X) == 1.)
Ec = [1 0 1; 0 1 0; 1 0 1]
@constraint(model,  Symmetric(Ec .* X )  in JuMP.PSDCone())
status = JuMP.optimize!(model)
```
The last constraint gets printed like this:
```
[X[1,1]  0       X[1,3];
 0       X[2,2]  0     ; ∈ PSDCone()
 X[1,3]  0       X[3,3]]
```
Yields a dual infeasible model.

**Model 2**:
Here we just work with the vector `x` which are just the nonzero elements of `X` starting with the three diagonal entries.
```julia
model2 = JuMP.Model(with_optimizer(SCS.Optimizer))
@variable(model2, x[1:4]) # x = [ X[1,1]; x[2,2]; x[3, 3]; x[1; 3] ]
@objective(model2, Max, sum(x))
@constraint(model2, sum(x[1:3]) == 1.)

A11 = zeros(3, 3); A11[1, 1] = 1.
A22 = zeros(3, 3); A22[2, 2] = 1.
A33 = zeros(3, 3); A33[3, 3] = 1.
A13 = zeros(3, 3); A13[1, 3] = 1.
@constraint(model2, Symmetric(A11 .* x[1] + A22 .* x[2] + A33 .* x[3] + A13 .* x[4] )  in JuMP.PSDCone());
status2 = JuMP.optimize!(model2)
JuMP.value.(x)
```

The last constraint gets printed like this:
```
[x[1]  0     x[4];
 0     x[2]  0   ; ∈ PSDCone()
 x[4]  0     x[3]]
```

Is a feasible problem. The behaviour seems solver-independent. Looking further down into the solver wrappers, different constraint matrices are passed to the solvers.

**Comment by blegat** [comment]
> different constraint matrices are passed to the solvers

At the MOI level, the only difference is that the first one has 2 additional unused variables. So the difference between the constraint matrices should be 2 zero columns. Is that what you see?

**Comment by odow** [comment]
The first model has `X[1,2]` that doesn't appear in a constraint, but is in the objective? So it's unbounded? These models are not equivalent. Why do you create `E` if you don't use it?

**Comment by migarstka** [comment]
Thank you for the answers.

> The first model has X[1,2] that doesn't appear in a constraint, but is in the objective? So it's unbounded?

Indeed, my bad. If I create the objective like this, i.e. taking the zero elements of X out of the objective:
```
@objective(model, Max, sum(Ec .* X))
```
it works in COSMO. With SCS it complains about the empty columns in `A`. So it seems that this can be fixed by adding:
```
@constraint(model,  X[1, 2] == 0)
@constraint(model,  X[2, 3] == 0)
```

> Why do you create E if you don't use it?

This was just for illustrative purposes.
