### ISSUE TITLE
[Feature Request] Error Function Keyword Argument for Macros

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#2333]
**Is your feature request related to a problem? Please describe.**
Currently, extensions that employ their own macros that in turn wrap JuMP macros get error messages that are not meaningful as exemplified below:
```julia
using JuMP

macro my_new_variable(model, args...)
   # Define macro error function that is relevant to this macro
   _my_error_func(str...) = JuMP._macro_error(:my_new_variable, (model, args...), __source__, str...)

   # Do desired extension manipulations before calling JuMP.@variable (calling _my_error_func where needed)
   new_args = args # do nothing in this example for simplicity

   # Prepare and return the code wrapping JuMP.@variable 
   code = :( JuMP.@variable($model, $(new_args...)) )
   return esc(code)
end 

# Make a call that invokes an error 
model = Model()
@my_new_variable(model, [1:2] >= 0) 
```
```julia
ERROR: LoadError: At REPL[9]:9: `@variable(model, [1:2] >= 0)`: Cannot use explicit bounds via >=, <= with an anonymous variable
Stacktrace:
 [1] error(::String, ::String) at .\error.jl:42
 [2] _macro_error(::Symbol, ::Tuple{Symbol,Expr}, ::LineNumberNode, ::String) at my_pathr\.julia\packages\JuMP\e0Uc2\src\macros.jl:924
 [3] (::getfield(JuMP, Symbol("#_error#88")){LineNumberNode,Tuple{Symbol,Expr}})(::String) at my_path\.julia\packages\JuMP\e0Uc2\src\macros.jl:1198
 [4] @variable(::LineNumberNode, ::Module, ::Vararg{Any,N} where N) at my_path\.julia\packages\JuMP\e0Uc2\src\macros.jl:1253
in expression starting at REPL[9]:9
```
Notice that the the given error message doesn't refer to the macro that the user actually called and the sourcing info is not 
where the user called it (it refers to where the extension macro calls `@variable`). It would be nice to pass on `_my_error_func` to @variable such that it uses that instead of the `_error` defined within the `@variable` macro. Use cases come up for instance in InfiniteOpt.jl. 

**Describe the solution you'd like**
It would very helpful to add a keyword argument in JuMP macros with which a user-defined error function can be provided. By default if this keyword argument is not provided then just use the current implementation, otherwise if a user-defined error function is given it should be used in place of the `_error` defined inside the JuMP macro. 

For example a rough implementation for the `@variable` macro might look like this:
```julia
macro variable(args...)
    # Do initial arg processing
    model = esc(args[1])
    extra, kw_args, requestedcontainer = Containers._extract_kw_args(args[2:end])

    # Prepare the macro error function 
    error_kwargs = filter(kw -> kw.args[1] == :new_error_func_kw, kw_args)
    if isempty(error_kwargs)
        _error(str...) = _macro_error(:variable, args, __source__, str...) # no user-defined function provided
    else
        _error = error_kwargs[1].args[2]
    end

    # Implement rest of the macro as is (except remove the `:new_error_func_kw` from the `extra_kw_args`
    .
    .
    .
end
```
With this revised version, the above extension example would become:
```julia
using JuMP

macro my_new_variable(model, args...)
   # Define macro error function that is relevant to this macro
   _my_error_func(str...) = JuMP._macro_error(:my_new_variable, (model, args...), __source__, str...)

   # Do desired extension manipulations before calling JuMP.@variable (calling _my_error_func where needed)
   new_args = args # do nothing in this example for simplicity

   # Prepare and return the code wrapping JuMP.@variable 
   code = :( JuMP.@variable($model, $(new_args...), new_error_func_kw = $(_my_error_func)) )
   return esc(code)
end 

# Make a call that invokes an error 
model = Model()
@my_new_variable(model, [1:2] >= 0) 
```
Now the resulting error would look something like:
```julia
ERROR: At REPL[9]:1: `@my_new_variable(model, [1:2] >= 0)`: Cannot use explicit bounds via >=, <= with an anonymous variable.
Stacktrace:
.
.
.
```
Thus, an extension user obtains meaningful error messages.

**Describe alternatives you've considered**
My current workaround in InfiniteOpt is I utilize the `extra_kw_args` support to pass on my macro specific error functions on to the extended build functions (e.g., build_variable) where this when provided replaces the `_error` argument in the build function. This approach works, but it is not able to address the error function calls that take place inside the JuMP macros.

**Comment by odow** [comment]
The real issue is that you are touching a lot of internal functions (the ones beginning with `JuMP._`). These functions should be considered private, and they can break between patch versions. You can reasonably depend on public functions within the macro code, which don't begin with `_`.

A more robust way for your macros might be to copy-paste the bits you need into InfiniteOpt with the appropriate license header.

**Comment by blegat** [comment]
The recommended way to extend the `@variable` macro is by creating new method for `build_variable`,...

**Comment by pulsipher** [comment]
Oscar, duly noted on the use of internal functions. I will implement my own versions in the near future. All my implementations do as well extend `build_variable`, `add_variable`, etc. as recommended for extension. 

With that all in mind, I still think there is a use case here for adding functionality to enable user-defined error functions. Specifically, this would better enable wrapper macros on extensions that foster a symbolic interface for users.  To make this less arbitrary let me briefly illustrate with one of my variable extensions. 

For example, in InfiniteOpt let's say we wish to define a dynamic variable ``x(t)`` where `t` denotes time. To accommodate such variables I have made an `InfiniteVariable` struct that can be built and added using extended versions of `JuMP.build_variable` and `JuMP.add_variable` which enable `JuMP.@variable` using `variable_type`. Thus, we can code:
```julia
using JuMP, InfiniteOpt

# Preliminaries
m = InfiniteModel()
@infinite_parameter(m, t in [0, 10]) # define time parameter using InfiniteOpt macro (i.e., no JuMP macro dependencies)

# Define an infinite variable using @variable w/ recommended extensions 
@variable(m, x, variable_type = Infinite, parameter_refs = (t, )) # both keyword args are required
```
However, this syntax is/becomes quite verbose especially as we specify variable bounds, container types, etc. Thus, to provide a symbolic interface I have `@infinite_variable` which wraps around the above to give:
```julia
@infinite_variable(m, x(t))
```
This significantly streamlines things (especially for more complex definitions). However, this now brings me back to the problem behind this feature request which is that any error incurred will stem from the error function defined within `JuMP.@variable` which will not correspond to what the user entered. Thus, having the option for `@infinite_variable` to supply its own error function to `JuMP.@variable` would help circumvent this problem. This could amount to adding an extra keyword argument to `JuMP.@variable` for use in extensions similar to what is currently done with `variable_type`.

Such a capability would be useful for extensions that wish to implement symbolic interfaces (using macros) while leveraging the supported extendability of JuMP. An alternative to resolving this would amount to defining my own version of `@variable`, but that would seem redundant.

**Comment by mlubin** [comment]
How is it that invalid input to `@infinite_variable` causes invalid input to `@variable`? Can you do validation before calling `@variable`?

**Comment by odow** [comment]
The syntax I have for SDDP state variables is 
```Julia
@variable(model, x, SDDP.State; initial_value = 0)
```

It should be possible to create
```Julia
@variable(model, t, InfiniteParameter(0, 10))
@variable(model, x, Infinite(t))
```

**Comment by pulsipher** [comment]
> How is it that invalid input to `@infinite_variable` causes invalid input to `@variable`? Can you do validation before calling `@variable`?

`@infinite_variable` only handles the symbolic extension syntax (i.e., adding on the infinite parameter(s)), thus errors such as double specifying a lower bound symbolically and via the keyword arg would come up in the `@variable`. Such could be validated in `@infinite_variable`, but then it would end up having to repeat a lot of the processing already done in `@variable`.

> 

> The syntax I have for SDDP state variables is
> 
> ```julia
> @variable(model, x, SDDP.State; initial_value = 0)
> ```
> 
> It should be possible to create
> 
> ```julia
> @variable(model, t, InfiniteParameter(0, 10))
> @variable(model, x, Infinite(t))
> ```

This is interesting, I'll have to look into this further.

**Comment by mlubin** [comment]
Syntax doesn't compose across macros in different packages like APIs do. Any approach that forwards what the user wrote down from your macro to a JuMP macro is going to have fundamental issues with error handling. Maybe this is worth it for developer convenience. Another option is to offer a more limited syntax that you parse and validate in `@infinite_variable`. For example, there's probably not a good reason to allow two ways to specify a lower bound.

**Comment by pulsipher** [comment]
> Syntax doesn't compose across macros in different packages like APIs do. Any approach that forwards what the user wrote down from your macro to a JuMP macro is going to have fundamental issues with error handling. Maybe this is worth it for developer convenience. Another option is to offer a more limited syntax that you parse and validate in `@infinite_variable`. For example, there's probably not a good reason to allow two ways to specify a lower bound.

That all makes sense and yes I agree such an approach is not the most elegant, but it probably just comes down to a matter of developer convenience in leveraging JuMP's capabilities for enabling a symbolic API. With that said, I understand if this is a route you all would prefer not to support and I can look into forgoing the symbolic API in favor of something more function based like what Oscar suggested or building more robust macros that handle all of the validation (likely removing the dependency of `@variable`) along the lines of your suggestion. Thank you all for time and suggestions thus far.

**Comment by odow** [comment]
@pulsipher what's the current status of this? Can we close?

**Comment by pulsipher** [comment]
Yeah, we can close this. Having an issue to reflect the need to refractor the variable macros more generally would be nice though.

**Comment by odow** [comment]
Yeah there are a few macro related issues open. I'm very aware of the need for a refactor. But I'm hoping it's a post-1.0 type thing. For 1.0, we'll just say that accessing the internals of the macros is not supported.
