### ISSUE TITLE
L1 regularization with box constraint in JuMP?

### ISSUE THREAD

**Issue by yewalenikhil65** [jump-dev/JuMP.jl#2361]
Does JuMP have L1 regularization with box constraint in following form as utility ?

minimize || Ax - b ||
subject to 1st norm of x i.e. |x| < lambda (some parameter)
and 0 <= x[i] <= kappa (some parameter)
where, A is some tall matrix and b is some tall vector

(If not, and you know any other package that supports such kind of optimization, please let me know)

**Comment by odow** [comment]
This question is better asked on the Community Forum: https://discourse.julialang.org/c/domain/opt/13.

But you're looking for the [`NormOneCone`](https://jump.dev/MathOptInterface.jl/stable/apireference/#MathOptInterface.NormOneCone).
```Julia
using JuMP
model = Model()
@variable(model, x)
@variable(model, t)
@constraint(model, [t, x] in MOI.NormOneCone(2))
```

**Comment by odow** [comment]
Closing since discussion has moved to Discourse: https://discourse.julialang.org/t/l1-regularization-with-box-constraint-in-jump/49105
