### ISSUE TITLE
Feature request: implement getindex for expressions

### ISSUE THREAD

**Issue by remi-garcia** [jump-dev/JuMP.jl#2371]
I would like to access the objective coefficients yet it just possible to access the function as an expression.
My solution would be:
```julia
"""
    objective_coefficient(model::Model, variable::VariableRef)

Return the coefficient associated with `variable` in the objective function. See
also [`set_objective_coefficient`](@ref).

Note: this function will throw an error if a nonlinear objective is set.
"""
function objective_coefficient(model::Model, variable::VariableRef)
    return get(objective_function(model).terms, variable, 0.0)
end
```

Yet, I have no idea how quadratic objective functions should be handled and what to do if someone tries the following
```julia
model_1 = Model()
@variable(model_1, x >= 0)
@objective(model_1, Min, x)
model_2 = Model()
@variable(model_2, y >= 0)
@objective(model_2, Min, y)

objective_coefficient(model_1, y)
```

**Comment by mlubin** [comment]
This is already a one-liner (as you show above), and the proposed version is slow inside a loop because `objective_function(model)` may be expensive. I'm not really seeing the benefit of adding this to JuMP.

**Comment by remi-garcia** [comment]
> I'm not really seeing the benefit of adding this to JuMP.

Actually, when I needed this function I was sure I would find it in JuMP. With CPLEX.jl there is `CPLEX.get_obj(model::CPLEX.Model)`, which returns a vector of coefficients.

**Comment by mlubin** [comment]
I'd say that `objective_function(model)` is the analogue of `CPLEX.get_obj`. It returns a data structure that represents the objective function. The proposed implementation of `objective_coefficient` is not a clear win because `objective_coefficient.(model, all_variables(model))` could be O(N^2).

**Comment by odow** [comment]
I agree with @mlubin. We already provide `objective_function`, and the returned data-structure is pretty transparent. 

What we could implement are `getindex` methods along the likes of;
```Julia
function Base.getindex(ex::GenericAffExpr{V, K}, x::K) where {K, V}
    return get(ex.terms, x, zero(V))
end
```
That would permit
```Julia
model = Model()
@variable(model, x)
@variable(model, y)
@objective(model, Min, x)
obj = objective_function(model)
obj[x]  # 1.0
obj[y]  # 0.0
@objective(model, Min, x^2 + x * y + x)
obj = objective_function(model)
obj[x, x]  # 1.0
obj[x, y]  # 1.0  # What about obj[y, x]?
obj[y, y]  # 0.0
obj[x]  # 1.0
obj[y]  # 0.0
```

**Comment by linde-fr** [comment]
I am getting a `ERROR: MethodError: no method matching getindex(::ReferenceMap, ::Array{GenericQuadExpr{Float64,VariableRef},1})` 
when trying to copy a model that contains quadratic expressions. Is this related to this topic?

**Comment by junglegobs** [comment]
I wouldn't mind doing this, if someone could tell me:
1. Where this would go - I guess in `aff_expr` and `quad_expr`?
2. Would it be as simple as implementing what @odow  suggested (taking care if you do `obj[x,y]` since this wouldn't be quadratic)?
3. In @odow's example, there's the special case where the objective function is just a `VariableRef`, so should I also implement something along the lines of:
```julia
function Base.getindex(v1::VariableRef, v2::VariableRef)
   v1 === v2 && return 1
   return error("Don't know what this means.")
end
```

**Comment by blegat** [comment]
1. Yes
2. Yes, `obj[x,y]` is zero if `obj` is `VariableRef` of `GenericAffExpr`
3. `Base.getindex(v1::VariableRef, v2::VariableRef) =  v1 == v2 ? 1.0 : 0.0`
4. Either a new branch or the master branch of your fork, up to you

**Comment by odow** [comment]
> this is my first time doing a pull request

Please ask questions! (@linde-fr may have some similar ones as well: https://github.com/jump-dev/JuMP.jl/issues/2425#issuecomment-769966675).

The general work-flow is to open Julia and run
```Julia
] dev JuMP
```
Then open a terminal (Or command prompt on Windows)
```
cd ~/.julia/dev/JuMP
git remote add junglegobs https://github.com/junglegobs/JuMP.jl.git
git checkout master
git pull
git checkout -b name-of-branch
```
Then edit the files in `~/.Julia/dev/JuMP` with your changes.
Test your changes by running 
```Julia
cd ~/.julia/dev/JuMP
julia --project=.
julia> ] test
```
Then back in the terminal
```
git add .
git commit -m "A descriptive message describing what you did"
git push -u junglegobs name-of-branch
```
Then go to https://github.com/jump-dev/JuMP.jl and follow the instructions that pop up to open a pull request.

**Comment by junglegobs** [comment]
This is exciting! So my implementations are:
```julia
# in aff_expr.jl
Base.getindex(a::GenericAffExpr{C,V}, v::V) where {C,V} = get(a.terms, v, zero(V))
Base.getindex(a::GenericAffExpr{C,V}, v1::V, v2::V) where {C,V} = zero(V)

# in quadr_expr.jl
Base.getindex(q::GenericQuadExpr{C,V}, v::V) where {C,V} = q.aff[v]
function Base.getindex(q::GenericQuadExpr{C,V}, v1::V, v2::V) where {C,V}
    return get(q.terms, UnorderedPair(v1,v2), zero(V))
end

# in variables.jl
Base.getindex(v1::VariableRef, v2::VariableRef) = (v1 == v2 ? one(v1) : zero(v1))
Base.getindex(v1::VariableRef, v2::VariableRef, v3::VariableRef) = zero(v1)
```
I see however that `one(v::VariableRef)` returns an affine expression (similarly with zero) - should I just replace this with 1.0 and 0.0? (I had some vague notion that JuMP wasn't tied to using exclusively `Float64` after I read that `COSMO.jl` can be used with `BigFloat, but maybe I misunderstood?)

**Comment by odow** [comment]
Yes, I think we can have:
```julia
Base.getindex(v1::VariableRef, v2::VariableRef) = (v1 == v2 ? 1.0 : 0.0)
Base.getindex(v1::VariableRef, v2::VariableRef, v3::VariableRef) = 0.0
```
JuMP should get better at supporting things other than `Float64`, but it is hard to know what to do for this case. 

A bigger issue is: overloading `getindex` like this is a bit weird. Perhaps we should call the function `coefficient` instead? It's clearer, and we don't have weird methods like `Base.getindex(v1::VariableRef, v2::VariableRef, v3::VariableRef) = 0.0`.
```Julia
coefficient(expr::VariableRef, x::VariableRef) = (expr == x ? 1.0 : 0.0)
coefficient(expr::VariableRef, x1::VariableRef, x2::VariableRef) = 0.0
```

And yes, you should add those tests. 

I would recommend that you commit the code you have currently and open a pull request. Then we can talk through the changes.

**Comment by junglegobs** [comment]
Cool! Done.
