### ISSUE TITLE
Add a new variable to an existant constraint

### ISSUE THREAD

**Issue by GattH** [jump-dev/JuMP.jl#2376]
Hello everybody,

I am trying to compute a column-generation algorithm.
To do this, I need to add new variables to existing variable arrays.

I dit it with :

_push!(f, @variable(model,
                    lower_bound = 0, 
                    base_name = "f[$(nbElements+1)]",
                    start = 1)
            )_

But the problem is that I don't find any indication to modify constraints prealably created to add a new element to them..

I would like to transform a constraint like : 

_@constraint(model, ctrte[a in 1:nbArcs],
        - sum(f[l] for l in 1:nbElements
        >= M
)_

to add _f[nbElements+1]_ to it..

The only thing I read can add constant to a constraint but no variable. Does anybody know if something doing this exists?

Thanks a lot!

**Comment by odow** [comment]
See https://jump.dev/JuMP.jl/stable/constraints/#Modifying-a-variable-coefficient-1

**Comment by GattH** [comment]
Wonderful! Thanks a lot! 👍
