### ISSUE TITLE
Issues when fixing variable value using CPLEX

### ISSUE THREAD

**Issue by spuschel** [jump-dev/JuMP.jl#2400]
Hi,
I have been updating the libraries to use the latest versions of Gurobi and CPLEX.
In my code, I fix some integers after solving a MILP. I tested things with Gurobi with no issues, however, when I apply the CPLEX library I run into issues. I am posting here because the stacktrace points to JuMP as the source of the error. Refer to the minimal reproducible example below:

```julia
using JuMP, CPLEX
model = Model(CPLEX.Optimizer) 
@variable(model, 0 <= x <= 10, Int)
@variable(model, -9.5 <= y <= 3.4)
@objective(model, Max, 5x - 3 * y)

optimize!(model)

objective_value(model)

for v in all_variables(model)
    println(v)
    if is_integer(v)
        unset_integer(v) 
        fix(v,value(v); force=true)
    end
end

optimize!(model)
```
the error I get happens in the following line:
```
fix(v,value(v); force=true)
```
The stacktrace:
```
ERROR: LoadError: OptimizeNotCalled()
Stacktrace:
 [1] _moi_get_result(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::MathOptInterface.VariablePrimal, ::Vararg{Any,N} where N) at /Users/spuschel/.julia/packages/JuMP/qhoVb/src/JuMP.jl:846
 [2] get(::Model, ::MathOptInterface.VariablePrimal, ::VariableRef) at /Users/spuschel/.julia/packages/JuMP/qhoVb/src/JuMP.jl:878
 [3] value(::VariableRef; result::Int64) at /Users/spuschel/.julia/packages/JuMP/qhoVb/src/variables.jl:767
 [4] value at /Users/spuschel/.julia/packages/JuMP/qhoVb/src/variables.jl:767 [inlined]
 [5] top-level scope at /Users/spuschel/git/jPSO/src/testcplex.jl:16
```
Odd behaviour. As said, when I run it with Gurobi I get no issues and things happen as expected.
I am using JuMP v0.21.5 and CPLEX v0.7.4 (and Gurobi v0.9.4).
I hope you can give me a hand.
Thanks!
Sebastian

**Comment by blegat** [comment]
Your code mixes queries for the solution with `value(v)` and model changes with `unset_integer` and `fix`. After you change the model, the solution is discarded and you need to optimize to get the solution of the modified model. This explains the `OptimizeNotCalled` error.
In your case, I would recommend doing `sol = value.(all_variables(model))`. Before the loop and use this vector instead of `value` in the loop.

**Comment by odow** [comment]
See this warning in the docs (https://jump.dev/JuMP.jl/stable/solutions/#Obtaining-solutions-1):
![image](https://user-images.githubusercontent.com/8177701/101966587-28526880-3c7d-11eb-989d-55923fe6e675.png)
Although it could be made bigger and more explicit.

**Comment by spuschel** [comment]
> Your code mixes queries for the solution with `value(v)` and model changes with `unset_integer` and `fix`. After you change the model, the solution is discarded and you need to optimize to get the solution of the modified model. This explains the `OptimizeNotCalled` error.
> In your case, I would recommend doing `sol = value.(all_variables(model))`. Before the loop and use this vector instead of `value` in the loop.

Makes sense. However, the odd part is that the behaviour is not consistent for two different solvers (I don't get the error when I run it with gurobi).

**Comment by odow** [comment]
> the odd part is that the behaviour is not consistent for two different solvers

The underlying solvers have different behavior. This is one reason why the behavior at the JuMP level is undefined.

**Comment by spuschel** [comment]
got it! cheers
