### ISSUE TITLE
Copying expressions between models

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2407]
While working on #2405, I found theses two functions:

https://github.com/jump-dev/JuMP.jl/blob/90e63c47372e02b7093a9bf2fb4153dfa548c0a6/src/quad_expr.jl#L434-L439

https://github.com/jump-dev/JuMP.jl/blob/90e63c47372e02b7093a9bf2fb4153dfa548c0a6/src/aff_expr.jl#L425-L434

The first is invalid (the `.qvars1` fields have been replaced by an `OrderedDict`), so it clearly isn't tested or used by anyone in the last ~2 years. The second is tested here:
https://github.com/jump-dev/JuMP.jl/blob/90e63c47372e02b7093a9bf2fb4153dfa548c0a6/test/expr.jl#L157-L164

But it has an implicit assumption that the variables in the new model have the same `.value` field as the original model:
https://github.com/jump-dev/JuMP.jl/blob/90e63c47372e02b7093a9bf2fb4153dfa548c0a6/src/JuMP.jl#L796-L801

Now that we've moved to `MOI.copy_to`, can these be removed? Is anyone using them?

**Comment by blegat** [comment]
I assume these can be removed as they were not correct and not used by `copy`
