### ISSUE TITLE
How to use `constraint_by_name` for vectorized constraints

### ISSUE THREAD

**Issue by ShuhuaGao** [jump-dev/JuMP.jl#2432]
I played with the toy example for [Vectorized constraints](https://jump.dev/JuMP.jl/stable/constraints/#Vectorized-constraints-1).
```julia
using JuMP
model = Model()
@variable(model, x[i=1:2])
A = [1 2; 3 4]
b = [5, 6]
@constraint(model, con, A * x .== b)
```
Now the question is how we can retrieve the above constraint by name. The following code always returns `nothing`.
```julia
constraint_by_name(model, "con")  # nothing
constraint_by_name(model, "con[1]")  # nothing
```
Of course, `model[:con]` works but I want `constraint_by_name`.

A related question is what is the best way to check whether a variable (or a constraint) exists in a `model`. Currently, I am using `variable_by_name` and `constraint_by_name` as above, because the `model[:var]` throws an exception if `:var` does not exist and I have to wrap it with try-catch. I am wondering whether there is something like `:var in model`.

Version info:
- Julia 1.5.3
- JuMP v0.21.4

**Comment by blegat** [comment]
The subconstraints have no names, see https://github.com/jump-dev/JuMP.jl/blob/24d131610ff51a8187352e9a55df093ce1e4b6bb/src/macros.jl#L441
If you want names, do
```julia
@constraint(model, con[i in eachindex(b), A[i, :]'x == b[i])
```

**Comment by ShuhuaGao** [comment]
Thanks. But I think a name in this case is useful. Why does JuMP not assign a name? The behavior is somewhat unexpected. 

Also, could you please provide suggestions on how to check whether a variable or a constraint exists? Suppose that I have the candidate name as a symbol like `:var`.

**Comment by mlubin** [comment]
> Why does JuMP not assign a name? The behavior is somewhat unexpected.

It's a known issue: https://github.com/jump-dev/JuMP.jl/issues/1166

> Suppose that I have the candidate name as a symbol like :var

`:var in keys(object_dictionary(model))`

See also https://github.com/jump-dev/JuMP.jl/issues/1887.

Closing as a duplicate.
