### ISSUE TITLE
Extend CommonSolve.jl?

### ISSUE THREAD

**Issue by ChrisRackauckas** [jump-dev/JuMP.jl#2437]
https://github.com/SciML/CommonSolve.jl is a very simple library. Let's be friends and not overlap on `solve`?

**Comment by blegat** [comment]
Should we reexport CommonSolve in JuMP or just do
```julia
import CommonSolve
CommonSolve.solve!(model::Model) = optimize!(model)
```

**Comment by ChrisRackauckas** [comment]
Oh I didn't realize it was deprecated for `optimize!`. That would make it a non-issue then. https://github.com/jump-dev/JuMP.jl/blob/a945fb016e4750d77fb8643cbb43f7f8f620d7e3/src/optimizer_interface.jl#L86-L93

**Comment by odow** [comment]
Can this be closed then? The deprecation for `solve` will stay for a few more releases, but at this point, no one should be calling `JuMP.solve` in any real code. It's just to help people who are still transitioning from the previous version (e.g., https://github.com/jump-dev/JuMP.jl/issues/2438).
