### ISSUE TITLE
Migrate JuMPTutorials

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2483]
This issue is to track the progress of migrating the [modeling tutorials from JuMPTutorials](https://github.com/jump-dev/JuMPTutorials.jl/tree/master/script/modelling).

* Tutorials should be added to some suitable subfolder of https://github.com/jump-dev/JuMP.jl/tree/master/docs/src/tutorials (make one if it doesn't fit. e.g., The examples have `MILP`, `Nonlinear`, `Quadratic`, and `SDP`). We could (and probably should) convert the existing examples into tutorials overtime.
* In addition, they need to be converted from Weave to Literate.
* Some tutorials require extra packages. We should try to minimize the number of new dependencies. <s>For example, we don't need Plots and Gadfly. If `Plots` adds too much to the CI runtime, we could consider using `GRUtils` instead.</s> Plots has been added.

## Tutorials

- [x] #2489 experiment_design
- [x] facility_location
    - Needs `Plots`
- [x] #2489 finance
- [x] #2489 geographic_clustering
    - Needs `Distances`
- [ ] geometric_problems
    - Needs `Gadfly` (Convert to `Plots` instead?)
- [ ] maxcut
    - Needs `LightGraphs`, `Graphplot`, `Colors`
    - These are quit a few dependencies. Do we need this tutorial?
- [x] #2489 n-queens
- [x] #2489 network_flows
- [x] #2489 power_systems
    - Original license:  Creative Commons Attribution-ShareAlike 4.0 International License.
    - https://github.com/JuliaOpt/juliaopt-notebooks/blob/master/notebooks/Dvorkin%20-%20Power%20systems%20-%20Economic%20dispatch%20and%20Unit%20commitment.ipynb
- [ ] problems_on_graphs
     - Needs `LightGraphs`, `Graphplot`, `Colors`
     - These are quit a few dependencies. Do we need this tutorial?
- [x] #2489 rocket_control
    - Original license:  Creative Commons Attribution-ShareAlike 4.0 International License.
    - https://github.com/JuliaOpt/juliaopt-notebooks/blob/master/notebooks/JuMP-Rocket.ipynb
- [x] #2489 sudoku
    - Delete existing [example](https://github.com/jump-dev/JuMP.jl/blob/master/docs/src/examples/Mixed-integer%20linear%20programs/sudoku.jl).

## Unmerged PRs

- [x] #2496 https://github.com/jump-dev/JuMPTutorials.jl/pull/97
- [x] #2499 https://github.com/jump-dev/JuMPTutorials.jl/pull/71
- [ ] https://github.com/jump-dev/JuMPTutorials.jl/pull/49
## Unresolved issues

- [x] #2501 https://github.com/jump-dev/JuMPTutorials.jl/issues/53

**Comment by blegat** [comment]
Is there a rule for whether something is an example or a tutorial or should all examples become tutorials ?

**Comment by odow** [comment]
Not really. I wonder if we should just move all the examples into the tutorials folder now.

**Comment by joaquimg** [comment]
+1 for merging folders.

Distances is no "really" needed. Haversine is like 5 lines of code + 1 link to wikipedia. We can reference the package.

I imagine we are considering having examples with plots but using a single framework to minimize deps.

**Comment by frapac** [comment]
> I imagine we are considering having examples with plots but using a single framework to minimize deps.

How about using [UnicodePlots](https://github.com/Evizero/UnicodePlots.jl) as a plotting library? It does not require many deps, and comes with an acceptable time to first-plot. In my experience, the rendering in Weave/Literate notebooks is more than ok.

**Comment by odow** [comment]
The doc build currently takes ~11 minutes, so I think we can take the hit with Plots. Although if we switched the doc build to Julia 1.6, things would be much quicker.

**Comment by ferrolho** [comment]
The way the docs are currently built seems to share the same context for the different examples. This means that I had to abstain from using `const` on some global variables in the notebook, and I also had to rename one of the functions because its name was generic enough to have already been defined in some previous notebook.

On a separate note, +1 for the inclusion of `Plots`.

**Comment by odow** [comment]
> The way the docs are currently built seems to share the same context for the different examples.

Hmm. They shouldn't. Maybe I've configured things wrong.

I might need a `let` around
https://github.com/jump-dev/JuMP.jl/blob/f01adac6038d5f496f2624f3beb7e9532a4e9050/docs/make.jl#L42-L50

**Comment by odow** [comment]
Closing this as substantially done. The tutorials could always use more work tidying them up, but I don't think we need an issue to track that.
