### ISSUE TITLE
JuMP logo on night/dark theme

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/JuMP.jl#2492]
![image](https://user-images.githubusercontent.com/13870065/108604953-b3439380-738f-11eb-9e15-f5ac0e3e9bd5.png)

This is what I get on my phone's github app.
One possible fix is to use a picture with white background...

**Comment by odow** [comment]
I made an attempt here: https://github.com/jump-dev/JuMP.jl/pull/2535

But we probably need to add a white outline to the text, if anyone has SVG skills to do so.

**Comment by odow** [comment]
Closing as duplicate of https://github.com/jump-dev/JuMP.jl/issues/2581
