### ISSUE TITLE
Explain difference of parameter and variable?

### ISSUE THREAD

**Issue by cdeil** [jump-dev/JuMP.jl#2500]
In [nonlinear_modelling.ipynb#Parameters](https://nbviewer.jupyter.org/github/JuliaOpt/JuMPTutorials.jl/blob/master/notebook/using_JuMP/nonlinear_modelling.ipynb#Parameters) I see this explanation of parameters.

I don't get it. Why do you have a `@NLparameter` and not simply use `@variable` like in all the other models? When should I use which of the two?

Can you please add 1-2 sentences explaining this to the tutorial?

(Unless you can get rid of `@NLparameter` and merge it's functionality into `@variable` - then please do that to keep it simple for the user.)

![Screenshot 2020-04-12 at 22 35 09](https://user-images.githubusercontent.com/852409/79079194-ed72ec00-7d0d-11ea-8e35-11907c86b24b.png)

**Comment by odow** [comment]
Transferred from JuMPTutorials, because this should be better addressed in the JuMP documentation.
