### ISSUE TITLE
Register non linear parameters in the model

### ISSUE THREAD

**Issue by davidanthoff** [jump-dev/JuMP.jl#2509]
There is already a TODO for this in the code [here](https://github.com/jump-dev/JuMP.jl/blob/749c828236dea3a065a428b93df7a60437d80052/src/macros.jl#L1750) :)

It would be awesome if NL parameters were registered in the model so that for example expression printing could use the proper name of the parameter in its output. Also, just seems in general that it should be that way?

**Comment by odow** [comment]
As you've probably started to realize, nonlinear is a second-class citizen in JuMP at present. There are a number of features that are not implemented.
