### ISSUE TITLE
Replace Containers with an external package

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2523]
@oxinabox raised the possibility of replacing JuMP's `Containers` package with a different package.

More than 10% of our current open issues are [related to containers](https://github.com/jump-dev/JuMP.jl/issues?q=is%3Aissue+is%3Aopen+label%3A%22Category%3A+Containers%22), so it makes sense to offload this to a specialized package.

A wholesale replacement is probably too breaking for JuMP 1.0, but we should think about ways to make it easier to create containers of JuMP variables using external containers.

DenseAxisArray:
* https://github.com/mcabbott/AxisKeys.jl
* https://github.com/Tokazama/AbstractIndices.jl
* https://github.com/rafaqz/DimensionalData.jl

SparseAxisArray:
 * Just a standard `Dict`?
 * Or a `DenseAxisArray` with holes?

**Comment by blegat** [comment]
+1 for moving it a separate package. https://github.com/mcabbott/AxisKeys.jl could not replace `DenseAxisArrays` as indexing with brackets expect the indexing of the underlying `Array`. If we have a separate package, we could define clearly the API needed (I think it's the `container` function) so that external packages can define it and be usable from JuMP without having to have JuMP in their dependencies.

**Comment by odow** [comment]
I think I'm okay keeping the `Containers` submodule. It gives us greater control over what happens as the default for JuMP. But we should add documentation to make it easy to use different Containers.

At the moment, all we have is https://jump.dev/JuMP.jl/stable/variables/#User-defined-containers

**Comment by odow** [comment]
If we remove https://github.com/jump-dev/JuMP.jl/blob/e2b6ee959c827d60f0c8178a813fddb6e21048b2/src/Containers/macro.jl#L188-L199, then we can dispatch on any container type. 

```Julia
julia> using JuMP

julia> function Containers.container(f::Function, indices, ::Type{Dict})
           return Dict(i => f(i...) for i in indices)
       end

julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x[1:2, 1:2], container=Dict)
Dict{Tuple{Int64, Int64}, VariableRef} with 4 entries:
  (1, 2) => x[1,2]
  (1, 1) => x[1,1]
  (2, 2) => x[2,2]
  (2, 1) => x[2,1]
```
