### ISSUE TITLE
Feasibility checker with function

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#2526]
In the `primal_feasibility_report` just introduced by https://github.com/jump-dev/JuMP.jl/pull/2466, we expect the primal value to be given by a `Dict`. In the future, we might rely on `MOIU.eval_variables` to evaluate the function which requires a function mapping the variables to their values as arguments so we will have to create a lambda from the `Dict`. In view of this, we could also accept a function as argument to specify the value of the variables.
To allow the syntax:
```julia
primal_feasibility_report(model, tol) do var_ref
    ...
end
``` 
we should have the `point` as a first argument while it is currently the second argument.

**Comment by odow** [comment]
We made it an `AbstractDict` and not a `Dict` so you can go:
```Julia
struct FunctionalDict{F} <: AbstractDict
    f::F
end
Base.getindex(f::FunctionalDict, key::VariableRef) = f.f(key)

FunctionalDict(x -> value(x))
```

Do we have a concrete use-case for this? I'm not in favor of adding complexity and multiple ways to do something before we really need to.

**Comment by blegat** [comment]
Currently, we convert all function to JuMP before evaluating them. When we'll start looking at performance, we'll notice that we should directly evaluate them at the MOI level hence use:
https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Utilities/functions.jl#L6-L13
so passing a function is more efficient.
There are indeed two use cases. If the user has a costly way to get the value of the variables then he should first create a dict to avoid computing it twice. Otherwise, it's easier and more efficient to just pass a function.

**Comment by odow** [comment]
We already evaluate the functions using a function: 
https://github.com/jump-dev/JuMP.jl/blob/e4320ea4aeb9ce5c155ecae905d7cd953016eb36/src/feasibility_checker.jl#L60-L69
https://github.com/jump-dev/JuMP.jl/blob/e4320ea4aeb9ce5c155ecae905d7cd953016eb36/src/feasibility_checker.jl#L108

**Comment by odow** [comment]
To summarize the developer call:

* `primal_feasibility_report(model::Model, point::AbstractDict)` should stay.
* At some point in the future, we can add a non-breaking `primal_feasibility_report(point::Function model::Model)`
* Even if we add the functional form is added, we should not add `primal_feasibility_report(point::AbstractDict, model::Model)`.
* Before adding the functional form, we should wait until there is evidence that the functional form is more convenient than the dictionary.

I would then propose that we close this issue for now and re-visit it in the future.

**Comment by blegat** [comment]
Thinking more about this. I agree that if the user pass a function, he might expect that we memoize its results but we don't so that's an issue. In fact, this also applies to MOI functions. Even ScalarAffineFunction can have several terms with the same variable.
If the user has some custom way. In view of this, we should probably change `JuMP.value` so that it expects a dictionary and `MOI.eval_variable` so that it takes a dictionary as second argument.
We should check that we agree on a long term plan to have a consistent interface between `primal_feasibility_checker`, `value` and `eval_variable` before going forward

**Comment by odow** [comment]
The functional form of `value` is useful:
https://github.com/jump-dev/JuMP.jl/blob/2b08a39e564cb7d5fc4f6f94a5f7ac9cf4671f88/src/callbacks.jl#L64-L66
https://github.com/jump-dev/JuMP.jl/blob/2b08a39e564cb7d5fc4f6f94a5f7ac9cf4671f88/src/aff_expr.jl#L488-L490

The `value` functions are different, because they often apply to a very small subset of the model. (You don't want have to build a dictionary of every variable value just to call `callback_value`.) `primal_feasibility_report` applies to the whole model. 

So I don't think we need a consistent interface between `primal_feasibility_checker` and `value`. I think the design, as we have it, makes senses in both cases.
