### ISSUE TITLE
Pluto Notebook support.

### ISSUE THREAD

**Issue by waltsims** [jump-dev/JuMP.jl#2540]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I am trying to explore the JuMP exmaple in a Pluto notebook, and I cannot define a variable as described in the quickstart.

**Describe the solution you'd like**
I would like pluto notebook support

**Describe alternatives you've considered**
...

**Additional context**
This is the Minimal example that I am having issues with:

```
### A Pluto.jl notebook ###
# v0.12.21

using Markdown
using InteractiveUtils

# ╔═╡ 36b05920-8d98-11eb-1f1d-0b78df1fd03d

using JuMP

# ╔═╡ 26b6a19c-8d97-11eb-167a-b7ee62efa687
import Pkg; Pkg.add("JuMP")

# ╔═╡ 8e86a862-8d97-11eb-157c-8150efc5af6f
Pkg.add("GLPK")

# ╔═╡ 3af47c50-8d98-11eb-31f0-9bf25ff6f8d9
import GLPK

# ╔═╡ b25513e6-8d9c-11eb-3f3d-1d1b82813655
model = Model(GLPK.Optimizer)

# ╔═╡ 8b026044-8d9e-11eb-3aa5-39546b88dc15
@variable(model, 0 <= x <= 2)

# ╔═╡ Cell order:
# ╠═26b6a19c-8d97-11eb-167a-b7ee62efa687
# ╠═8e86a862-8d97-11eb-157c-8150efc5af6f
# ╠═36b05920-8d98-11eb-1f1d-0b78df1fd03d
# ╠═3af47c50-8d98-11eb-31f0-9bf25ff6f8d9
# ╠═b25513e6-8d9c-11eb-3f3d-1d1b82813655
# ╠═8b026044-8d9e-11eb-3aa5-39546b88dc15

```

I get the error:

> cannot assign a value to variable workspace3.x from module workspace85
> 
>     macro expansion@macros.jl:102[inlined]
>     top-level scope@Local: 1

**Comment by odow** [comment]
This issue a problem with Pluto: It doesn't understand macros https://github.com/fonsp/Pluto.jl/issues/196 or mutation https://github.com/fonsp/Pluto.jl/issues/564.

These two issues mean that there is no way to use JuMP in Pluto.

**Comment by waltsims** [comment]
Thanks for the fast response. Hope that change soon.

-walter

**Comment by odow** [comment]
I wouldn't expect it to change anytime soon. Pluto has a strong vision for reactivity, and that is at odds with JuMP's workflow.

**Comment by waltsims** [comment]
Thanks, that’s too bad.

**Comment by joaquimg** [comment]
Pluto initialises any variable?
Maybe we can check if in Pluto and display a pretty error...

**Comment by odow** [comment]
The Pluto dev's are aware of the issue, including this specific error message: https://github.com/fonsp/Pluto.jl/issues/196#issuecomment-650415188
