### ISSUE TITLE
type unstability with container generation

### ISSUE THREAD

**Issue by etienneINSA** [jump-dev/JuMP.jl#2552]
```julia 
julia> model = Model(Gurobi.Optimizer)

julia> @variable(model, a[x in 1:10; x < 5], Bin)
JuMP.Containers.SparseAxisArray{VariableRef, 1, Tuple{Int64}} with 4 entries:

julia> @variable(model, b[x in 1:10; x > 15], Bin)
JuMP.Containers.SparseAxisArray{Any, 1, Tuple{Any}} with 0 entries
```
Here, I would expect the second example to return a `JuMP.Containers.SparseAxisArray{VariableRef, 1, Tuple{Int64}}`
I don't know if the current behaviour is expected, but it can cause type unstability if we don’t check the emptiness of the resulting container beforehand.

**Comment by odow** [comment]
Thanks for opening an issue. Empty dictionaries seem to be well-typed, so maybe there is something we can do:
```Julia
julia> Dict(x => x for x in 1:10 if x > 15)
Dict{Int64, Int64}()
```

Here is the backstory on Discourse: https://discourse.julialang.org/t/type-unstability-with-container-generation-in-jump/58433

**Comment by odow** [comment]
Here's the problem: https://github.com/jump-dev/JuMP.jl/blob/41e4bf0a1c4b71e37e8cc10d958d7818df891d38/src/Containers/container.jl#L117-L123

**Comment by blegat** [comment]
`Dict(x => x for x in 1:10 if x > 15)` is using some dark magic to work. See the `_iterator_upper_bound` function:
https://github.com/JuliaLang/julia/blob/8218480f059b7d2ba3388646497b76759248dd86/base/abstractdict.jl#L541
https://github.com/JuliaLang/julia/blob/8218480f059b7d2ba3388646497b76759248dd86/base/array.jl#L628-L656
We could use `Base.@default_eltype` as well.
