### ISSUE TITLE
Logo thoughts

### ISSUE THREAD

**Issue by cormullion** [jump-dev/JuMP.jl#2581]
Now that Dark Mode is everywhere, many logos are suddenly confronting their dark side - or lack of it. I noticed that the JuMP logo doesn't work too well in all contexts.

In the sidebar of the Documenter docs, there is a provision for both light-mode and dark-mode logos. So it would be possible to have two versions of the logo, one light, one dark, and Documenter can switch between them automatically (the dark one has to be called `logo-dark.svg`.

<img width="555" alt="Screenshot 2021-05-02 at 16 08 03" src="https://user-images.githubusercontent.com/52289/116817903-96ca9100-ab60-11eb-82b9-064e92fb3a6c.png">

It occurred to me that a square-er version of the logo might work better in some situations:

<img width="662" alt="Screenshot 2021-05-02 at 16 09 11" src="https://user-images.githubusercontent.com/52289/116817952-beb9f480-ab60-11eb-8d78-bf6f70837c5c.png">

When used elsewhere, there's an alternative to having a white box around the entire logo - you can make a version that has a small white outline around each shape, so that the same image can work against any background:

<img width="474" alt="Screenshot 2021-05-02 at 16 13 34" src="https://user-images.githubusercontent.com/52289/116818077-6afbdb00-ab61-11eb-8b4e-6bbe45f3c763.png">

It mostly works...

If you want any of these, let me know - I can make a PR with a suitable SVG (or you can have the code).

**Comment by odow** [comment]
I like the first option. 

However, we use both the square and rectangular logos:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/8177701/116825610-2402f980-abe4-11eb-8d8a-735ef48cf70d.png">
I guess the square one switches out to `logo-dark.svg`, but we'd need some way of switching the main logo. I guess that's just a matter of some css somewhere?

**Comment by joaquimg** [comment]
+1 for the first option

**Comment by cormullion** [comment]
> but we'd need some way of switching the main logo

Unfortunately switching images according to the current theme isn't supported by Documenter... (https://github.com/JuliaDocs/Documenter.jl/issues/1560)

**Comment by odow** [comment]
Should be something like

`assets/extra_style.css`:
```
.display-light-only {
    display: block;
}

.theme--documenter-dark .display-light-only {
    display: none;
}

.display-dark-only {
    display: none;
}

.theme--documenter-dark .display-dark-only {
    display: block;
}
```

`Index.html`:
```
<img class="display-light-only" src="assets/light-jump-logo-with-text.svg" alt="JuMP logo"/>
<img class="display-dark-only" src="assets/dark-jump-logo-with-text.svg" alt="JuMP logo"/>
```
