### ISSUE TITLE
Enhance Usability of Variable(s)ConstrainedOnCreation for Extensions

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#2594]
For extensions like InfiniteOpt.jl that introduce a number of new scalar like variable types (e.g., `InfiniteVariable`, `PointVariable`) in addition to `JuMP.ScalarVariable`, enabling the use of variable sets built into JuMP (e.g., `MOI.AbstractVectorSet`, `JuMP.SymMatrixSpace`, `JuMP.SecondOrderCone`) is a little tedious since all of their respective `JuMP.build_variable` methods are typed to `JuMP.ScalarVariable` or `Vector{<:JuMP.ScalarVariable}`. Thus, extensions like InfiniteOpt.jl need to extend `JuMP.build_variable` for all these cases to work with the extension variable types. 

One idea to alleviate this problem would be to introduce a new abstract variable type to JuMP for scalar variables:
```julia
abstract type AbstractScalarVariable <: AbstractVariable end
```
Then let 
```julia
struct ScalarVariable{S,T,U,V} <: AbstractScalarVariable
    info::VariableInfo{S,T,U,V}
end
```
With this, all the the appropriate `JuMP.build_variable` methods could be typed with `JuMP.AbstractScalarVariable` or `Vector{<:JuMP.AbstractScalarVariable}`. Then extensions like InfiniteOpt.jl could inherit these by simply having the extended variable types inherit `JuMP.AbstractScalarVariable` as appropriate.

If this sounds agreeable, I would be happy to make a pull request.

**Comment by blegat** [comment]
Given that it's supported by the structs:
https://github.com/jump-dev/JuMP.jl/blob/80626541cc19005d1cb48958531d2ec71e8b7bf7/src/variables.jl#L1030
https://github.com/jump-dev/JuMP.jl/blob/80626541cc19005d1cb48958531d2ec71e8b7bf7/src/variables.jl#L1085
We could just replace `ScalarVariable` by `AbstractVariable` in:
https://github.com/jump-dev/JuMP.jl/blob/80626541cc19005d1cb48958531d2ec71e8b7bf7/src/macros.jl#L1351
and
https://github.com/jump-dev/JuMP.jl/blob/80626541cc19005d1cb48958531d2ec71e8b7bf7/src/macros.jl#L1358

**Comment by pulsipher** [comment]
If possible I would also like to cover the `build_variable` definitions in sd.jl and sets.jl.
For example:
https://github.com/jump-dev/JuMP.jl/blob/80626541cc19005d1cb48958531d2ec71e8b7bf7/src/sets.jl#L16
and 
https://github.com/jump-dev/JuMP.jl/blob/80626541cc19005d1cb48958531d2ec71e8b7bf7/src/sd.jl#L245

**Comment by blegat** [comment]
Yes, that makes sense as well.
