### ISSUE TITLE
stable printing for SparseAxisArray.jl

### ISSUE THREAD

**Issue by vtjnash** [jump-dev/JuMP.jl#2624]
It might be better to show the array in a stable form via `sort`. This shouldn't make any performance difference, but look better and solve https://github.com/jump-dev/JuMP.jl/issues/2623.
https://github.com/jump-dev/JuMP.jl/blob/cde8bb54cf4f70841ca6c4a59ed6f4c848241ff0/src/Containers/SparseAxisArray.jl#L296
==>
```julia
 for (i, key) in enumerate(sort!(collect(keys(x.data))))
   value = x.data[key]
```

**Comment by blegat** [comment]
Performance in printing is not critical but we cannot really expect the keys to implement `sort`. Maybe we could use a `OrderedDict`, we do that at other places in JuMP to make sure things are easy to reproduce (with affine expressions for instance).
