### ISSUE TITLE
Error message improvement for value(Array of NLexpression)

### ISSUE THREAD

**Issue by anastasianikolako** [jump-dev/JuMP.jl#2635]
When calling `value(u)` where `u` is an array of variables the following error shows up
```julia
julia> value(u)
ERROR: `JuMP.value` is not defined for collections of JuMP types. Use Julia's broadcast syntax instead: `JuMP.value.(x)`.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] value(#unused#::Matrix{VariableRef})
   @ JuMP C:\Users\user\.julia\packages\JuMP\Xrr7O\src\variables.jl:1204
```
This error is helpful.

On the other hand, when calling `value(u)` where `u` is an array of nonlinear expressions the error is
```julia
ERROR: LoadError: MethodError: no method matching value(::Matrix{NonlinearExpression})
```
This is not as helpful as it does not say that `value.` should be used instead.

**Comment by odow** [comment]
Thanks for raising the issue. 

There is this error:
https://github.com/jump-dev/JuMP.jl/blob/2871a06cb3c9115eb167c88e5ab8ef1ee40133e2/src/variables.jl#L1230-L1235
but it looks like we need to make `NonlinearExpression <: AbstractJuMPScalar`:
https://github.com/jump-dev/JuMP.jl/blob/5bdec266ea2dc435d1ff3237930410faf2cf0411/src/JuMP.jl#L1373
