### ISSUE TITLE
objective_value(model) returns the wrong objective function evaluation

### ISSUE THREAD

**Issue by anastasianikolako** [jump-dev/JuMP.jl#2637]
In the following code calling the `objective_value(model)` returns a different value from a value evaluation of the objective function at the optimal point.

This is due to `y_m` and `y_p` being subtracted elementwise in the objective function, when `y_m` is 1x2 matrix and `y_p` is 2x1 vector. Transposing `y_m` when calling `set_value.(y_m_param, y_m')`, fixes the problem, and the two commands `objective_value(model)` and `value(ObjFun(y_p,y_m,nu,model))` return the same value.
```julia
function ObjFun(y_p,y_m,ny,model=nothing)
    y_f = @NLexpression(model, [j=1:ny],  y_m[j] - y_p[j])
    return @NLexpression(model, sum(y_f[j]^2 for j in 1:ny))
end
using LinearAlgebra
# import NLopt
# model = Model(NLopt.Optimizer)
# set_optimizer_attribute(model, "algorithm", :LD_MMA)
import Ipopt
model = Model(Ipopt.Optimizer)
set_silent(model)
nu = 2;  Wy=[1,1]; y_p = [0.5,300]; y_m = hcat(0.7,250)  

@variable(model,  u[j=1:nu] )
@NLparameter(model, y_p_param[i=eachindex(y_p)] == y_p[i])
@NLparameter(model, y_m_param[i=eachindex(y_m)] == y_m[i])
obj=ObjFun(y_p_param,y_m_param,nu,model)
@NLobjective(model, Min, obj)
  
set_value.(y_p_param, y_p); set_value.(y_m_param, y_m)
optimize!(model)
@show termination_status(model)
@show primal_status(model)
@show objective_value(model); @show value(ObjFun(y_p,y_m,nu,model))
```

**Comment by blegat** [comment]
What's happening is that `set_value.(y_m_param, y_m)`. Because of the different shapes, the broadcast does
```julia
[
    set_value(y_m_param[1], y_m[1]) set_value(y_m_param[1], y_m[2])
    set_value(y_m_param[2], y_m[1]) set_value(y_m_param[2], y_m[2])
]
```
which is equivalent to
```julia
set_value(y_m_param[1], y_m[2])
set_value(y_m_param[2], y_m[2])
```
because it overwrites the setting to `y_m[1]`.

**Comment by anastasianikolako** [comment]
Thank you, this explanation is very helpful. Being a new user to Jump, I still have some misconception regarding broadcasting.
