### ISSUE TITLE
Constructor of Array with DenseAxisArray

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#2644]
This was discussed in the JuliaLab meeting today. The current behavior of `JuMP.DenseAxisArray` is consistent with `OffsetArray` in the sense that `similar` converts it onto an `Array` but `Array` gives an error.
Making `convert` work would be too much as `convert` is called implicitly when in `setindex!` or when setting fields of `struct`s.
However, @stevengj suggested that the `Array` constructor should be allowed to coercing the `JuMP.DenseAxisArray` into dropping its dimensions would be reasonable.
We might want to follow the development on `OffsetArray` and follow what's decided there.

**Comment by odow** [comment]
To clarify, you're proposing the following?
```Julia
Base.Array(x::DenseAxisArray) = x.data
```
Or something else?

**Comment by blegat** [comment]
Yes exactly, also one for `Array{N}`
