### ISSUE TITLE
copy conflict fails when model has parameters

### ISSUE THREAD

**Issue by jd-lara** [jump-dev/JuMP.jl#2649]
It seems that models with ParameterJuMP parameters fail to copy and throw an error. Looks like a missing method error. 

```julia
julia> new_model, reference_map = JuMP.copy_conflict(HAUC.internal.optimization_container.JuMPmodel)
ERROR: MethodError: no method matching copy_extension_data(::ParameterJuMP._ParameterData, ::JuMP.Model, ::JuMP.Model)
Stacktrace:
 [1] copy_model(model::JuMP.Model; filter_constraints::JuMP.var"#76#77"{JuMP.Model})
   @ JuMP ~/.julia/packages/JuMP/Xrr7O/src/copy.jl:171
 [2] copy_conflict(model::JuMP.Model)
   @ JuMP ~/.julia/packages/JuMP/Xrr7O/src/copy.jl:257
 [3] top-level scope
   @ REPL[19]:1
```

**Comment by odow** [comment]
I don't think copying a model with parameters is going to work.

ParameterJuMP would need to implement
 https://github.com/jump-dev/JuMP.jl/blob/6901e8f98bf24242a141e003e42530fa90f33c3c/src/copy.jl#L6-L13

However, we should have some fallback so this doesn't error:

```julia
copy_extension_data(data, new_model, model) = missing
```

**Comment by jd-lara** [comment]
@odow FWIW I wasn't actually trying to copy the model, just playing with the conflict features to debug a model.

**Comment by odow** [comment]
Copying the conflict is just copying a subset of the model, so it goes through the same system. 

As a work-around, just add this to your script:
```julia
JuMP.copy_extension_data(::Any, ::Any, ::Any) = missing
```
