### ISSUE TITLE
Defining a problem when an analytical expression exists for the Jacobian

### ISSUE THREAD

**Issue by Peter-Jolly** [jump-dev/JuMP.jl#2670]
I am presently using JuMP successfully to solve a 2D non-linear optimization problem, subject to several constraints. The problem is solved multiple time within one program run. In an effort to speed things up I am wondering if there is a way of defining the problem with an analytical expression for the Jacobian? I have checked the current documentation, but cannot find an example. Can someone let me know if this can be done and perhaps supply a simple example. I love the package. Thanks Peter

**Comment by odow** [comment]
You can register analytic first-order derivatives with user-defined function:
https://jump.dev/JuMP.jl/stable/manual/nlp/#User-defined-Functions
But you're probably better off avoiding user-defined functions and letting JuMP automatically compute first- and second-order derivatives.

If you're solving the same problem multiple times with slightly different data, try using `@NLparameter`:
 https://jump.dev/JuMP.jl/stable/manual/nlp/#Create-a-nonlinear-parameter

You might also consider creating a reproducible example and posting on the community forum: https://discourse.julialang.org/c/domain/opt/13. People may have ideas to speed things up.

If JuMP is too heavy, there alternatives in the Julia world, such as https://mohamed82008.github.io/Nonconvex.jl/stable/.

**Comment by Peter-Jolly** [comment]
Thank your very much for all this VERY useful information - I am digesting it all. I have many options to try in due course. I am not stuck at present, just working my way through the examples and thinking about the best way to move forward. Thanks Peter
