### ISSUE TITLE
Extend Raw NLP Expr Input to Allow AffExprs and QuadExprs

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#2671]
Thanks to #2559 the NLP macros now support `AffExpr`s and `QuadExpr`s. However, this is not the case for the `set_NL_objective` and `add_NL_constaint` API. Adding this capability looks like it would be a simple matter of extending `_Derivatives.expr_to_nodedata` in like manner to what was done with `_parse_NL_expr_runtime` in #2559. If this sounds reasonable, I would be happy to make a pull request.

I am working on supporting NLP with InfiniteOpt.jl and for efficiency my expression structure allows `AffExpr`s and `QuadExpr`s to be stored directly. Thus, being able to insert them directly into a raw expression that JuMP can interpret would be convenient and more efficient that feeding a sum.

**Comment by odow** [comment]
I haven't looked at the details, but yes, go ahead.
