### ISSUE TITLE
Implement owner_model for expressions

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2678]
Request from discourse: https://discourse.julialang.org/t/how-to-view-which-model-the-variable-belongs-to/67233
```julia
owner_model(::GenericAffExpr)
owner_model(::GenericQuadExpr)
```
A test would be something like
```Julia
function test_owner_model_expression()
    model_1 = Model()
    @variable(model_1, x_1)
    model_2 = Model()
    @variable(model_2, x_2)
    @test owner_model(x_1 + x_1) === model_1
    @test owner_model(x_1 + x_1) !== model_2
    @test owner_model(x_2 * x_2) === model_2
    @test owner_model(x_2 * x_2) !== model_1
    @test owner_model(0 * x_1^2 + x_1) === model_1
    @test owner_model(0 * x_1^2 + x_1) !== model_2
    return
end
```

**Comment by mlubin** [comment]
What would be the behavior of `owner_model` when the expression contains variables from multiple models?

**Comment by odow** [comment]
Shouldn't we make that an error? Are there any use-cases where you would want to build an expression with variables from different models?

**Comment by mlubin** [comment]
> Are there any use-cases where you would want to build an expression with variables from different models?

StructJuMP did this, IIRC

> Shouldn't we make that an error?

Do you mean an error from `owner_model` or an error when constructing the expression? The former seems fine.

**Comment by mlubin** [comment]
One reason not to implement `owner_model` is that it needs to be O(n) to check for consistency, which is likely surprising to users.

**Comment by odow** [comment]
> is that it needs to be O(n) to check for consistency

That's reasonable. 

I'll close this issue for now. 

For future readers: if you want this feature, please leave a comment below. If there's enough interest, we may reconsider it.

As a work-around before then, you can use the following:
```julia
my_owner_model(x::AffExpr) = JuMP.owner_model(first(x.terms)[2])

function my_owner_model(x::QuadExpr)
    if length(x.aff.terms) > 0
        return my_owner_model(x.aff)
    end
    return JuMP.owner_model(first(x.terms)[1].a)
end
```
