### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by chelseas** [jump-dev/JuMP.jl#2715]
Is there a way to clear the objective? And turn a max or min problem into a feasibility problem? I know I can overwrite the objective with something like 
```jl
@objective(model, Min, 0)
```
But does Gurobi see it as a feasibility problem in the same way? Or does it try to "optimize" 0 ?

Computational cost is important to me here.

**Comment by odow** [comment]
I'm going to close this since there isn't anything actionable on the JuMP.jl front. Please post on the forum if you'd like to discuss further.
