### ISSUE TITLE
Add get/set_variable/constraint_attribute

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/JuMP.jl#2770]
There are `get/set_optimizer_attribute` which has `MOI.AbstractOptimizerAttribute` as parameter. To be consistent we should add the variable/constraint method or remove the optimizer_attribute that has the MOI parameter and simply use `MOI.get/set`.

**Comment by odow** [comment]
We're going to leave this as `set_optimizer_attribute` for now.
