### ISSUE TITLE
define Base.isempty or is_empty for JuMP models

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/JuMP.jl#2810]
When passing a model as argument to solve a problem in-place, it would be handy to know if a model is empty or not, thus to implement MOI.is_empty for JuMP models or define a JuMP function if a different meaning must be attached.

Itt could make sense to have:
`MOI.is_empty(model)` <=> model is empty (some optimizer attributes can have been set)
`JuMP.is_empty(model)` <=> model is empty and no attribute has been set. Open question is whether the optimizer itself should be absent

**Comment by matbesancon** [comment]
I also suggested Base.isempty but this would be inconsistent with the rest of the MOI/JuMP redefinitions of functions when the sense given by the Base one is different

**Comment by matbesancon** [comment]
I'd be happy to open a PR but since this is mostly a design decision I wanted to get opinions

**Comment by odow** [comment]
We define `Base.empty!`, so `Base.isempty` seems consistent:
https://github.com/jump-dev/JuMP.jl/blob/ded934743b307e6d034d6f26a0d3a442a29fe9ef/src/JuMP.jl#L645-L670
