### ISSUE TITLE
Make plural macros (e.g. @variables) return collections of the defined objects

### ISSUE THREAD

**Issue by MartinBonde** [jump-dev/JuMP.jl#2837]
When working on a large model it is extremely useful to be able to manipulate large groups of variables or constraints.

To avoid repeating long lists of variable names or equations, it would be very useful if the the ‘plural macros’ (e.g. @variables and @constraints), returned collections of the newly defined objects.

For example I would like for

```
vars = @variables model begin
  x
  y[1:2]
end
```

to be equivalent to writing

```
@variables model begin
  x
  y[1:2]
end
vars = [x, y]
```
and

```
eqs = @NLconstraints model begin
  E_x, x == 1
  E_y[i ∈ 1:2], y[i] == x
end
```
should be equivalent to writing

```
@NLconstraints model begin
  E_x, x == 1
  E_y[i ∈ 1:2], y[i] == x
end
eqs = [E_x, E_y]
```

Note that this is not just a matter of laziness, but that repeating long lists of items is prone to hard-to-debug errors. I.e. spotting which item is missing in a large collection of variables or constraints can take a long time.

**Comment by odow** [comment]
Discussed on discourse: https://discourse.julialang.org/t/plural-macros-e-g-variables-should-return-collection-of-the-defined-objects/73397

I think this is a reasonable suggestion.

Currently the macros return `nothing`, so I think this is just a non-breaking feature addition. I can't think of a reason that someone would rely on `@variables` returning `nothing`.

**Comment by MartinBonde** [comment]
I read through the metaprogamming docs and as expected it is a m

**Comment by odow** [comment]
Yes, something like this would be sufficient. Please make a pull request and we can work out the details. 

We'll also need to add some new tests and update the documentation, but we can point you in the right direction once there is an open pull request.
