### ISSUE TITLE
Typo in RotatedSecondOrderCone docstring

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2855]
Hi! I have a comment on the ambiguity in the docstring for [RotatedSecondOrderCone()](https://jump.dev/JuMP.jl/stable/reference/constraints/#JuMP.RotatedSecondOrderCone) on whether we are taking the 2-norm or squared 2-norm of the vector. The docstring describes it as "the square of the euclidean norm of a vector" while the mathematical formula in the example shows ∥(x−1,x−2)∥_2 ≤ 2tx.

_Originally posted by @sean-lo in https://github.com/jump-dev/JuMP.jl/issues/2487#issuecomment-1013786993_

**Comment by odow** [comment]
@Sean-lo want to make a pull request?

The docstring is here:
https://github.com/jump-dev/JuMP.jl/blob/5970e5d09aaddb18b8ab7bf935bf2bebb738764a/src/sets.jl#L145-L168

You can click the pencil in the top-right to edit the file online:
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/8177701/150658689-c132e725-1001-464c-a55c-a8b4a5c5e698.png">

**Comment by sean-lo** [comment]
Thanks Oscar, I've made the pull request.
