### ISSUE TITLE
Slicing DenseAxisArrays

### ISSUE THREAD

**Issue by IainNZ** [jump-dev/JuMP.jl#287]
```
m = Model()
@defVar(m, x[0:5], Bin)
solve(m)
getValue(x[0])  # Works
getValue(x[0:2])
#BoundsError()
#while loading In[15], in expression starting on line 1
#
# in copy! at array.jl:52
# in getindex at array.jl:265
# in getindex at no file
```

**Comment by joehuchette** [comment]
Looks like colon isn't desugared at parse time anymore (?):
```julia
julia> dump(:(a[1,:]))
Expr
  head: Symbol ref
  args: Array(Any,(3,))
    1: Symbol a
    2: Int64 1
    3: Symbol :
  typ: Any
```

**Comment by mlubin** [comment]
This has always been a compile-time transformation.

**Comment by mlubin** [comment]
The remaining issue, if any, is:
```julia
julia> m = Model();

julia> @variable(m, x[0:5]);

julia> x[0:2]
ERROR: KeyError: key 0:2 not found
```

**Comment by rapus95** [comment]
Are there any news on this? Why is slicing not supported in the first place?

**Comment by odow** [comment]
We're likely missing an appropriate `getindex` method. I don't think anyone has looked in detail about this recently.

**Comment by mlubin** [comment]
AxisArrays has this functionality in some form. You may be interested in https://github.com/rdeits/AxisArrayVariables.jl (which would need to be updated for the latest JuMP).

**Comment by rapus95** [comment]
How about sneakily passing it through?
```julia
JuMP.Containers.lookup_index(i, lookup::Dict) = isa(i, Colon) ? Colon() : isa(i, AbstractRange) ? i : lookup[i]
```

**Comment by mlubin** [comment]
What's the interpretation of indexing by 5:7 when the index set is 1:2:9? "passing it through" would be the equivalent of `collect(1:2:9)[5:7]`.

See the discussion at https://github.com/JuliaArrays/AxisArrays.jl/issues/84 for more context.

**Comment by rapus95** [comment]
Better: if T::AbstractUnitRange then just pass through

**Comment by mlubin** [comment]
`collect(5:7)[5:7]` also yields a BoundsError.

**Comment by rapus95** [comment]
Is there any (dirty) workaround for making that
```julia
@variable(m, x[1:DN,1:DN,1:NTC,-36:T,1:NivelesC] >= 0, Int)
[constraints]
[optimize!]
JuMP.value.(x)[:, :, :, 3:40,:]
```
working easily?

**Comment by NLaws** [comment]
+1 on this issue
