### ISSUE TITLE
Rename nl_ functions to nonlinear_

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#2882]
These three functions are inconsistent in how we name nonlinear things:
https://github.com/jump-dev/JuMP.jl/blob/2670540c5b497eb54dc8ecb8c6630668a632ef45/src/nlp.jl#L2038
https://github.com/jump-dev/JuMP.jl/blob/2670540c5b497eb54dc8ecb8c6630668a632ef45/src/nlp.jl#L2062
https://github.com/jump-dev/JuMP.jl/blob/2670540c5b497eb54dc8ecb8c6630668a632ef45/src/nlp.jl#L2085

x-ref: https://github.com/jump-dev/JuMP.jl/pull/2879#issuecomment-1046390000

**Comment by mlubin** [comment]
https://github.com/jump-dev/JuMP.jl/pull/2879#issuecomment-1046397139
