### ISSUE TITLE
It could be helpful to have the `MOI.RelativeGap(model)` reported in the `solution_summary`

### ISSUE THREAD

**Issue by hdavid16** [jump-dev/JuMP.jl#2906]
I understand that this only makes sense if there are discrete variables. However, it's an important parameter to have when solving discrete optimization problems.

**Comment by odow** [comment]
PRs accepted. It's a good intro issue for someone interested.

Code to modify is here:
https://github.com/jump-dev/JuMP.jl/blob/master/src/solution_summary.jl

Tests to update are here:
https://github.com/jump-dev/JuMP.jl/blob/master/test/solution_summary.jl

Docs to update are here:
https://github.com/jump-dev/JuMP.jl/blob/master/docs/src/manual/solutions.md

**Comment by hdavid16** [comment]
Thanks for taking care of this @odow. I never got around to it.
