### ISSUE TITLE
callback_value doesn't work if nonlinear constraint present

### ISSUE THREAD

**Issue by a6a3uh** [jump-dev/JuMP.jl#2908]
If nonlinear constraint is present callback_value returns initial condition for decision variable always.

Here code sample to reproduce
```
using JuMP, Ipopt

model = Model(Ipopt.Optimizer)
set_silent(model)

@variable(model, 0 <= x <= 1, start = 0.1)
@objective(model, Min, x^2)

# @NLconstraint(model, x^3 >= 0)

function callback(args...)
    println(callback_value(model, x))
    return true
end

MOI.set(model, Ipopt.CallbackFunction(), callback)

optimize!(model)
```
It prints decision variable value at each step

But if you uncomment NLconstraint it will print always only initial value. But problem still get solved though.

I'm not sure if this is not Ipopt.jl specific issue. I've reported [there](https://github.com/jump-dev/Ipopt.jl/issues/308) as well with not much reaction yet. But since callback functionality is defined at the JuMP library level probably reporting it here is a better option.

**Comment by odow** [comment]
Closing in favor of https://github.com/jump-dev/Ipopt.jl/issues/308. I didn't get a chance to look at it yet.
