### ISSUE TITLE
Consolidating logos and branding

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#2920]
Thanks to https://github.com/jump-dev/JuMP.jl/pull/2584 we have a "modern" Julia-inspired JuMP logo. We still have some traces of old logos and branding that should be updated:

- [x] https://numfocus.org/project/jump [Emailed NF]
- [x] NumFOCUS JuMP drive (not public) [Emailed NF]
- [x] https://twitter.com/jumpjl
- [x] JuMP.jl GitHub "social preview"
- [X] https://www.gurobi.com/resource/add-ons/ (JuliaOpt!) [Sent email to Gurobi]

Is https://github.com/jump-dev/JuMP.jl/tree/master/docs/src/assets the canonical source of the new logos?
Do we have a version without the "JuMP" text? (Needed for NumFOCUS and Twitter)

@cormullion

**Comment by joaquimg** [comment]
The github logo is also a no text logo.

**Comment by mlubin** [comment]
> The github logo is also a no text logo.

I see the JuMP-dev org has a "new" no-text logo, but not in a vector format. How was it generated?

**Comment by cormullion** [comment]
This gist is the source - all you need is Julia.😀

**Comment by mlubin** [comment]
Thanks, @cormullion. The script is helpful but it doesn't exactly reproduce [logo-with-text.svg](https://github.com/jump-dev/JuMP.jl/blob/master/docs/src/assets/logo-with-text.svg).

Current logo:


![image](https://user-images.githubusercontent.com/1733683/158032931-c8abb774-2553-4663-a4d3-9343e34ed1f7.png)


Generated by https://gist.github.com/cormullion/42977b9bca4c7d08a6455865297c6d9e:

![image](https://user-images.githubusercontent.com/1733683/158032911-6d2313a1-fedd-40f5-be1b-db098cf5d0c5.png)

Differences I see are:
- Thickness of the line segments ("chopsticks") around the circles
- Different black for the text and line segments
- Size of the canvas and centering

The first two differences are most important in keeping the logo consistent.

Peeking into the svg, the code generating the line segments is different:
Current logo:
```
<path d="M41 75.5l100-40M25 127.5l116-116" fill="none" stroke-width="8" stroke-linecap="round" stroke="#333" stroke-miterlimit="10"/>
```

Generated by the gist:
```
<path style="fill:none;stroke-width:12;stroke-linecap:round;stroke-linejoin:miter;stroke:rgb(0%,0%,0%);stroke-opacity:1;stroke-miterlimit:10;" d="M 20 68 L 120 28 "/>
<path style="fill:none;stroke-width:12;stroke-linecap:round;stroke-linejoin:miter;stroke:rgb(0%,0%,0%);stroke-opacity:1;stroke-miterlimit:10;" d="M 4 120 L 120 4 "/>
```

**Comment by cormullion** [comment]
Yes, I think @odow did some tweaking by hand. https://github.com/jump-dev/JuMP.jl/pull/2596/files

**Comment by odow** [comment]
I think the only tweaking I did was to add the background, but let me take a look.

**Comment by odow** [comment]
Okay, take a look at https://github.com/jump-dev/JuMP.jl/pull/2924

We have, in light and dark:
 * logo no text
 * logo with text below
 * logo with text beside
 * logo with text beside and background

These now all use the same script, so they are identical. There's a few quibbles to be had on the margins/offsets which we can refine.

**Comment by odow** [comment]
Here are three pngs:

| with-text | square-with-text | square-without-text |
| ---- | ---- | ---- |
| ![][-with-text] | ![][-square-with-text] | ![][-square] |

[-square-with-text]: https://user-images.githubusercontent.com/8177701/158288499-4172847c-2431-4573-be66-7a0f6bf6a68e.png
[-with-text]: https://user-images.githubusercontent.com/8177701/158288504-1c4273a1-80d3-4cc5-aa6a-6d10928cc6e2.png
[-square]: https://user-images.githubusercontent.com/8177701/158288507-df1cc665-b91a-4b4b-8686-5521df09135f.png

**Comment by odow** [comment]
Updated the social preview and uploaded the pngs to the NumFOCUS drive, but I don't have permission to move files to re-organize it.

I also don't have access to the twitter account.

**Comment by joaquimg** [comment]
We need more borders for twitter because it will on consider a circle inside the square

**Comment by odow** [comment]
How's this:
![Screen Shot 2022-03-15 at 3 42 53 PM](https://user-images.githubusercontent.com/8177701/158295365-35951352-22d0-42db-a458-a203cd5cd7df.png)

**Comment by joaquimg** [comment]
perfect! Twitter updated

**Comment by odow** [comment]
Can we update the JuliaOpt link in the bio?

**Comment by joaquimg** [comment]
done

**Comment by mlubin** [comment]
I contacted NumFOCUS to update on their side, so all the work items for us are done on this issue.
