### ISSUE TITLE
MOIPajarito

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#2927]
We could get rid of this section now that we have https://github.com/chriscoey/MOIPajarito.jl/ which would be nice for JuMP v1.0
https://github.com/jump-dev/JuMP.jl/blob/5e79e0b02c49c379e1ddf4d2317a668b3157e9e4/docs/src/installation.md#L197-L206

@chriscoey Is it ready for prime time ?

**Comment by chriscoey** [comment]
Yes, I think it's stable enough. I will do more development after I graduate in May (uhh fingers crossed). I don't have much time before then though.

**Comment by odow** [comment]
We should probably just graft the MOIPajarito repository onto the old JuliaOpt/Pajarito and then move it to jump-dev/Pajarito.jl? 

The name is already registered, so we don't want to register MOIPajarito.

**Comment by odow** [comment]
I'll remove this paragraph. We can always add Pajarito to the table in a future release. https://github.com/jump-dev/JuMP.jl/pull/2928

**Comment by chriscoey** [comment]
I was thinking we would rename pajarito to like mathprogbasepajarito and rename MOIPajarito to pajarito and move it into jump-dev. In any case let's leave that until early May when I have more time.

**Comment by odow** [comment]
I did this for PATH: https://github.com/chkwon/PATHSolver.jl/pull/44. 

You can graft on the commits so everything stays in the same repo. Then you have the new code and in the commit history there is the old code.

**Comment by odow** [comment]
Okay I've removed the paragraph. We can add Pajarito to the table once it's registered again, but I don't think this needs to block JuMP 1.0.

**Comment by odow** [comment]
Closing because there isn't anything actionable to do here.
