### ISSUE TITLE
TagBot didn't automatically create the 1.0.0 tag

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#2933]
I manually triggered the TagBot workflow and it worked as expected, creating the 1.0.0 tag. Not sure why it didn't automatically trigger.

**Comment by pulsipher** [comment]
I ran into the same problem when releasing InfiniteOpt v0.5.3. I had to invoke TagBot manually.

**Comment by odow** [comment]
Given that it happened to a few repos, I guess this was an upstream GitHub actions outage?

**Comment by odow** [comment]
TagBot has been working for other repos, https://github.com/jump-dev/AmplNLWriter.jl/releases/tag/v1.0.0, so I'm going to close this as non-reproducible. We can re-open if it happens again.
