### ISSUE TITLE
Couple JuMP with the simulator

### ISSUE THREAD

**Issue by jacktang** [jump-dev/JuMP.jl#2979]
Hi

I am working on a project about multi-reservoir control optimization problem and the objective function is calculated by Telemac simulator. Do you have some examples or best practices for such integration? I have read some JuMP examples and the objective function is written in expressions. Can I pass one function to @objective macro and can I get all variables in the function?

Thanks!

**Comment by odow** [comment]
Let's keep the discussion on the community forum: https://discourse.julialang.org/t/couple-jump-with-the-simulator/80792
