### ISSUE TITLE
Include the Docstring for `set_optimizer_hook` in the Docs

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#2981]
The method `set_optimizer_hook` has a docstring, but it is not included in the documentation: 
https://github.com/jump-dev/JuMP.jl/blob/9ea1df38fd320f864ab4c93c78631d0f15939c0b/src/JuMP.jl#L718-L745

This would be a useful resource for extension developers.

**Comment by odow** [comment]
Ooops. I'll do this now unless you're currently working on it?

**Comment by pulsipher** [comment]
Go for it, thanks!
