### ISSUE TITLE
Discussion/style guide updates on abstraction/correctness/composability

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMP.jl#2988]
https://yuri.is/not-julia/ and the corresponding [HN discussion](https://news.ycombinator.com/item?id=31396861) is worth a read. Overall I think JuMP is already doing quite well with respect to the cultural issues raised (none of the bugs involved JuMP); however, JuMP is part of the Julia community so we should reflect on what we can do to improve. 

IMO the post claims the following issues in the Julia ecosystem:
- Code tends to not document assumptions on abstract types (assuming AbstractArrays are 1-based)
- Undocumented assumptions are not checked (e.g., [`copyto!` and aliasing](https://github.com/JuliaLang/julia/issues/39460))
- Composition of packages is untested (e.g., OffsetArrays and Distributions)

JuMP's style guide doesn't really discuss these issues, except for user-facing method errors (which are a result of unchecked assumptions on abstract types).

**Comment by odow** [comment]
We should discuss this on Thursday's call. 

> Overall I think JuMP is already doing quite well with respect to the cultural issues raised

Agreed. 

> IMO the post claims the following issues in the Julia ecosystem

Other things I would add:

  * AD packages are particularly brittle. Which is an argument for MOI.Nonlinear to take a much narrower focus
  * Trade-off between ["Annotations for function definitions should be as general as possible."](https://github.com/SciML/SciMLStyle#function-type-annotations) and testing. JuMP is at one end  of the spectrum (often only supports `Vector{Float64}`).
