### ISSUE TITLE
all_constraints(model)

### ISSUE THREAD

**Issue by oxinabox** [jump-dev/JuMP.jl#3001]
**Is your feature request related to a problem? Please describe.**
I wish to list all constraints so i can then check all `shadow_prices` so I can find which as nonzero to determine which constraints are binding.
I have also wanted to list all constraints for check feasibility of a potential primal solution in the past, but that is now a inbuilt feature of JuMP so i don't need to.

**Describe the solution you'd like**
define 
```julia
all_constraints(model) = mapreduce((f,s)->all_constraints(model, f,s), vcat, list_of_constraint_types(model))
```
in JuMP and export it

**Describe alternatives you've considered**
Not doing this, and making the user do this

**Comment by odow** [comment]
The main problem is that this will also include some variable bound constraints.

I guess we have a precedent:
https://github.com/jump-dev/JuMP.jl/blob/dc4a786cfda3f364e79b261853ef59907ebbdcba/src/constraints.jl#L1248-L1282

**Comment by joaquimg** [comment]
> check all shadow_prices so I can find which as nonzero to determine which constraints are binding.

Just be careful, because in degenerate situations you might have binding constraints with zero shadow price.
Depending on what you want you might need to check the value of the constraints lhs and rhs.
