### ISSUE TITLE
read! is not implemented for LP files.

### ISSUE THREAD

**Issue by freiburgermsu** [jump-dev/JuMP.jl#3003]
Hello!

I receive the attached error
![cannot read LP files](https://user-images.githubusercontent.com/60083977/173096573-067086a1-c090-4292-aefd-bea431e8b71f.JPG)
when I execute this code
```julia
import GLPK, JuMP, MathOptInterface
function execute_cobra(model_path)
    model = JuMP.read_from_file(model_path) #, MathOptInterface.FileFormats.FORMAT_LP)    
    JuMP.set_optimizer(model, GLPK.Optimizer)
    return JuMP.optimize!(model)
end
print(execute_cobra("test.lp"))
```
[This discourse post](https://discourse.julialang.org/t/read-lp-file-into-jump-model-in-direct-mode/81803/2) suggests that LP files can indeed be imported, yet the error conveys that LP files cannot be imported. Is there an error in my code or installation?

Thank you :)

**Comment by odow** [comment]
Please update your packages. You must have an old version of MathOptInterface installed. 

If you still need help, please post on the community forum, https://discourse.julialang.org/c/domain/opt/13, but I assume it's related to https://github.com/jump-dev/GLPK.jl/issues/217 and COBRA, which forced you to install old versions of GLPK.jl and MathOptInterface.jl.

**Comment by freiburgermsu** [comment]
Hello @odow ,

I updated my packages in the Julia REPL via ``Pkg.update()`` and restarted by Jupyter kernel, however, the same error is observed. Must packages be updated via another channel?

I will post to the JuMP forum.

Thank you so much :)

**Comment by odow** [comment]
Can you post on the forum with a reproducible example?
