### ISSUE TITLE
[docs] Clarify `String` singleton as an iterable object for `@variable`

### ISSUE THREAD

**Issue by jd-foster** [jump-dev/JuMP.jl#3042]
See: https://discourse.julialang.org/t/jump-variable/85853

This seems like it shouldn't happen from a user perspective without at least a warning.

**Comment by mlubin** [comment]
This would be a breaking change, not sure it's worth it. At some level we have to deal with Julia's rules for which objects are iterable.

**Comment by odow** [comment]
Agree that it's a bit unexpected, but it follows the rules of iterable objects (it's also why `1` is a valid index, because you can iterate integers).

So it would be breaking and somewhat arbitrary to special-case `String` but not other singletons that are iterable.

**Comment by jd-foster** [comment]
Makes sense. This seems like it could be addressed in documentation in "[Getting started with sets and indexing](https://jump.dev/JuMP.jl/dev/tutorials/getting_started/getting_started_with_sets_and_indexing/#Getting-started-with-sets-and-indexing)"

**Comment by odow** [comment]
Okay, I'll take a pass.
