### ISSUE TITLE
record software license more prominently in documentation

### ISSUE THREAD

**Issue by robbiemorrison** [jump-dev/JuMP.jl#3055]
In the **online documentation** at https://jump.dev/JuMP.jl/stable/, it might help to have the **MPL‑2.0 software license** stated more prominently.  There is a reference to an alteration of the license type in the change log, but that information is not necessary current.  This is a&nbsp;suggestion only.

**Comment by odow** [comment]
The license is https://github.com/jump-dev/JuMP.jl/blob/master/LICENSE.md

It's also in all of the files: https://github.com/jump-dev/JuMP.jl/blob/547895c44ec35bfdf68e961a14310d6cc68aa994/src/JuMP.jl#L1-L4

I guess we could add a paragraph to the bottom of the introduction page?

How about something like:
```
## License

JuMP is licensed under the [MPL-2.0 software license](https://mozilla.org/MPL/2.0/).
At a high level, this means you are free to use JuMP in any situation, including
in commercial products, but there are some restrictions if you modify the JuMP
source code. Consult the [license](https://github.com/jump-dev/JuMP.jl/blob/master/LICENSE.md)
and the [Mozilla FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) for more
information.
```

**Comment by robbiemorrison** [comment]
The approach looks good to me.  And I note that some of the obligations that the MPL-2.0 requires do not apply to JuMP because JuMP is never compiled and potentially distributed in just binary form (if I am not mistaken).  Just one small remark to consider: I&nbsp;would omit ~~At a high level~~ (or be more specific).

**Comment by mlubin** [comment]
I'd drop the full sentence, "At a high level, this means you are free to use JuMP in any situation, including in commercial products, but there are some restrictions if you modify the JuMP source code." It's safer not to offer commentary on the license.

> JuMP is never compiled and potentially distributed in just binary form (if I am not mistaken)

Julia code can be compiled and distributed, although it's rare and technically complicated.

**Comment by robbiemorrison** [comment]
I participate in the Free Software Foundation Europe (FSFE) Legal Network (LN) community since 2017.  And I see many discussions about the merits, attributes, weaknesses, and coverage of software licenses.  And I agree that there is no need to offer an interpretation in this context.
