### ISSUE TITLE
Request for the capability to obtain the start value of the NLexpressions

### ISSUE THREAD

**Issue by KennethAnn** [jump-dev/JuMP.jl#3067]
1. The problem and necessity

I am using JuMP to develop a computable general equilibrium model which is important for climate change economic studies. In general, the CGE model is developed by the GAMS but is not open-source, since the PATH solver is not freely accessible. 

JuMP maybe an useful tool to build the open-source CGE model because of its packages: PATHSolver.jl and Complementarity.jl. However, I feel that those packages are still not perfect to build the model. One necessary function is to evaluate whether the nonlinear equations are balanced in the initial value of variables. So it would be quite useful to have an API to **directly obtain the initial value of the @NLexpression.**

2. Possible solution
Currently, I found an API named **JuMP.start_value()**, which could obtain the initial value of the variables. So I am asking for help to extend the function of this API to obtain the initial value of expressions. This function seems to be easy to handle: **1. initializing the value of variables in the expression, 2. calculating the initial value of expression, 3. return the value.** 

This is one expression printed out: subexpression[58]: ff[16] * pff[16] ^ 0.3 - 0.0 * prod[16] * pprod[16] ^ 0.

If it is possible, when I code **start_value(expr_name)**, I can obtain the value of the expression.

Thanks for your help!

**Comment by odow** [comment]
Use this method:
https://github.com/jump-dev/JuMP.jl/blob/59926a993a126444c48bf9a212e986679ca4b2fe/src/nlp.jl#L358-L363

```Julia
julia> using JuMP

julia> model = Model();

julia> @variable(model, x, start = 0.5);

julia> @NLexpression(model, expr, sin(x)^2);

julia> sin(start_value(x))^2
0.22984884706593015

julia> value(start_value, expr)
0.22984884706593015
```

**Comment by KennethAnn** [comment]
Thanks for your excellent JuMP package, I have almost finished a version of CGE model which is stable and good to use. However, I find another problem which I cannot solve by reading the manual. 

If there are any similar function to dynamically activate or deactivate the @NLexpression or other components? In Pyomo, the model use activate() and deactivate() to point to one of some constraints or objectives, such as 

```
model = pyo.ConcreteModel()
model.obj1 = pyo.Objective(expr = 0)
model.obj2 = pyo.Objective(expr = 0)
model.obj1.deactivate()
model.obj2.activate()
```

How to achieve this modeling target in JuMP? I prefer a tool for NLexpression. Thanks a lot!

**Comment by odow** [comment]
JuMP doesn't have the concept of activate and deactivate. To set a new objective, just make another call to `@NLobjective`.
