### ISSUE TITLE
`@NLconstraint` names

### ISSUE THREAD

**Issue by hdavid16** [jump-dev/JuMP.jl#3069]
It's great to see that names (with indexing) can now be assigned to nonlinear constraints. The following features would be nice to have:

- [ ] extend the `@NLconstraint` macro to allow the `base_name` kwarg as is the case in `@constraint`.
- [ ] extend `JuMP.name` to allow accessing the name of the nonlinear constraint.
- [ ] extend `JuMP.set_name` for nonlinear constraints.

**Comment by odow** [comment]
This is related to the MOI Nonlinear redesign. At the moment, nonlinear constraints don't exist as first-class objects, so they don't support the `MOI.ConstraintName` attribute, and therefore JuMP can't set their `name`.

So implementing this would first require https://github.com/jump-dev/MathOptInterface.jl/issues/846

**Comment by odow** [comment]
I'm going to close this as won't-fix for now. Nonlinear constraints don't have names. If/when we update MOI to have first-class nonlinear constraints, this is something that will happen naturally.

**Comment by hdavid16** [comment]
They do appear to have names now...

```julia
using JuMP
m=Model()
@variable(m,x);
@NLconstraint(m, constraint_1, exp(x) <= 1)
#exp(x) - 1.0 <= 0
m[:constraint_1]
#exp(x) - 1.0 <= 0
```

**Comment by odow** [comment]
They have a symbolic identifier, but not a `MOI.ConstraintName`. The distinction is somewhat subtle:
https://jump.dev/JuMP.jl/stable/manual/constraints/#String-names,-symbolic-names,-and-bindings

`JuMP.name` is syntactic sugar for get/set of `MOI.ConstraintName`. There is no mechanism in JuMP or MOI for nonlinear constraints to store a `String` as the constraint, and you cannot look up a nonlinear constraint by a `String` name.

I think what you're asking for in DisjunctiveProgramming is a way to look up if a constraint has been stored in the `object_dictionary`, but that is orthogonal to the name discussion.

**Comment by hdavid16** [comment]
ok. makes sense. Thanks for clarifying.
