### ISSUE TITLE
`unregister` option in `delete`

### ISSUE THREAD

**Issue by hdavid16** [jump-dev/JuMP.jl#3070]
It would be nice to have an optional keyword argument in `delete` that will call `unregister` if `unregister = true` (default would be `false`). This would avoid having to manually unregister after deleting an object from the model.

This also avoids breaking `object_dictionary` when deleting.

**Comment by odow** [comment]
See the backstory in https://github.com/jump-dev/JuMP.jl/pull/2417, https://github.com/jump-dev/JuMP.jl/pull/2232, https://github.com/jump-dev/JuMP.jl/issues/2589#issuecomment-837270325, https://github.com/jump-dev/JuMP.jl/pull/2601

We opted for explicit calls to both `delete` and `unregister`: https://github.com/jump-dev/JuMP.jl/pull/2232#discussion_r496189346.

One issue with the keyword is that we don't have a way to lookup the symbol from the variable, and if you delete an element of a vector, `unregister = true` wouldn't be meaningful.

**Comment by hdavid16** [comment]
ahh ok.
