### ISSUE TITLE
`relax_integrality` takes really long for large problems even if there aren't that many integer variables

### ISSUE THREAD

**Issue by raphaelsaavedra** [jump-dev/JuMP.jl#3086]
Example:

```
julia> model
A JuMP Model
Minimization problem with:
Variables: 1193206
Objective function type: AffExpr
`AffExpr`-in-`MathOptInterface.EqualTo{Float64}`: 399576 constraints
`AffExpr`-in-`MathOptInterface.GreaterThan{Float64}`: 43031 constraints
`AffExpr`-in-`MathOptInterface.LessThan{Float64}`: 904612 constraints
`VariableRef`-in-`MathOptInterface.GreaterThan{Float64}`: 1144294 constraints
`VariableRef`-in-`MathOptInterface.LessThan{Float64}`: 48912 constraints
`VariableRef`-in-`MathOptInterface.ZeroOne`: 48912 constraints
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @time JuMP.relax_integrality(model)
 44.611944 seconds (33.02 M allocations: 1.550 GiB, 1.33% gc time, 0.82% compilation time)
```

Note that although the problem is large (>1m constraints and >2.5m constraints), there are just around 50k binaries.
I suspect the reason for the poor performance is that in [relax_integrality](https://github.com/jump-dev/JuMP.jl/blob/08dae8502aa01fd22e965a31cbe2fbcc1804bc77/src/variables.jl#L1421) we iterate over `all_variables(model)`.
Not sure if there's a straightforward improvement that still provides informative error messages, but my guess is that iterating over just the integer/binary ones would reduce this runtime.

**Comment by odow** [comment]
Updating the function to loop over `all_constraints(model, VariableRef, MOI.ZeroOne)` etc would make a nice PR.

**Comment by raphaelsaavedra** [comment]
I'm looking into that. Changing the first loop is easy enough. However, it seems that the big offender here is 
```julia
info_pre_relaxation = map(v -> (v, _info_from_variable(v)), all_variables(model))
```
which takes nearly 100% of the runtime. Would be great if we could map only over the variables that are binary or integer, however it seems we need `_info_from_variable` to actually check that.

Is it possible to get from a `ZeroOne` / `Integer` constraint to the variable over which it is applied? If so, we could get from

```julia
bin_int_constraints = vcat(
    all_constraints(model, VariableRef, MOI.ZeroOne),
    all_constraints(model, VariableRef, MOI.Integer),
)
```

to only those variables without having to iterate over all variables.

 I'm open to suggestions.

**Comment by odow** [comment]
> Is it possible to get from a ZeroOne / Integer constraint to the variable over which it is applied?

Yes. Use `VariableRef(::ConstraintRef)`
```julia
julia> model = Model();

julia> @variable(model, x, Bin)
x

julia> @variable(model, y)
y

julia> c = all_constraints(model, VariableRef, MOI.ZeroOne)
1-element Vector{ConstraintRef{Model, MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.ZeroOne}, ScalarShape}}:
 x binary

julia> VariableRef(c[1])
x

julia> VariableRef.(all_constraints(model, VariableRef, MOI.ZeroOne))
1-element Vector{VariableRef}:
 x
```

**Comment by mlubin** [comment]
Does the internal model actually store a list of integer/binary variables that would avoid an O(num variables) pass? It's hard to imagine that `relax_integrality` could be implemented in O(num integers) versus O(num variables). That said, 44 seconds seems like too long to iterate through a list of 1M variables.

**Comment by odow** [comment]
> Does the internal model actually store a list of integer/binary variables that would avoid an O(num variables) pass?

No. It still does an O(num variables) pass to see what variables are discrete.

I assume the issue is that `info_pre_relaxation = map(v -> (v, _info_from_variable(v)), all_variables(model))` involves getting _everything_ related to a variable, the bounds, the starting value, integer and binary status, name, for _every_ variable in the model and allocating space for all of that, only to end up using a few of the fields.
