### ISSUE TITLE
Tables.jl support for results

### ISSUE THREAD

**Issue by hellemo** [jump-dev/JuMP.jl#3096]
We are considering moving the Tables.jl support for results from SparseVariables.jl to another package. (https://github.com/hellemo/SparseVariables.jl/issues/20). One issue then is whether support for the default containers from JuMP should be in a separate package from the SparseVariables type(s) or not. 

One alternative would be to add `Tables.jl` support for `DenseAxisArrays` and `SparseAxisArrays` to JuMP, as Tables is designed to be a light dependency (and keep the Tables support for our own types in our package). What do you think?

Some other things to consider (that might go together with this or belong in separate issues) are:

* It would be nice if `DenseAxisArrays` and `SparseAxisArrays` would also store the subindex names/index_vars, in our current implementation these have to be added explicitly when generating e.g. a `DataFrame` with the variable values from the solver (kind of a follow-up to https://github.com/jump-dev/JuMP.jl/pull/3088). With names stored with the container, one could generate result tables with good default column names automatically.
* Performance of reading results from solvers. I haven't looked into this yet, but getting large results feels kind of slow. Fast read of results that can easily be dropped into dataframes, plots, csv etc would be a nice usability improvement.

**Comment by odow** [comment]
Related https://discourse.julialang.org/t/efficient-serialization-of-jump-results/87896

cc @jd-foster 

I haven't really looked at the Tables.jl stuff, but what would the output be? Columns with the keys and then one value column? That could be quite nice, and would work for both Dense and Sparse

**Comment by hellemo** [comment]
Yes, exactly. Tables support for Dense is already implemented in SparseVariables, and I think Sparse is in the works (@trulsf ?)

For the example in the readme (after solving):
```
julia> # Read solution values for u (DenseAxisArray)
       DataFrame(table(u, :u, :car, :year))
12×3 DataFrame
│ Row │ car    │ year  │ u       │
│     │ String │ Int64 │ Float64 │
├─────┼────────┼───────┼─────────┤
│ 1   │ ford   │ 2000  │ 1.0     │
│ 2   │ bmw    │ 2000  │ 1.0     │
│ 3   │ opel   │ 2000  │ 1.0     │
│ 4   │ ford   │ 2001  │ 1.0     │
│ 5   │ bmw    │ 2001  │ 1.0     │
│ 6   │ opel   │ 2001  │ 1.0     │
│ 7   │ ford   │ 2002  │ 1.0     │
│ 8   │ bmw    │ 2002  │ 1.0     │
│ 9   │ opel   │ 2002  │ 1.0     │
│ 10  │ ford   │ 2003  │ 1.0     │
│ 11  │ bmw    │ 2003  │ 1.0     │
│ 12  │ opel   │ 2003  │ 1.0     │

julia> using PrettyTables

julia> pretty_table(table(y)) # SparseVarArray
┌──────┬──────┬─────┐
│  car │ year │   y │
├──────┼──────┼─────┤
│  bmw │ 2001 │ 0.0 │
│ ford │ 2001 │ 0.0 │
│ ford │ 2000 │ 0.0 │
│  bmw │ 2002 │ 0.0 │
└──────┴──────┴─────┘
```

**Comment by odow** [comment]
This could actually be quite nice. Happy to review a PR if you want to make one?

**Comment by hellemo** [comment]
Sure, will get back to you with a PR. No promises on timeline, though.
