### ISSUE TITLE
I/O functions fail in NL files with models with quadratic `@constraint` and `@objective`

### ISSUE THREAD

**Issue by felipemarkson** [jump-dev/JuMP.jl#3100]
Hi!

I was trying to use `AmplNLWriter.jl` in some tests when I realized that JuMP's I/O functions fail to keep quadratic `@constraint` and `@objective`.

Here is a minimum example:

```julia
using JuMP

model = Model()
@variable(model, 0 <= x <= 1)
@constraint(model, (x + 1)^2 <= 2)
@objective(model, Max, x^2)

write_to_file(model, "model.nl")

model2 = read_from_file("model.nl")

print("$model") 
# Max x²
# Subject to
#  x² + 2 x ≤ 1.0
#  x ≥ 0.0
#  x ≤ 1.0

print("$model2")
# Max 0
# Subject to
#  _[1] ≥ 0.0
#  _[1] ≤ 1.0
```

_NOTE:  Using `@NLconstraint` and `@NLobjective` I found the same issue_ 

cc @Ibrahim-a-Ibrahim

**Comment by odow** [comment]
Transferring this back to JuMP. It's a bug copying the `NL.Model` into the JuMP model. Everything exists at the MOI level, we're just loosing information at the JuMP level.

**Comment by odow** [comment]
Fix is here: https://github.com/jump-dev/JuMP.jl/pull/3101
