### ISSUE TITLE
ERROR: LoadError: ReadOnlyMemoryError()

### ISSUE THREAD

**Issue by rhemeim1** [jump-dev/JuMP.jl#3105]
I m trying to import a txt file into Julia and it has an array of 25,728 X 334 , I get: ERROR: LoadError: ReadOnlyMemoryError()
<img width="703" alt="Screen Shot 2022-10-06 at 12 01 00 PM" src="https://user-images.githubusercontent.com/89939313/194362295-2eac8793-4004-4a66-8aa9-f13ab0f2edbb.png">

**Comment by mlubin** [comment]
Closing since nothing in this report suggests an issue with JuMP. Please use https://discourse.julialang.org/ for questions like these.

As for the issue itself: Julia doesn't perform especially well when you stuff data into code. Try reading the array in a standard format like csv.
