### ISSUE TITLE
Incorrect handling of complex coefficients in GenericAffExpr

### ISSUE THREAD

**Issue by julian-upc** [jump-dev/JuMP.jl#3111]
Complex cofficients of variables in `GenericAffExpr`s appear to be handled incorrectly. 

An example is the following. I'll start with the setup code:
```
julia> using JuMP

julia> m = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(m,x)
x

julia> e = GenericAffExpr{ComplexF64, JuMP.VariableRef}()
(0.0 + 0.0im)

julia> e += x+1
x + (1.0 + 0.0im)

julia> f = 1.0im * e
(0.0 + 1.0im) x + (0.0 + 1.0im)

julia> typeof(f)
GenericAffExpr{ComplexF64, VariableRef}
```
All of this works fine, but here comes the bug: multiplying `f = i x + i` by `i` should give `- x - 1`, but actually yields `x - 1`:
```
julia> 1.0im * f
x + (-1.0 + 0.0im)
```
This is especially weird given that
- multiplication by `i` works in some cases, given that `i (x+1) = i x + i` is calculated correctly
- the bug only affects the coefficient of the variable, not of the constant of the affine expression.

**Comment by odow** [comment]
This was actually a printing problem, not a correctness issue 😆Fixed in https://github.com/jump-dev/JuMP.jl/pull/3112
