### ISSUE TITLE
Add documentation for Complex numbers

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#3114]
As suggested by @ccoffrin in https://github.com/jump-dev/JuMP.jl/pull/3109#issuecomment-1287043601

**Comment by odow** [comment]
We've added a bunch of stuff for complex-valued variables and constraints recently. These need a dedicated section of the manual, and a tutorial or two.

x-ref:

 - https://github.com/jump-dev/JuMP.jl/pull/3134
 - https://github.com/jump-dev/JuMP.jl/pull/3109

**Comment by odow** [comment]
I've added docs in #3141. There's still scope for a tutorial.

**Comment by odow** [comment]
This is largely done, so closing in favor of https://github.com/jump-dev/JuMP.jl/issues/2348#issuecomment-1341644412
