### ISSUE TITLE
set_time_limit_sec: take Dates.Period as argument?

### ISSUE THREAD

**Issue by dourouc05** [jump-dev/JuMP.jl#3115]
Currently, `set_time_limit_sec` only takes a real number of seconds as arguments. What about taking the Julia standard for durations, `Dates.Period` (standard library)? The only goal would be to make this function easier to use from Julia if you already use standard-library features for time.

Its implementation could look like this: 

```
function set_time_limit_sec(model, time::Dates.Period)
  set_time_limit_sec(model, floor(rd.timeout, Nanosecond).value * 1.0e-9)
  return
end
```

**Comment by odow** [comment]
I'm usually not in favor of expanding the surface area of the API like this. It just makes for more ways of doing the same thing. What's the motivation? When is this useful? Where does the `Dates.Period` come from that couldn't otherwise be a `Float64`?

**Comment by dourouc05** [comment]
The goal would be twofold: make JuMP more compatible with Julia in general (using a semantic type instead of a random float) and the code would much much more readable. Instead of writing `set_time_limit_sec(model, 24 * 60 * 60)` or worse `set_time_limit_sec(model, 86400)`, you could do `set_time_limit_sec(model, Hour(24))`, with almost zero chance of making a typo there.

**Comment by mlubin** [comment]
Seems like a reasonable helper to have at the JuMP level. The name would need to be `set_time_limit` as `_sec` doesn't make sense for a `Period` value.
