### ISSUE TITLE
Setting Optimizer Attributes on an OptimizerWithAttributes

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/JuMP.jl#3128]
Thought,  should `set_optimizer_attribiute` be defined for objects of type `OptimizerWithAttributes`, similarly to how it works for the type `Model`?

For example,
```
solver = JuMP.optimizer_with_attributes(Ipopt.Optimizer)
if <some condition>
    JuMP.set_optimizer_attribiute(solver, "tol", 1e-6)
end
```

my current work around, which is not too bad,
```
options = Dict{String,Any}()
if <some condition>
    options["tol"] = 1e-6
end
solver = JuMP.optimizer_with_attributes(Ipopt.Optimizer, options...)
```

**Comment by ccoffrin** [comment]
note from @odow 

> Probably should be in MOI, for `set(::OptimizerWithAttributes, ::RawOptimizerAttribute, value)`

**Comment by blegat** [comment]
I never thought of that but it's a good idea
