### ISSUE TITLE
Allow using ternary operator inside `@constraint`

### ISSUE THREAD

**Issue by hdavid16** [jump-dev/JuMP.jl#3183]
It would be great to do something like this:
```julia
m=Model()
@variable(m,x)
@constraint(m, [i=1:2],
    i == 1 ? exp(x) <= 0 : x^2 <= 0
)
```
Currently, this gives the error:
```julia
Unsupported constraint expression: we don't know how to parse constraints containing expressions of type :if.
```
This is, however, supported in `@expression` (the macro below does work):
```julia
@constraint(m, [i=1:2],
    i == 1 ? exp(x) : x^2
)
```

Tested in JuMP v.1.6.0

Current workaround is to use the ternary operator in `@expression` and then use that expression to build the needed constraints.

**Comment by odow** [comment]
Multiple problems here:

 * `@constraint` doesn't support `exp`
 * Second example doesn't form a constraint

> This is, however, supported in `@expression`
> Current workaround is to use the ternary operator in @expression and then use that expression to build the needed constraints.

Not sure what you mean? This shouldn't work in `@expression` because it doesn't support `exp`.

The correct way to write this is:
```Julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x)
x

julia> @NLconstraint(model, [i=1:2], ifelse(i == 1, exp(x), x^2) <= 0)
2-element Vector{NonlinearConstraintRef{ScalarShape}}:
 ifelse(1.0 == 1.0, exp(x), x ^ 2.0) - 0.0 ≤ 0
 ifelse(2.0 == 1.0, exp(x), x ^ 2.0) - 0.0 ≤ 0
```

**Comment by hdavid16** [comment]
Yes, you are right, `exp` is nonlinear. Instead of `exp(x) <= 0`, say `x <= 0` instead.

Ok, I see that I can actually use the ternary operator if I wrap it in parenthesis. For example,
```julia
@constraint(m,[i=1:3], x <= (i == 3 ? 0 : 2))
```
The above works as long as the ternary operator part is in parenthesis. Otherwise, it errors.

Thanks for looking into this.
