### ISSUE TITLE
Mosek direct_model support

### ISSUE THREAD

**Issue by amirmm11** [jump-dev/JuMP.jl#3194]
When I use `direct_model(Mosek.Optimizer)`, I get this error:
```
ERROR: LoadError: MethodError: no method matching direct_model(::typeof(Mosek.Optimizer))
```
It seems that JuMP does not support direct_model for Mosek.

Thanks

**Comment by jd-foster** [comment]
I think you want the syntax `direct_model(Mosek.Optimizer())`: note the `()` after `Optimizer`.
Docs: https://jump.dev/JuMP.jl/stable/reference/models/#JuMP.direct_model

**Comment by amirmm11** [comment]
Thank you @jd-foster
