### ISSUE TITLE
Provide diagnostics mode to pinpoint source of NaNs

### ISSUE THREAD

**Issue by davidanthoff** [jump-dev/JuMP.jl#320]
This continues a discussion started in #318.

[This](https://gist.github.com/davidanthoff/2e7a3ed62e20a6506dbb) model now solves, but we now know that there are iterations where it returns NaNs. I would like to be able to pinpoint the exact expression where the NaN is introduced, so that I can double check whether this is due to an error in my model, or whether I'm ok with this.

This is obviously not trivial at all, because the NaN could also be generated in a derivative, so in those cases ideally the diagnostic would say something like "the NaN was introduced in part x of the gradient of expression y" or something like that.

**Comment by mlubin** [comment]
This discussion is very old and I don't expect any progress on providing NaN diagnostics unless someone is willing to do the work. I'm tempted to close.
