### ISSUE TITLE
Error with semicolon/sum in nonlinear constraint

### ISSUE THREAD

**Issue by Robbybp** [jump-dev/JuMP.jl#3224]
I recently hit the error mentioned [here](https://discourse.julialang.org/t/error-reducing-over-an-empty-collection-is-not-allowed/47410) and have been updating all my sums to use `; init = 0` instead of `, init = 0` to guard against empty generators. When I make this change to sums in `@NLconstraint`s, I get "UndefVarError: init not defined". Is this intended behavior? If so, I think the error message could be more clear.

Interestingly, `sum(generator, init = 0)` seems to work in NLconstraint even when the generator is empty.

I'm using JuMP 1.8.0. Code to reproduce:
```julia
using JuMP
m = Model()
@variable(m, v[1:3])
@NLconstraint(m, nlcon, sum(v[i] for i in 1:3; init = 0) == 1)
```

**Comment by odow** [comment]
Fixed in https://github.com/jump-dev/JuMP.jl/pull/3226. The nonlinear interface didn't support `init`.
