### ISSUE TITLE
Renaming MathOptInterface -> MOI is breaking for some external packages

### ISSUE THREAD

**Issue by lassepe** [jump-dev/JuMP.jl#3233]
The latest release has renamed `MathOptInterface` internally to `MOI`. Some external packages, [like LazySets.jl](https://github.com/JuliaReach/LazySets.jl/blob/b11803321cd10ce904198d8abcf19759f9257f1d/src/Initialization/init_JuMP.jl#L1) referenced this name and are now broken. It may be argued that LazySets.jl should not "steal" MOI out of the JuMP scope but rather should depend on it directly but, for now, it may be wise to add an alias `const MathOptInterface = MOI` to avoid this kind of downstream breakage.

**Comment by blegat** [comment]
Not sure so many packages would break, what LazySets was doing seems quite uncommon.
JuMP was defining the MOI symbol and recommending to use it. LazySets was getting `JuMP.MathOptInterface`.

**Comment by lassepe** [comment]
Would accessing `JuMP.MOI` be considered "stable" (until the next breaking JuMP release at least)?

**Comment by lassepe** [comment]
Or is the better fix to depend on MOI directly in LazySets (not going through JuMP)?

**Comment by blegat** [comment]
When you do `using JuMP`, you can assume `MOI` is available. Otherwise, you can depend on MOI and do `import MathOptInterface as MOI`. I would stick to either of these two options although I assume `JuMP.MOI` should be available as well if we guarantee that `using JuMP` will export `MOI`.

**Comment by lassepe** [comment]
Okay, great. I will close this (and the PR) then.

**Comment by blegat** [comment]
Thanks for letting us know about the issue.

**Comment by odow** [comment]
>  LazySets was getting JuMP.MathOptInterface

Yes. I think getting a package through another package is a private implementation detail?

The constant `MOI` is exported, and so it's a public Symbol that can be relied upon to be non-breaking in future releases;

https://github.com/jump-dev/JuMP.jl/blob/385c72fa7e62187672ec79609e0fda7baf8d5250/src/JuMP.jl#L802-L804
