### ISSUE TITLE
[Q] Support of M1 chipset

### ISSUE THREAD

**Issue by yordiak** [jump-dev/JuMP.jl#3239]
This is more a question, which I remember that a similar one posted here before a couple of years. 

I am running julia v1.8.5 (arm) and the latest supported version of JuMP is 0.23.2

I am wondering if you are planning to support Apple's chipset and so, to be able to take full advance of the JuMP's feature. Or should I install the intel version?

**Comment by odow** [comment]
See https://github.com/jump-dev/JuMP.jl/issues/2971. JuMP works fine on M1, although some solvers (Cbc and Clp) do not work.
