### ISSUE TITLE
missing Grisu

### ISSUE THREAD

**Issue by bkalpert** [jump-dev/JuMP.jl#3297]
With today's update, I get this error when include'ing my file using JuMP:

[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]
ERROR: LoadError: ArgumentError: Package JuMP does not have Grisu in its dependencies:

Apparently the recent move of Grisu out of Base is to blame.

**Comment by odow** [comment]
JuMP doesn't use Grisu.

What is `import Pkg; Pkg.status()`? I think you must have installed an old incompatible version of JuMP somehow?

**Comment by bkalpert** [comment]
Thank you: removing some solvers and JuMP, then reinstalling cleared this up.
