### ISSUE TITLE
Add/improve solver documentation in documentation

### ISSUE THREAD

**Issue by juliohm** [jump-dev/JuMP.jl#3307]
Recently I attempted to use HiGHS.jl on a quadratic program and it worked just fine. The documentation mentions that HiGHS.jl only supports (MI)LP though. It would be great if the docs could be reviewed or even updated automatically from files stored in solver repositories:

https://jump.dev/JuMP.jl/stable/installation/#Supported-solvers

Can you please confirm that HiGHS.jl can be used with programs of the `minimize ||Ax - b||_2^2` with optimization variable `x`?

**Comment by odow** [comment]
Recent versions of HiGHS support a quadratic objective, but not quadratic constraints.

**Comment by odow** [comment]
> It would be great if the docs could be reviewed or even updated automatically from files stored in solver repositories:

I've thought about this and talked about it a few times. But it's quite difficult and not obvious what the right solution is.

The existing categories are also quite coarse and don't adequately cover some of the quirks of various solvers. It also omits bridges. You could imagine that the table might change if we added a new bridge to MOI...

One approach would be to require a standardized README.md, and then pull those into the documentation. 

The doc build is already long enough that I don't fancy installing 30 solvers and then dynamically figuring out what constraint types are supported.
