### ISSUE TITLE
Broken getindex with no arguments

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#3313]
The syntax `x[]` works if `x` has only one element:
```julia
julia> x = [1]
1-element Vector{Int64}:
 1

julia> x[]
1

julia> x = [1, 2]
2-element Vector{Int64}:
 1
 2

julia> x[]
ERROR: BoundsError: attempt to access 2-element Vector{Int64} at index []
Stacktrace:
 [1] throw_boundserror(A::Vector{Int64}, I::Tuple{})
   @ Base ./abstractarray.jl:703
 [2] checkbounds
   @ ./abstractarray.jl:668 [inlined]
 [3] _getindex
   @ ./abstractarray.jl:1273 [inlined]
 [4] getindex(::Vector{Int64})
   @ Base ./abstractarray.jl:1241
 [5] top-level scope
   @ REPL[4]:1
```
This doesn't work anywork for a vector with JuMP types because of https://github.com/jump-dev/JuMP.jl/pull/3237
This broke DiffOpt for instance: https://github.com/jump-dev/DiffOpt.jl/pull/238

**Comment by odow** [comment]
I don't understand why `x[]` is meant to work iff there is one element. Is that intended behavior in Julia? Is it documented?
