### ISSUE TITLE
Unable to use Index Variables with Declaring Variable Sets

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#3336]
We can use container indices when defining things like bounds:
```julia
using JuMP
model = Model()
@variable(model, x[i in 1:2] >= i)
```
However, when we use try to use `i` for sets, it is undefined:
```julia
julia> @variable(model, y[i in 1:2] in MOI.EqualTo(i))
ERROR: UndefVarError: i not defined
Stacktrace:
 [1] macro expansion
   @ C:\Users\bbgui\.julia\packages\JuMP\jKsOs\src\macros.jl:136 [inlined]
 [2] top-level scope
   @ REPL[10]:1

julia> @variable(model, y[i in 1:2], set = MOI.EqualTo(i))
ERROR: UndefVarError: i not defined
Stacktrace:
 [1] macro expansion
   @ C:\Users\bbgui\.julia\packages\JuMP\jKsOs\src\macros.jl:136 [inlined]
 [2] top-level scope
   @ REPL[11]:1
```
This came up with us trying to set different initial values in `ParametricOptInterface.Parameter` for each parameter.

**Comment by odow** [comment]
Hmm. I would have expected this to work, but I can see why it doesn't.

The macro expands into something like
```Julia
y = add_variable(
    model, 
    build_variable(
        error,
        Containers.container(
            (i,) -> build_variable(
                error,
                JuMP.VariableInfo(false, NaN, false, NaN, false, NaN, false, NaN, false, false)
            ), 
            Containers.vectorized_product(Base.OneTo(1:2)), 
            Containers.AutoContainerType, 
            Any[:i],
        ),
        MOI.EqualTo(i),
    ),
    "",
)
```
so we're not expanding the set argument into a container and then broadcasting over the container. We just assume the set is a constant.

I wonder if the right approach is to add special support for `Parameter`, with the syntax `:=`.

```Julia
using JuMP
model = Model()
@variable(model, p[i in 1:2] := i)
```

**Comment by pulsipher** [comment]
> I wonder if the right approach is to add special support for `Parameter`, with the syntax `:=`.
> 
> ```julia
> using JuMP
> model = Model()
> @variable(model, p[i in 1:2] := i)
> ```

I think this is a good idea.

> We just assume the set is a constant.

It would seem that there might be some cases where having varied set types might exist beyond parameters, so a minor refactor here to change this assumption could be useful. I can even take a look at the macro internals again to see what it would involve.

**Comment by odow** [comment]
I think I have a fix for the macro internals. Just running the tests.

**Comment by odow** [comment]
Ah. It's not that simple because of vector sets:
```Julia
@variable(model, x[i = 1:3] in MOI.EqualTo(1.0 * i))
@variable(model, x[i = 1:3] in SecondOrderCone())
```
It's okay to pass a vector of scalar sets to `build_variable`, but we need to pass a single instance of `SecondOrderCone()` for the latter.

Perhaps this issue is really asking for dedicated support for `MOI.Parameter`.

**Comment by blegat** [comment]
We have a way to distinguish them:
https://github.com/jump-dev/JuMP.jl/blob/160b22eded2d0ea77e71a4e68da7e060fda7b9e2/src/Containers/macro.jl#L167-L176

**Comment by odow** [comment]
Ah that might work.
