### ISSUE TITLE
[docs] Tutorial on SDP relaxation of AC-OPF using `HermitianPSDCone`

### ISSUE THREAD

**Issue by jd-foster** [jump-dev/JuMP.jl#3363]
This got somewhat lost: https://github.com/jump-dev/JuMP.jl/pull/3109#issuecomment-1287043601
* Happy for this issue to just be a new checkbox here:
https://github.com/jump-dev/JuMP.jl/issues/2348#issuecomment-1341644412

**Comment by odow** [comment]
I ended up deciding that it was a pretty complicated tutorial to have in the docs. There are a lot of data, and a lot of different variables and constraints. 

We also have this one for `HermitianPSDCone`: https://jump.dev/JuMP.jl/dev/tutorials/conic/quantum_discrimination/

But if you want to write a tutorial, then sure :smile:

**Comment by joaquimg** [comment]
I would suggest the 3 bus system in which you hard code all data in the example.

At the end of the example it might be useful to link do power models and rosetta opf.

**Comment by jd-foster** [comment]
Ok, let me see what I can cook up.
