### ISSUE TITLE
Bridges parametrized by complex type

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#3393]
In `add_bridge`, JuMP adds the `Float64` version of the bridge:
https://github.com/jump-dev/JuMP.jl/blob/e7f1bd1f311efb867f4737efab188ee72bed52cc/src/JuMP.jl#L497
This is an issue with PolyJuMP for instance which needs some bridge to act with complex coefficients as well:
https://github.com/jump-dev/SumOfSquares.jl/pull/300
One solution would be to have `add_typed_bridge` that adds the bridge already parametrized so that JuMP does not do `{Float64}`. Another option would be to have `add_complex_bridge`. It can also be keyword arguments to `add_bridge`.
Then we would need similar changes to `BridgeableConstraint`.

**Comment by odow** [comment]
A keyword `value_type = value_type(M)` would work?
