### ISSUE TITLE
difficult 

### ISSUE THREAD

**Issue by lynieya** [jump-dev/JuMP.jl#3419]
Welcome to JuMP! You can use this Github issue to suggest a new feature for JuMP.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thanks for contributing to JuMP!

**Comment by lynieya** [comment]
difficult

**Comment by odow** [comment]
Closing because this doesn't appear to be a feature request or a bug report.

If you're having difficulty using JuMP, please start a thread on our community forum: https://discourse.julialang.org/c/domain/opt/13

**Comment by lynieya** [comment]
ty
