### ISSUE TITLE
JuMP 1.14.0 fails to precompile on Julia 1.6.0/1

### ISSUE THREAD

**Issue by JackDunnNZ** [jump-dev/JuMP.jl#3461]
Seems like something doesn't play well between Julia 1.6.0 and 1.6.1 with the precompilation in JuMP 1.14:

```
julia> using JuMP
[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]
ERROR: LoadError: JuMP.NoOptimizer()
Stacktrace:
  [1] optimize!(model::JuMP.Model; ignore_optimize_hook::Bool, _differentiation_backend::MathOptInterface.Nonlinear.SparseReverseMode, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JuMP ~/.julia/packages/JuMP/KiENn/src/optimizer_interface.jl:436
  [2] optimize!(model::JuMP.Model)
    @ JuMP ~/.julia/packages/JuMP/KiENn/src/optimizer_interface.jl:417
  [3] top-level scope
    @ ~/.julia/packages/JuMP/KiENn/src/JuMP.jl:1233
  [4] eval(m::Module, e::Any)
    @ Core ./boot.jl:360
  [5] macro expansion
    @ ~/.julia/packages/JuMP/KiENn/src/JuMP.jl:1190 [inlined]
  [6] top-level scope
    @ ~/.julia/packages/SnoopPrecompile/1XXT1/src/SnoopPrecompile.jl:69
  [7] include
    @ ./Base.jl:386 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1213
  [9] top-level scope
    @ none:1
 [10] eval
    @ ./boot.jl:360 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [12] top-level scope
    @ none:1
in expression starting at /Users/jack/.julia/packages/JuMP/KiENn/src/JuMP.jl:11
ERROR: Failed to precompile JuMP [4076af6c-e467-56ae-b986-b466b2749572] to /Users/jack/.julia/compiled/v1.6/JuMP/jl_50Zae6.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base ./loading.jl:1360
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1306
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1021
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:914
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:901
```

It's fine on 1.6.2+, so bumping compat to that would be a viable alternative to chasing this down for a version nobody still uses :)

**Comment by odow** [comment]
Did you experience a problem with other JuMP versions? I don't think there is anything in v1.14 in particular that would cause this https://github.com/jump-dev/JuMP.jl/compare/v1.13.0...v1.14.0

This looks like it's coming from the `SnoopPrecompile` block, so I assume that means there was some bug in Julia v1.6.0 that needed fixing?

https://github.com/jump-dev/JuMP.jl/blob/b3c6f9f6ffb27c0dc905b63f210d685960d9f23e/src/JuMP.jl#L1185-L1233

Now it looks like `SnoopPrecompile` is deprecated and we should be using https://github.com/JuliaLang/PrecompileTools.jl instead...

**Comment by JackDunnNZ** [comment]
Whoops, you are totally right, it is the same on 1.13. I only noticed that build was broken today but it has been broken for a while...

**Comment by odow** [comment]
Taking a look into this now.

**Comment by odow** [comment]
I found this problem and we can fix in JuMP. PR incoming.

**Comment by odow** [comment]
Hopefully fixed in #3464. 

Just to double check it's not just my computer. Do you mind trying the branch?

`] add JuMP#od/fix-nospecialize`

**Comment by odow** [comment]
Another question is can you just move to latest Julia v1.6.x, or do you need a patch releases of JuMP with the fix?

**Comment by JackDunnNZ** [comment]
Works perfectly, thanks for the quick fix! 

No, we have no hard requirement to support versions older than the latest LTS patch release, we only support it on a best-effort basis, i.e. it works if it works.

**Comment by odow** [comment]
Yeah. One problem is that CI only tests the latest patch, and we already have a heavy CI load so I'm hesitant to add another build explicitly for v1.6.0. 

I assume from the fact that your build was broken for a while (and that we haven't had an earlier report on this) that there are essentially zero users who are both staying on v1.6.0 _and_ staying up to date with the latest JuMP releases.

**Comment by JackDunnNZ** [comment]
Definitely, makes sense
