### ISSUE TITLE
Nonlinear interfaces are not well distinguished in the docs

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#3471]
In the manual it is difficult to distinguish which tab leads to which interface since they are both "Nonlinear Modeling":
![tempsnip](https://github.com/jump-dev/JuMP.jl/assets/33848311/95dc7ac7-1030-4320-8d29-cc589ee503e2)

Also, the new interface comes last, so users will likely see the old API first.

**Comment by odow** [comment]
:+1: good point. I'll fix this
