### ISSUE TITLE
Documentation: links to API elements broken in Changelog

### ISSUE THREAD

**Issue by pierre-haessig** [jump-dev/JuMP.jl#3477]
In the [Release notes](https://jump.dev/JuMP.jl/stable/release_notes/) (Changelog), there are many links to API elements which are broken. For example in the changes for 1.14.0:

*“Added syntactic sugar for the MOI.Parameter set: ... [Parameter](https://jump.dev/JuMP.jl/api/JuMP/#JuMP.Parameter)”*.

This link yields a "404 File not found" error because the URL is https://jump.dev/JuMP.jl/api/JuMP/#JuMP.Parameter while it should be https://jump.dev/JuMP.jl/stable/api/JuMP/#JuMP.Parameter. I don't know why the "stable" folder is missing from URL.

Link to the relevant source code of the doc: [docs/src/changelog.md](https://github.com/jump-dev/JuMP.jl/blob/master/docs/src/changelog.md?plain=1#L16) at Line 16.

**Comment by odow** [comment]
Oops! That's pretty serious. Thanks for finding this. 

Looks like this was working in v1.13.0, so I assume that it broke because of https://github.com/jump-dev/JuMP.jl/pull/3455.

Documenter doesn't seem to be throwing any errors or warnings:

![image](https://github.com/jump-dev/JuMP.jl/assets/8177701/56484383-c39b-4e07-94c7-1b3693018d12)

cc @mortenpi

**Comment by odow** [comment]
Is this the right way to add a new API page?

https://github.com/jump-dev/JuMP.jl/blob/65533417f0e69081780c2670e4340415a1d3dedb/docs/DocumenterReference.jl#L204-L211

**Comment by odow** [comment]
Temporarily fixed in v1.14.1 release. Hopefully fixed in future by #3484

**Comment by mortenpi** [comment]
@odow I see #3480 was a revert to an older Documenter commit, right? Did you figure out what was going wrong here?

**Comment by odow** [comment]
I think the fix is https://github.com/jump-dev/JuMP.jl/pull/3484

**Comment by odow** [comment]
For the source of the new page, I was missing the `document.user.source` root.
