### ISSUE TITLE
missleading error message: `fix_value` for unfixed variable 

### ISSUE THREAD

**Issue by hdavid16** [jump-dev/JuMP.jl#3493]
The docstring for `fix_value` states that an error is thrown if the value of the variable has not been fixed. However, the error message states:
```julia
m = Model()
@variable(m,x)
fix_value(x)
ERROR: The index MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.EqualTo{Float64}}(1) is invalid. Note that an index becomes invalid after it has been deleted.
```
Perhaps a better error message could be used, indicating that the value does not exist?

**Comment by odow** [comment]
See https://github.com/jump-dev/JuMP.jl/pull/3494
