### ISSUE TITLE
`@variable` declarations returning empty container should have `VariableRef` element type

### ISSUE THREAD

**Issue by ExpandingMan** [jump-dev/JuMP.jl#3499]
**Is your feature request related to a problem? Please describe.**
On latest tagged, `@variable(m, x[1:0])` returns a `Vector{Any}`.  Because of this, code which uses `x` as an input cannot infer the containers element type.  An example of how this can go wrong is if one calls `sum(x)` it will throw an error because there is no `zero(Any)`, where as `zero(VariableRef)` gives a zero `AffExpr`.

**Describe the solution you'd like**
The simplest solution would be to check for empty returns and convert them to `Array{VariableRef}`.  However, I realize that this ignores the possibility of other variable types, so, alternatively, it might be nice to add a keyword argument.  Preferably, this would still default to something other than `Any`.

**Describe alternatives you've considered**
You can `convert` the result, but it seems undesirable to have to do the check.

**Additional context**
I think previous versions of JuMP returned a `VariableRef` container, but I haven't verified this.

**Comment by odow** [comment]
JuMP@1.0.0 produced:

```julia
julia> using JuMP

julia> model = Model();

julia> @variable(model, x[1:0])
VariableRef[]
```

Latest `master` produced:
```Julia
julia> using JuMP

julia> model = Model();

julia> @variable(model, x[1:0])
GenericVariableRef[]
```
so this is a regression.

Let me take a look.

**Comment by odow** [comment]
Ah. This is because `model` is a non-const global, so inference can't figure out the return type of the variable:
```Julia
julia> using JuMP

julia> model = Model();

julia> @variable(model, x[1:0])
GenericVariableRef[]

julia> add_var(model) = @variable(model, y[1:0])
add_var (generic function with 1 method)

julia> add_var(model)
VariableRef[]
```

**Comment by ExpandingMan** [comment]
I'm confused, I was getting `Any[]` when the type of `Model` should have been inferable.  I'll try to come up with a MWE when I get a chance.

**Comment by odow** [comment]
I didn't try the latest tag yet. I could see how that might return `Any`. 

I think I have a fix for the underlying issue. Just running the tests.

**Comment by odow** [comment]
I found your `Any`:

```julia
julia> m = (;m = Model());

julia> @variable(m.m, x[1:0])
Any[]
```
