### ISSUE TITLE
New nonlinear expression stuff doesn't support `min` properly

### ISSUE THREAD

**Issue by davidanthoff** [jump-dev/JuMP.jl#3508]
On `master` with the new non linear expression, one cannot call `min` on two `AffExpr` because `min` internally just calls `isless`, and that is one of the functions that doesn't have operator overloading for the JuMP expression types.

I think the solution is presumably that JuMP needs to add a `min` method that internally uses `JuMP.op_strictly_less_than` (or one of its variants), right?

**Comment by odow** [comment]
Oops. This was just an oversight. I added `min` and `max` support to MOI after I had started working on #3106 and never copied across the new features...the perils of working on a branch for one year.

See #3509
