### ISSUE TITLE
Drop zeros for nonlinear functions

### ISSUE THREAD

**Issue by mcosovic** [jump-dev/JuMP.jl#3510]
Hello,

It would be quite beneficial to incorporate a drop zeros feature akin to the functionality found in affine or quadratic functions.

**Comment by pulsipher** [comment]
You should refer to the conversations in #3498 and #3502.

**Comment by odow** [comment]
Thanks for the report, it's really helpful to hear feedback.

I'm going to close this in favor of #3498, but the fact it came up within hours of the release means that we probably need to at least fix the `0.0 + terms` that appear.

Let me know if you have any other suggestions.
