### ISSUE TITLE
Update location of 'database called multi.sqlite' for tutorial 'The multi-commodity flow problem'

### ISSUE THREAD

**Issue by JorritHimself** [jump-dev/JuMP.jl#3511]
Trying to play around with some examples from he tutorial. If I follow steps here: https://jump.dev/JuMP.jl/stable/tutorials/linear/multi/, or just download the .jl file from https://jump.dev/JuMP.jl/stable/tutorials/linear/multi.jl

This is confusing because few people would look up the location of the 'multi.jl' file in their JuMP instalation folder, and just create a folder with a .jl fiel for following along with this tutorial. 
Tthat means they need the database and it cannot be found by 
`db = SQLite.DB(joinpath(@__DIR__, "multi.sqlite"))`
 as the tutorial suggests.
The suggested file path 
`SQLite.DB("/home/runner/work/JuMP.jl/JuMP.jl/docs/build/tutorials/linear/multi.sqlite")`
is not helpful either as folder structure seems to have been updated. Should read:
`db = SQLite.DB("C:/Users/username/.julia/packages/JuMP/OUdu2/docs/src/tutorials/linear/multi.sqlite")`
or similar.

Took me rather a bit to locate. 
Suggest updating tutorial, or point to generic file pathof all tutorials somewhere, or includign a link that allows download of the multi.sqlite db in the tutorial.

Cheers

**Comment by odow** [comment]
Ah. The path is from the server that builds the docs.

We can add a link to: https://github.com/jump-dev/JuMP.jl/blob/master/docs/src/tutorials/linear/multi.sqlite
