### ISSUE TITLE
Refactor JuMP macros

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#3513]
We have a roadmap item for this: https://github.com/jump-dev/JuMP.jl/blob/master/docs/src/developers/roadmap.md, but it'd be useful to have an issue tracking it (x-ref https://github.com/jump-dev/JuMP.jl/pull/3500#issuecomment-1716511987).

I don't have any suggestions for what a "good" `macros.jl` file would look like, but it would be cleaner, with less code being run in the macros, and no user-facing changes.

**Comment by chriscoey** [comment]
Maybe precluded by the "no user-facing changes", but it would be great if macro changes could make it easier to use JuMP "programmatically". Possibly that could be a separate roadmap item. I don't know what needs to be done really because I'm no expert on macros etc, but I have had to resort to generating low level MOI code to build complex models programmatically.

**Comment by odow** [comment]
I think the non-macro version is just a documentation issue. We already have all of the machinery available in JuMP.

Given:
```julia
using JuMP
model = Model()
@variable(model, 0 <= x[1:I, 1:T] <= 100)
@constraint(model, [i in 1:I, t in 2:T], x[i, t] - x[i, t-1] <= 10)
@constraint(model, [i in 1:I, t in 2:T], x[i, t] - x[i, t-1] >= -10)
@objective(model, Min, sum(x))
```

One version of the non-macro version is
```julia
model = Model()
x = [VariableRef(model) for i in 1:I, t in 1:T]
set_lower_bound.(x, 0)
set_upper_bound.(x, 1000)
for i in 1:I, t in 2:T
    add_constraint(model, ScalarConstraint(x[i, t] - x[i, t-1], MOI.LessThan(10.0)))
    add_constraint(model, ScalarConstraint(x[i, t] - x[i, t-1], MOI.GreaterThan(-10.0)))
end
set_objective(model, MOI.MIN_SENSE, sum(x))
```

It's also possible to minimally use the macros:
```julia
model = Model()
x = [@variable(model) for i in 1:I, t in 1:T]
set_lower_bound.(x, 0)
set_upper_bound.(x, 1000)
for i in 1:I, t in 2:T
    f, set = x[i, t] - x[i, t-1], MOI.LessThan(10.0)
    @constraint(model, f in set)
    f, set = x[i, t] - x[i, t-1], MOI.GreaterThan(-10.0)
    @constraint(model, f in set)
end
sense, f = MOI.MIN_SENSE, sum(x)
@objective(model, sense, f)
```

But these don't give good names, and it's a bit more complicated if you want to construct containers that are not arrays, etc.

There's the much more complicated `build_variable` `add_variable` API, but that's really just for the macros. I don't think users gain much by using it. 

But I also don't think users gain much by using the non-macro JuMP syntax. If you're doing it programmatically, what's wrong with MOI?

**Comment by pulsipher** [comment]
From the extension side of things, it would be nice to have some of the common macro tooling be accessible. Specifically, I encounter macros of the form `@myobject(model, name[inds...], expr_to_parse, extra_args...; base_name = "", container = Automatic, kw_args...)` which creates a container or singleton of `myobject`s which are constructed with appropriate `build_myobject` and `add_myobject` functions. With this a lot of the internal methods and workflow used in the JuMP macros have to be duplicated. Examples include:
- `@finite_parameter`, `@parameter_function`: https://github.com/infiniteopt/InfiniteOpt.jl/blob/master/src/macros.jl
- `@disjunction`: https://github.com/hdavid16/DisjunctiveProgramming.jl/blob/d501c77dbc859c7594600f429a9c6cb068a88c88/src/macros.jl

Currently, JuMP provides `JuMP.Containers.build_ref_sets` to help with these macros, but that is it. It would be ideal to have a workflow where only the `build_myobject` and `add_myobject` functions have to be provided along with code to specify how `expr_to_parse` should be processed.

**Comment by odow** [comment]
I have been making reasonable progress. The `@variable` macro is...complicated.

Once I have things under control, I'll think about how we could expose some public API for building related calls.

**Comment by odow** [comment]
@pulsipher interested in your feedback on these changes.

The two most useful new additions are:
```
args, kwargs = Containers.parse_macro_arguments(error_fn, input_args)
```
and 
```
Containers.container_name(ref_expr)
```

I haven't made any larger structural changes, or introduced a "simple" way to write macros. There's still a lot of fluff around error checking the number of arguments, and dealing with optional keyword arguments. But I don't know if there is a good universal design.

The `@variable` and `@constraint` macros are pretty complicated, but `@objective` and `@expression` are pretty simple.

**Comment by odow** [comment]
Actually. I've simplified to `parse_ref_sets`:

https://jump.dev/JuMP.jl/previews/PR3620/api/JuMP.Containers/#Containers.container_code

**Comment by odow** [comment]
Perhaps the best way to look at the new code is https://github.com/jump-dev/JuMP.jl/tree/od/container-name/src/macros

Here's the `@expression` macro, which uses everything without being overly complicated like `@constraint` or `@variable`:
https://github.com/jump-dev/JuMP.jl/blob/ea44fe47b7e08e8739c743f17be50f56e25edee3/src/macros/%40expression.jl#L67-L103

**Comment by pulsipher** [comment]
Hi @odow, you've been busy! I definitely like the direction these are going in. Some suggestions to improve things further:

- Have `parse_macro_arguments` accept an `valid_kwargs` argument that defaults to something like `(:container,)` such that it errors if some unexpected keyword argument is given.
- Have `parse_ref_sets` do the check whether index is the same symbol as the model, this is used by every macro.
- Perhaps have `container_code` accept the `kwargs` output from `parse_macro_arguments` extract the requested container since every macro will follow the same workflow
- **It would be really really nice to make `_finalize_macro` public since this brings everything together and its current implementation is already general enough to handle extensions.**
- Perhaps make `_macro_error` public, it is a small function, but every extension macro I have made ends up repeating it.

To guide refining the API, perhaps you could make a PR in JuMP that I could use to make an InfiniteOpt PR that tests out the new API.

**Comment by odow** [comment]
1. Good idea
 2. Something like `forbidden_indices::Vector{Symbol}`?
 3. I don't really know how this would work. Do you have an example of the code you'd like the macro to generate?
 4. Yeah I was thinking like `extension_finalize_macro_helper` or something
 5. Good idea

**Comment by pulsipher** [comment]
> Something like `forbidden_indices::Vector{Symbol}`?

Yes

> I don't really know how this would work. Do you have an example of the code you'd like the macro to generate?

For instance, right now in `@expression` you have:
```julia
args, kwargs = Containers.parse_macro_arguments(error_fn, input_args) 
# PUT CODE HERE to derive the code to define `index_vars`, `indices`, `code`
container = get(kwargs, :container, :Auto)
container_code = Containers.container_code(index_vars, indices, code, container)
```
By allowing the 4th argument of `container_code` to additionally accept the type of `kwargs` (which I believe is a Dict) then we don't have to do any processing of containers outside the API. Then we could have:
```julia
args, kwargs = Containers.parse_macro_arguments(error_fn, input_args) 
# PUT CODE HERE to derive the code to define `index_vars`, `indices`, `code`
container_code = Containers.container_code(index_vars, indices, code, kwargs)
```

> Yeah I was thinking like `extension_finalize_macro_helper` or something

Awesome!

**Comment by pulsipher** [comment]
One last suggestion that I forgot would be to make `_add_additional_args` public as well.

**Comment by odow** [comment]
Try #3620. I haven't made `_finalize_macro` public yet.

**Comment by pulsipher** [comment]
While I would prefer for `_finalize_macro` to be public, it is not too much trouble to copy it.

I tried out #3620 in InfiniteOpt.jl, see #3620 for details.
