### ISSUE TITLE
Nonlinear constraint MOI set value not converted to Float

### ISSUE THREAD

**Issue by hdavid16** [jump-dev/JuMP.jl#3540]
I notice the following:
```julia
julia> build_constraint(error, 1x, MOI.LessThan(1))
ScalarConstraint{AffExpr, MathOptInterface.LessThan{Float64}}(x, MathOptInterface.LessThan{Float64}(1.0))

julia> build_constraint(error, x^3, MOI.LessThan(1))
ScalarConstraint{NonlinearExpr, MathOptInterface.LessThan{Int64}}(x ^ 3, MathOptInterface.LessThan{Int64}(1))
```
Is it intended for the MOI set to stay as `Int64` for the nonlinear case? Or should it be converted to `Float64` as in the affine case?

**Comment by odow** [comment]
This is expected behavior of `build_constraint`.

There is `model_convert` which handles the case later on. `build_constraint` may delay promotion until it knows what the type of the model is.
