### ISSUE TITLE
Highlight Polyhedra.jl

### ISSUE THREAD

**Issue by jd-foster** [jump-dev/JuMP.jl#3541]
CDDLib is listed under solvers: https://jump.dev/JuMP.jl/dev/packages/CDDLib/
A question came up on Slack about using it from JuMP, since it wasn't apparent from the "Installation Guide" table that there was an interface via https://github.com/JuliaPolyhedra/Polyhedra.jl
Perhaps there can be a sentence, section or new category under Supported solvers for "PCL = Polyhedral Computation Libraries" or similar?

**Comment by odow** [comment]
We also use CDDLib in the docs here: https://jump.dev/JuMP.jl/stable/tutorials/conic/arbitrary_precision/#Rational-arithmetic

**Comment by odow** [comment]
Also cdd is in the list of supported solvers
<img width="910" alt="image" src="https://github.com/jump-dev/JuMP.jl/assets/8177701/7e699c66-86e8-48d7-a69b-1f5db441db26">

**Comment by odow** [comment]
I saw the question on Slack. I'm not really sure what needs to be changed in the JuMP docs.

**Comment by jd-foster** [comment]
Appreciate the info. I guess even just a sentence in the intro materials to say "you can do polyhedral computation things from JuMP: load CDD"?

**Comment by odow** [comment]
Isn't this more asking for better documentation about JuMP support in Polyhedra? 

So far, it's really just:

https://juliapolyhedra.github.io/Polyhedra.jl/stable/optimization/#Creating-a-polyhedron-from-the-feasible-set-of-a-JuMP-model

**Comment by jd-foster** [comment]
Sure. I guess I'm thinking about discoverability of `Polyhedra` from the perspective of someone coming from the JuMP side?  It's not exactly [When should you not use JuMP?](https://jump.dev/JuMP.jl/dev/should_i_use/#When-should-you-not-use-JuMP?) but, the case of: "You want to do polydehral computations".

**Comment by jd-foster** [comment]
👌🏻
