### ISSUE TITLE
Make `_DoNotConvertSet` Public

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#3549]
We need this for DisjunctiveProgramming. We need to intercept the `add_constraint` call be dispatching on our expression type along with the set (`_DoNotConvertSet`), but this is not public. Sorry I failed to bring this up in #3530.

**Comment by odow** [comment]
Ha, I was expecting this, just not so quickly: https://github.com/jump-dev/JuMP.jl/pull/3530#issuecomment-1761821650

**Comment by odow** [comment]
Here you go: https://github.com/jump-dev/JuMP.jl/pull/3552
