### ISSUE TITLE
Multiplying JuMP expression with UniformScaling absorbs the matrix

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#3553]
```julia
julia> @variable(model, x)

julia> rand(2, 2) - x * I
ERROR: MethodError: no method matching -(::Matrix{Float64}, ::AffExpr)

Closest candidates are:
  -(::RationalPoly, ::Any)
   @ MultivariatePolynomials ~/.julia/packages/MultivariatePolynomials/6TYc8/src/rational.jl:73
  -(::V, ::GenericAffExpr{C, V}) where {C, V<:AbstractVariableRef}
   @ JuMP ~/.julia/packages/JuMP/D44Aq/src/operators.jl:146
  -(::GenericQuadExpr, ::GenericAffExpr)
   @ JuMP ~/.julia/packages/JuMP/D44Aq/src/operators.jl:361
  ...

Stacktrace:
 [1] top-level scope
   @ REPL[39]:1
```
`x * I` cannot be a `UniformScaling` since the scaling should be a `Number` but and we cannot create a `Diagonal([x, x, ...])` since we don't know yet what is the dimension we'll need.

**Comment by odow** [comment]
I don't know what we can or should do here. The answer is to force people to use `I(2)`.

**Comment by odow** [comment]
I don't really want to add `MutableArithmetics.UniformScaling{<:AbstractMutable}` and have to deal with all the consequences?

**Comment by blegat** [comment]
Yes it seems like a rabbit hole. Maybe we could try to convince LinearAlgebra to accept Any instead of Number. I think they thought that they are only implementing * with Number. This is fine but they can still allow Any in the constructor when it's called explicitly. In a Matrix they didn't force the entries to be Number so why do it in UniformScaling ?

**Comment by odow** [comment]
Perhaps open an issue? This will be easier with upgradable stdlibs.

**Comment by odow** [comment]
Closing as too hard to fix. It can't be a common issue, because I don't remember it coming up on Discourse.

**Comment by jd-foster** [comment]
Could this give a better error message? For example,
```
Base.:-(a::Matrix, b::Union{JuMP.GenericVariableRef, JuMP.GenericAffExpr}) = error(
   "Subtraction between a Matrix and a JuMP variable is not supported: instead of A - x, " *
   "prefer A .- x for element-wise subtraction, or if you are modifying the diagonal entries of the matrix " *
   " do A - x * LinearAlgebra.I(n), where n is the diagonal length."
)
```

**Comment by blegat** [comment]
Yes, I think such error message for `:+(::Matrix, ::AbstractJuMPScalar)` would be useful
