### ISSUE TITLE
Starting values for constant expression

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#3559]
See https://discourse.julialang.org/t/wram-start-of-hermitianpsdcone-in-jump/105491/10?u=blegat

**Comment by odow** [comment]
So I implemented this locally, but I don't know about it.

Even if we fix the constant case, the example will still fail for `imag.(x)` because the lower-triangle is `-x`.

It also breaks our current rule of "iff the expression is convertible to a variable."

**Comment by blegat** [comment]
For the lower triangle, we could set the opposite of the starting value. It then set twice the same value to the variable. We could allow starting value if we have at most one variable and possible a nonzero constant and non-one coefficient

**Comment by odow** [comment]
So now our scope is starting to widen... How about we just add the `set_start_value` function from Discourse into the docs for HermitianPSD?

**Comment by odow** [comment]
See https://github.com/jump-dev/JuMP.jl/pull/3564
