### ISSUE TITLE
Operator with vector arguments

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMP.jl#3576]
I often have questions on how to define an nonlinear operator with several vector inputs.
We have the splatting section:
https://jump.dev/JuMP.jl/dev/manual/nonlinear/
but it doesn't explain what to do with multiple inputs.
I would probably write something in the doc like:
If you have a function `f(x::Vector, y::Vector, z::Real)` of length `nx` and `ny`, you can do
```julia
@operator(model, op_f, nx + ny + 1, (z, args...) -> f(collect(args[1:nx]), collect(args[nx .+ (1:ny)]), z))
```

**Comment by odow** [comment]
Yeah, we don't support operators with vector arguments. but we could improve the documentation.
