### ISSUE TITLE
Improve LaTeX Printing for `GenericNonlinearExpr`s 

### ISSUE THREAD

**Issue by pulsipher** [jump-dev/JuMP.jl#3604]
While adding better printing to DisjunctiveProgramming, I noticed some shortcomings with the LaTeX printing of `GenericNonlinearExpr`s. 

First, indexed variables such as `x[1]` are printed as `x[1]` and not `x_{1}`, since `function_string` is not called:
```julia
m = Model(); @variable(m, x[1:2])
@expression(m, x[1]^2.3)
```
![image](https://github.com/jump-dev/JuMP.jl/assets/33848311/6a29aee1-058a-40c0-8fa6-6905da646fb0)

It would also be nice to use LaTeX versions of operators where possible, at least for the more common ones. For example, it would be nice to use `\\leq` instead of `<=`:
```julia
@expression(m, x[1] <= x[2])
```
![image](https://github.com/jump-dev/JuMP.jl/assets/33848311/df9a80b0-617b-448a-af7a-e3b521dd4562)

This can even lead to problems for certain operators (e.g., `&&`):
```julia
@expression(m, x[1] && x[2])
```
![image](https://github.com/jump-dev/JuMP.jl/assets/33848311/33dcef08-3568-4031-89aa-875001d51fda)
Here, `&&` needs to be replaced with `\\wedge` to parse correctly.

**Comment by odow** [comment]
See https://github.com/jump-dev/JuMP.jl/pull/3609
