### ISSUE TITLE
shorthand for GenericAffExpr{T, GenericVariableRef{T}})

### ISSUE THREAD

**Issue by araujoms** [jump-dev/JuMP.jl#3634]
I've been using the new support for generic number types, it's amazing!

I was wondering if you could add a shorthand for `GenericAffExpr{T, GenericVariableRef{T}})` and `GenericAffExpr{Complex{T}, GenericVariableRef{T}})`, like currently we have `AffExpr` as a shorthand for `GenericAffExpr{Float64, GenericVariableRef{Float64}}`. I gets a bit unwieldy. For example `AffExpr{T}` and `AffExpr{Complex{T}}` would be great.

**Comment by odow** [comment]
Can you not define these constants in your own package/code? Do they need to be in JuMP?

It's just a single line, like this:
https://github.com/jump-dev/JuMP.jl/blob/817dc13e6e090ead3aace549deac903b6006189b/src/aff_expr.jl#L591-L597

We can't change `AffExpr` because that would be breaking.

**Comment by blegat** [comment]
I don't think it's possible to have both `AffExpr{T}` work and `AffExpr` default to `AffExpr{Float64}`

**Comment by odow** [comment]
> Why would it be breaking? Just let AffExpr alone default to Float64, and AffExpr{T} do the generic type.

You can't do this in Julia.

> Furthermore, I don't like releasing code with custom aliases, it hurts readability.

I also agree with this, and in retrospect, I probably would have preferred that we didn't use `AffExpr` :smile:

That line is some of the oldest code in JuMP:

https://github.com/jump-dev/JuMP.jl/commit/a1a95f37896b225067ef0a52db10d82da6295e69#diff-02dae21a59730ca257e3fc6e292b9958d9ce87d32be4a35b2af68a501f2b1f52R176

**Comment by araujoms** [comment]
I see, so `AffExpr` didn't start as a shorthand, but as an alias for backwards compatibility when `GenericAffExpr` was introduced. Well, it's still hand. In any case, it's clear that the answer is no so I'm closing the issue.
