### ISSUE TITLE
Constraint macro modifies expression

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#3638]
```julia
julia> using JuMP

julia> model = Model();

julia> @variable(model, 0 <= x <= 5);

julia> @expression(model, e, x + 5)
x + 5

julia> @constraint(model, -10 <= e <= 10)
x ∈ [-15, 5]

julia> e
x
```

**Comment by mlubin** [comment]
Oops, that's a bad one

**Comment by odow** [comment]
So this slipped by our tests because it's only a problem where the body of a function is a single identifier, like `:e`, and the constraint is:

 * a double-sided interval constraint
 * an explicit `f in Set()` constraint

Something like `e <= 1` doesn't trigger it.
