### ISSUE TITLE
@variable macro fails to resolve variables in 1.18.0

### ISSUE THREAD

**Issue by ianfiske** [jump-dev/JuMP.jl#3646]
Here's a MWE:

```
using JuMP

m = Model()
x = (lower_bound=5.0,)
@variable(m, set = MOI.GreaterThan(x.lower_bound))
```

With JuMP 1.18.0, this fails with the error

```
ERROR: UndefVarError: `x` not defined
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/JuMP/9tYtW/src/macros/@variable.jl:313 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/JuMP/9tYtW/src/macros.jl:375 [inlined]
 [3] top-level scope
   @ ~/julia-envs/jump-bug/minrepro.jl:6
```

In JuMP 1.17 and below, there is no error.

**Comment by odow** [comment]
I'll take a look. I recently refactored our macro handling, so this is my fault.

I guess I was right https://github.com/jump-dev/JuMP.jl/pull/3629#issuecomment-1858912840

> The main risk is probably esc scoping bugs

**Comment by odow** [comment]
See #3647

I guess the lesson is that when writing tests, we should prefer to use variables rather than literals so that we can check for scoping bugs like this.
