### ISSUE TITLE
Cannot `convert` an object of type Float64 to an object of type JuMP.NonlinearExpr

### ISSUE THREAD

**Issue by codercahol** [jump-dev/JuMP.jl#3699]
I have an array of nonlinear differentials (`a`, in the example below) that I use as part of an Euler integration step in finding an optimal trajectory. In some cases, one of the differentials is 0, but I haven't been able to figure out how to add it to the vector

Code for reproducing:

```
a = Vector{NonlinearExpr}(undef, 3)
a = 0.0
```

I've also tried
```
a = Vector{NonlinearExpr}(undef, 3)
a[1] = @expression(model, 0.0)
```

and
```
a = Vector{NonlinearExpr}(undef, 3)
a[1] = @NLexpression(model, 0.0)
```

I have it working with `a = Vector{Any}`, but I expect there is a better solution

**Comment by odow** [comment]
Closing as fixed. If you have follow-up questions, please use the forum and we can chat there :smile:

**Comment by codercahol** [comment]
ok thanks!
