### ISSUE TITLE
Documentation Request: List whether a solver supports Indicator Constraints

### ISSUE THREAD

**Issue by schlichtanders** [jump-dev/JuMP.jl#3701]
Using DisjunctiveProgramming.jl I was told that Indicator Constraints may actually be what I am looking for.

However unfortunately, Indicator Constraints don't have a bridge to Big-M notation, not are they listed on the solver's summary page whether it is supported or not.

It would be great to either 
- have a bridge
- or update the documentation to name whether a solver supports Indicator Constraints

**Comment by blegat** [comment]
You should find it in this list: https://jump.dev/JuMP.jl/stable/packages/Gurobi/#MathOptInterface-API
However, it seems to be supported in the MOI wrapper of Gurobi but not in this list. @odow will be able to help

**Comment by schlichtanders** [comment]
I was just pointed to the fact, that a bridge actually exists.

I was just falsely assuming there is no bridge. Probably because I read the Tips and Tricks section where Indicator constraints are mentioned to be only supported by a couple of solvers.

https://jump.dev/JuMP.jl/stable/tutorials/linear/tips_and_tricks/#Indicator-constraints

It would be great if this section is updated/deleted. Plus that the [section about Disjunctions](https://jump.dev/JuMP.jl/stable/tutorials/linear/tips_and_tricks/#Disjunctions) gets an alternative implementation using Indicator Constraints.

**Comment by odow** [comment]
> not are they listed on the solver's summary page whether it is supported or not.

This is an oversight on my part. I guess the script I ran didn't catch indicators :cry:

> It would be great if this section is updated/deleted

To clarify, what section?

> Plus that the [section about Disjunctions](https://jump.dev/JuMP.jl/stable/tutorials/linear/tips_and_tricks/#Disjunctions) gets an alternative implementation using Indicator Constraints.

I will add

**Comment by schlichtanders** [comment]
Thank you for your help.

I mean that the [Indicator section](https://jump.dev/JuMP.jl/stable/tutorials/linear/tips_and_tricks/#Indicator-constraints) does not need the Trick2 part, the manual workaround in case a solver does not support it. Instead mention that the MOI bridge already does that, as soon as one restricts the variables to a finite domain.
