### ISSUE TITLE
Multiple Ranges for variables

### ISSUE THREAD

**Issue by ymayer2006** [jump-dev/JuMP.jl#3715]
Welcome to JuMP! You can use this Github issue to suggest a new feature for JuMP.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thanks for contributing to JuMP!

**Comment by ymayer2006** [comment]
Is there a possibility to add multiple ranges for a specific variable, for example 0.4 <= x <= 1.6 or x = 0? I would really appreciate if someone could help me out

**Comment by odow** [comment]
Hi @ymayer2006,

If you're looking for "or x = 0" specifically, then use:
https://jump.dev/JuMP.jl/stable/tutorials/linear/tips_and_tricks/#Semi-continuous-variables

p.s., these questions are better asked on our forum: https://jump.dev/forum. We try to reserve the GitHub issues for bug reports and feature requests.

**Comment by odow** [comment]
Closing because I don't know if there is anything actionable to do here. If you have more usage questions, please ask on the forum :smile: https://jump.dev/forum
