### ISSUE TITLE
Model's print summary should include value type

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMP.jl#3802]
There's nothing to indicate that this is a `GenericModel{BigFloat}`:
```julia
julia> using JuMP

julia> file = joinpath(dirname(dirname(pathof(MOI))), "test", "FileFormats", "SDPA", "models", "example_A.dat-s")
"/Users/oscar/.julia/packages/MathOptInterface/2CULs/test/FileFormats/SDPA/models/example_A.dat-s"

julia> model = open(file, "r") do io
           return read(
               io,
               GenericModel{BigFloat};
               format = MOI.FileFormats.FORMAT_SDPA,
               number_type = BigFloat,
           )
       end
A JuMP Model
Minimization problem with:
Variables: 2
Objective function type: GenericAffExpr{BigFloat, GenericVariableRef{BigFloat}}
`Vector{GenericAffExpr{BigFloat, GenericVariableRef{BigFloat}}}`-in-`MathOptInterface.PositiveSemidefiniteConeTriangle`: 2 constraints
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.
```

**Comment by odow** [comment]
How about something like:
```Julia
julia> model
A JuMP Model
├ objective_sense: MIN_SENSE
│ └ objective_function_type: AffExpr
├ num_variables: 1
├ num_constraints: 2
│ ├ VariableRef in MOI.GreaterThan{Float64}: 1
│ └ VariableRef in MOI.Integer: 1
├ backend
│ ├ mode: AUTOMATIC
│ ├ solver_name: HiGHS
│ └ value_type: Float64
└ registered names
  └ :x
```

**Comment by blegat** [comment]
I like it, we could also say if there is a bridge layer and if there are any bridge in `bridge_type` (we can say nothing if `bridge_type` is empty

**Comment by odow** [comment]
So I wondered about this. There's merit to showing all of `backend(model)`. But this makes it too big.

What about adding something like ```├ backend: call `backend(model)` for more information```

**Comment by odow** [comment]
Bridges and caching optimizer and stuff is too complicated for general users.

Maybe we have just:
```
julia> model
A JuMP Model
├ value_type: Float64
├ objective_sense: MIN_SENSE
│ └ objective_function_type: AffExpr
├ num_variables: 1
├ num_constraints: 2
│ ├ VariableRef in MOI.GreaterThan{Float64}: 1
│ └ VariableRef in MOI.Integer: 1
└ registered names
  └ :x
```

**Comment by blegat** [comment]
We don't want to show all information but the bridge layer is a keyword argument to `JuMP.Model` we have `JuMP.add_bridge` so I thought we might add these too.
Not showing the backend at all as in your last comment is nice, the user can do `backend(model)` to see more.

**Comment by odow** [comment]
See #3803.

For the bridges: I wonder if some mix of `backend(model)` and `print_active_bridges(model)` is enough. The bridges are irrelevant for new users.
