### ISSUE TITLE
[docs] add datejada/rolling-horizon-example tutorial

### ISSUE THREAD

**Issue by datejada** [jump-dev/JuMP.jl#3811]
Hi,

I'm interested in using this package for our model development, especially for a rolling horizon application. Therefore, I've prepared an example using this package to implement a rolling horizon. You can find the example here:

https://github.com/datejada/rolling-horizon-example

I'd like to suggest referencing this example in the package documentation. If the development team agrees, I can create a pull request with the changes in the docs for your review.

Thank you, and I am looking forward to hearing from you.

BR,

Diego

**Comment by odow** [comment]
I've transferred this issue to JuMP, since I think this will make a nice "Rolling Horizon" tutorial:
https://github.com/jump-dev/JuMP.jl/tree/master/docs/src/tutorials/algorithms

It will help us advertise `Parameter`, and we can add POI to see if there is a performance benefit.

**Comment by odow** [comment]
Let me know if you want to make a PR, otherwise I'll likely have a stab at this tomorrow and include you as a co-author in the commit.

**Comment by datejada** [comment]
Hi @odow, Thank you for your reply and comments. So, the idea is to create a new file "rolling_horizon.jl" similar to the "cutting_stock_column_generation.jl" based on the Pluto notebook. Is that correct? If so, I can create the PR (probably during the weekend), and you can review it.
