### ISSUE TITLE
Ellipse fitting example

### ISSUE THREAD

**Issue by langestefan** [jump-dev/JuMP.jl#3893]
Hello,

I wrote a small program / notebook to fit ellipses to data using JuMP. 

It's quite visual and a nice demo so I thought it would be useful as an example to put under linear programming tutorials. 

Would you accept this as a PR?

**Comment by odow** [comment]
Sure. Open a PR and we can figure out the details.

**Comment by odow** [comment]
I'm going to close this issue (but please submit a PR).

Next time, just comment on https://github.com/jump-dev/JuMP.jl/issues/2348 instead :smile: I try to keep all the documentation issues in one place.

**Comment by odow** [comment]
Just make the PR and we can discuss there.

**Comment by langestefan** [comment]
Done: https://github.com/jump-dev/JuMP.jl/pull/3895
