### ISSUE TITLE
getvalue slow for nonlinear expressions

### ISSUE THREAD

**Issue by matthieugomez** [jump-dev/JuMP.jl#746]
Once the model is solved, `getvalue` takes a lot of time to return the result. Is it expected?
Gist here:  https://gist.github.com/matthieugomez/30f8145b9c0c333cfa10ca984428687a

**Comment by mlubin** [comment]
``getvalue`` on nonlinear expressions isn't expected to be fast, have a peek at the [code](https://github.com/JuliaOpt/JuMP.jl/blob/10769fb01462d77a46ed0549ac4e92c0a422ecff/src/nlp.jl#L1265).

**Comment by matthieugomez** [comment]
Thanks. Did you try the gist though? The optimization problem is solved in 11s but `getvalue` hangs forever.

**Comment by matthieugomez** [comment]
To be more precise:

With n = 500, I get
```julia
@time solve(m)
#  1.632312 seconds (3.61 M allocations: 291.463 MB, 36.34% gc time)
@time c = getvalue(c)
# 89.703773 seconds (550.96 M allocations: 35.474 GB, 21.51% gc time)
```
With n = 5000, getvalue hangs forever.

**Comment by mlubin** [comment]
Yep, it's slow. The workaround for now is to call ``getvalue`` on the variables and compute the nonlinear expressions using plain julia code.
